import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from '../server.js';
const directory=mkdtempSync(path.join(tmpdir(),'flow-browser-'));
const server=createServer({directory});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(7000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByRole('button',{name:'▷ Try flow',exact:true}).click();
 await page.getByLabel('Task',{exact:true}).fill('Fix search without changing the stored records.');
 await page.getByLabel('Acceptance checks',{exact:true}).fill('Empty search returns all records. Case-insensitive match works.');
 await page.getByRole('button',{name:'Start simulation',exact:true}).click();
 await page.getByRole('button',{name:'Simulate this step →',exact:true}).waitFor();
 await page.getByRole('button',{name:'Simulate this step →',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
 assert.match(await page.locator('.review-panel').textContent(),/My review/);
 await page.getByRole('button',{name:'Request changes',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('required'));
 await page.getByLabel('Review note',{exact:true}).fill('Include a regression check for empty queries.');
 await page.getByRole('button',{name:'Request changes',exact:true}).click();
 await page.getByRole('button',{name:'Simulate this step →',exact:true}).waitFor();
 await page.getByRole('button',{name:'Simulate this step →',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Continue',exact:true}).waitFor();
 assert.match(await page.locator('.review-panel').textContent(),/1 of 2/);
 await page.locator('[data-run-step]').first().click();
 assert.match(await page.locator('.output-panel').textContent(),/regression check/);
 assert.equal(await page.locator('.attempt').count(),2);
 mkdirSync('output',{recursive:true});
 await page.screenshot({path:'output/review-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 for(let i=0;i<3;i++) {await page.getByRole('button',{name:'Simulate this step →',exact:true}).click();}
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('heading',{name:'How did the flow feel?',exact:true}).waitFor();
 assert.match(await page.locator('.metrics').textContent(),/Not measured/);
 const snapshot=await (await fetch(url+'/api/state')).json();assert.equal(snapshot.runs[0].attempts.length,8);
 await page.getByRole('button',{name:'Try another flow with this task',exact:true}).click();
 await page.getByLabel('Flow',{exact:true}).selectOption(snapshot.flows[1].id);
 await page.getByRole('button',{name:'Start simulation',exact:true}).click();
 await page.getByRole('button',{name:'Stop simulation',exact:true}).click();
 await page.locator('#dialog').getByRole('button',{name:'Stop simulation',exact:true}).click();
 await page.getByRole('heading',{name:'You can start fresh.',exact:true}).waitFor();
 await page.reload();await page.getByRole('heading',{name:'You can start fresh.',exact:true}).waitFor();
 await page.getByRole('button',{name:'All runs',exact:true}).click();
 assert.equal(await page.locator('[data-open-run]').count(),2);
 await page.locator('[data-compare]').nth(0).check();
 await page.locator('[data-compare]').nth(1).check();
 await page.getByRole('button',{name:'Compare 2/2',exact:true}).click();
 await page.getByRole('heading',{name:'Compare flows',exact:true}).waitFor();
 assert.match(await page.locator('.comparison-notice').first().textContent(),/Same task & acceptance checks/);
 assert.equal(await page.locator('.compare-card').count(),2);
 assert.equal(await page.locator('.compare-card').getByText('Not measured',{exact:true}).count(),4);
 await page.screenshot({path:'output/compare-desktop.png',fullPage:true});
 await page.reload();await page.getByRole('heading',{name:'Compare flows',exact:true}).waitFor();
 const different=await (await fetch(url+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({flowID:snapshot.flows[0].id,flowVersion:1,task:'A different task',acceptance:'Different checks'})})).json();
 await page.goto(url+'/#compare/'+snapshot.runs[0].id+','+different.id);
 await page.reload();
 assert.match(await page.locator('.comparison-notice').first().textContent(),/Different tasks/);
 await page.getByRole('button',{name:'All runs',exact:true}).click();

 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('[data-open-run]').last().click();
 await page.screenshot({path:'output/run-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('Run browser checks passed: task creation, pause, required review note, retry, retained attempts, reload, completion, same-task rerun, cancellation, history, same-task and mismatched comparison, mobile.');
} finally {await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(directory,{recursive:true,force:true});}
