import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {CodexRuns} from '../lib/codex.js';import {claudeArgs,claudeUsage,discoverClaude} from '../lib/claude.js';
const provider={version:'fixture',models:[{id:'sonnet',efforts:['low']}]},input={agent:'claude',task:'Inspect',model:'sonnet',effort:'low',mode:'read-only'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function done(m,id){for(let i=0;i<200;i++){const r=m.get(id);if(!['preparing','running','stopping'].includes(r.status))return r;await sleep(20);}throw Error('timed out');}
function fixture(t,code){const root=mkdtempSync(path.join(tmpdir(),'skd-claude-'));const repo=path.join(root,'repo');execFileSync('git',['init','-b','main',repo]);writeFileSync(path.join(repo,'file.txt'),'original');execFileSync('git',['-C',repo,'add','.']);execFileSync('git',['-C',repo,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','fixture']);const binary=path.join(root,'claude');writeFileSync(binary,'#!/usr/bin/env node\n'+code,{mode:0o755});const manager=new CodexRuns(path.join(root,'data'),{discover:async()=>provider,claudeOptions:{binary,discover:async()=>provider}});t.after(()=>{manager.shutdown();rmSync(root,{recursive:true,force:true});});return {manager,repo,root,binary,project:{id:'p',name:'Fixture',folderPath:repo}};}
const success=`console.log(JSON.stringify({type:'result',subtype:'success',session_id:'claude-thread',result:'Done',usage:{input_tokens:10,cache_read_input_tokens:20,cache_creation_input_tokens:30,output_tokens:5},total_cost_usd:0.0123}));`;
test('Claude result persists normalized usage, model, cost, output and correlated tool activity',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();process.stdin.on('end',()=>{console.log(JSON.stringify({type:'system',subtype:'init',model:'resolved-sonnet'}));console.log(JSON.stringify({type:'assistant',message:{content:[{type:'tool_use',id:'tool-1',name:'Read',input:{file_path:'/private/fixture'}}]}}));console.log(JSON.stringify({type:'user',message:{content:[{type:'tool_result',tool_use_id:'tool-1',content:'private result'}]}}));console.log(JSON.stringify({type:'assistant',message:{content:[{type:'text',text:'Done'}]}}));${success}});`);const r=await manager.start(input,project);await assert.rejects(manager.start({...input,agent:'codex'},project),/already running/);const result=await done(manager,r.id);assert.equal(result.status,'completed',result.error);assert.equal(result.agent,'claude');assert.equal(result.output,'Done');assert.equal(result.resolvedModel,'resolved-sonnet');assert.equal(result.usage.inputTokens,60);assert.equal(result.usage.outputTokens,5);assert.equal(result.usage.cachedInputTokens,20);assert.equal(result.usage.cacheCreationInputTokens,30);assert.equal(result.cost,0.0123);assert.equal(result.toolActivity.coverage.status,'complete');assert.deepEqual(result.toolActivity.events.map(event=>[event.toolName,event.outcome]),[['Read','success']]);assert(!JSON.stringify(result.toolActivity).includes('/private/fixture'));assert(!JSON.stringify(result.toolActivity).includes('private result'));assert.equal(new CodexRuns(manager.directory).get(r.id).toolActivity.events.length,1);});
test('Claude runs in an isolated worktree and retains diff, not source edits',async t=>{const {manager,project,repo}=fixture(t,`process.stdin.resume();process.stdin.on('end',()=>{require('node:fs').writeFileSync('file.txt','changed');${success}});`);const r=await manager.start({...input,mode:'worktree'},project),result=await done(manager,r.id);assert.equal(result.status,'completed',result.error);assert.equal(readFileSync(path.join(repo,'file.txt'),'utf8'),'original');assert.match(result.diff,/changed/);assert.match(result.branch,/^claude\//);});
test('Claude error result is not successful even with exit zero',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({type:'result',subtype:'error_during_execution',is_error:true,errors:['Not entitled']})));`);const result=await done(manager,(await manager.start(input,project)).id);assert.equal(result.status,'failed');assert.match(result.error,/Not entitled/);assert.equal(result.usage,null);});
test('Claude stop and timeout retain terminal state',async t=>{const {manager,project}=fixture(t,'process.stdin.resume();setInterval(()=>{},1000);');const r=await manager.start(input,project);while(manager.get(r.id).status==='preparing')await sleep(10);manager.stop(r.id);assert.equal((await done(manager,r.id)).status,'cancelled');manager.timeoutMs=50;const second=await manager.start(input,project);assert.match((await done(manager,second.id)).error,/Runtime limit/);});
test('Claude tools exclude shell, delegation and read-only writes',()=>{for(const mode of ['read-only','worktree']){const args=claudeArgs({...input,mode});assert(args.includes('--restricted'));assert(args.includes('--safe-mode'));assert(args.includes('--strict-mcp-config'));const tools=args[args.indexOf('--tools')+1];assert(!/Bash|Agent|Task/.test(tools));assert.equal(tools.includes('Write'),mode==='worktree');assert(!args.includes('--dangerously-skip-permissions'));}assert.equal(claudeUsage({input_tokens:10}).inputTokens,null);});
test('Claude discovery rejects unauthenticated CLI and sanitizes signed-in result',async t=>{const {binary}=fixture(t,`const a=process.argv.slice(2);if(a[0]==='--version')console.log('Claude fixture');else if(a[0]==='--help')console.log('--restricted --safe-mode');else {console.log(JSON.stringify({loggedIn:false}));process.exitCode=1;}`);await assert.rejects(discoverClaude(binary),/claude auth login/);writeFileSync(binary,`#!/usr/bin/env node\nconst a=process.argv.slice(2);if(a[0]==='--version')console.log('Claude fixture');else if(a[0]==='--help')console.log('--restricted --safe-mode');else if(a[0]==='auth')console.log(JSON.stringify({loggedIn:true,email:'private@example.invalid'}));else{process.stdin.setEncoding('utf8');process.stdin.on('data',line=>{const q=JSON.parse(line);if(q.type!=='control_request')process.exit(1);console.log(JSON.stringify({type:'control_response',response:{request_id:q.request_id,response:{models:[{value:'sonnet',displayName:'Sonnet',supportsEffort:true,supportedEffortLevels:['low','medium','high','xhigh','max']},{value:'haiku',displayName:'Haiku'}]}}}));});}`,{mode:0o755});const d=await discoverClaude(binary);assert.equal(d.models.length,2);assert.deepEqual(d.models[0].efforts,['low','medium','high','xhigh','max']);assert.deepEqual(d.models[1].efforts,['default']);assert(!claudeArgs({...input,model:'haiku',effort:'default'}).includes('--effort'));assert(!JSON.stringify(d).includes('private@'));});
