import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {CodexRuns,usageFrom} from '../lib/codex.js';
const provider={available:true,version:'fixture',models:[{id:'fixture',efforts:['low']}]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function finished(manager,id){for(let i=0;i<200;i++){const r=manager.get(id);if(!['preparing','running','stopping'].includes(r.status))return r;await sleep(20);}throw new Error('Run did not settle');}
function fixture(t,code){const root=mkdtempSync(path.join(tmpdir(),'skd-codex-'));const repo=path.join(root,'repo');execFileSync('git',['init','-b','main',repo]);writeFileSync(path.join(repo,'file.txt'),'original\n');execFileSync('git',['-C',repo,'add','.']);execFileSync('git',['-C',repo,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','fixture']);const bin=path.join(root,'fake-codex');writeFileSync(bin,'#!/usr/bin/env node\n'+code,{mode:0o755});const manager=new CodexRuns(path.join(root,'data'),{binary:bin,discover:async()=>provider});t.after(()=>{manager.shutdown();rmSync(root,{recursive:true,force:true});});return {root,repo,manager,project:{id:'project',name:'Fixture',folderPath:repo}};}
const input={task:'Do task',model:'fixture',effort:'low',mode:'read-only'};
test('actual subprocess JSONL produces durable usage, output and deduplicated tool activity',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();process.stdin.on('end',()=>{console.log(JSON.stringify({type:'thread.started',thread_id:'fixture-thread'}));console.log(JSON.stringify({type:'item.started',item:{id:'call-1',type:'command_execution',command:'echo hidden-secret'}}));console.log(JSON.stringify({type:'item.completed',item:{id:'call-1',type:'command_execution',command:'echo hidden-secret',aggregated_output:'done',exit_code:0,status:'completed'}}));console.log(JSON.stringify({type:'item.completed',item:{id:'call-1',type:'command_execution',command:'echo hidden-secret',aggregated_output:'done',exit_code:0,status:'completed'}}));console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Actual fixture output'}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:100,cached_input_tokens:70,output_tokens:10}}));});`);await assert.rejects(manager.start({...input,model:'made-up'},project));const run=await manager.start(input,project);await assert.rejects(manager.start(input,project),/already running/);const done=await finished(manager,run.id);assert.equal(done.status,'completed');assert.equal(done.output,'Actual fixture output');assert.deepEqual(done.usage,{inputTokens:100,cachedInputTokens:70,outputTokens:10,reasoningOutputTokens:null});assert.equal(done.toolActivity.coverage.status,'complete');assert.equal(done.toolActivity.events.length,1);assert.equal(done.toolActivity.events[0].outcome,'success');assert.equal(done.toolActivity.aggregates.tools[0].count,1);assert(!JSON.stringify(done.toolActivity).includes('hidden-secret'));const restored=new CodexRuns(manager.directory).get(run.id);assert.equal(restored.output,done.output);assert.equal(restored.toolActivity.events.length,1);});
test('isolated worktree writes preserve source checkout and capture diff',async t=>{const {manager,project,repo}=fixture(t,`const fs=require('node:fs'),p=require('node:path');const args=process.argv;fs.writeFileSync(p.join(args[args.indexOf('--cd')+1],'file.txt'),'changed\\n');process.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({type:'turn.completed'})));`);const r=await manager.start({...input,mode:'worktree'},project);const done=await finished(manager,r.id);assert.equal(done.status,'completed',done.error);assert.match(done.diff,/changed/);assert.equal(readFileSync(path.join(repo,'file.txt'),'utf8'),'original\n');assert.match(done.branch,/^codex\/skd-/);writeFileSync(path.join(repo,'file.txt'),'dirty');await assert.rejects(manager.start({...input,mode:'worktree'},project),/clean Git/);});
test('cancellation kills the process and closes open tool activity without inferred success',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();console.log(JSON.stringify({type:'item.started',item:{id:'call-open',type:'web_search'}}));setInterval(()=>{},1000);`);const r=await manager.start(input,project);for(let i=0;i<250&&(manager.get(r.id).status==='preparing'||!manager.get(r.id).toolActivity.events.length);i++)await sleep(20);manager.stop(r.id);const stopped=await finished(manager,r.id);assert.equal(stopped.status,'cancelled');assert.equal(stopped.toolActivity.events[0].outcome,'cancelled');assert(stopped.toolActivity.events[0].finishedAt);await assert.rejects(async()=>manager.stop(r.id),/no longer active/);});
test('provider error and missing completion cannot count as success',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({type:'turn.failed',error:{message:'Not entitled'}})));`);const r=await manager.start(input,project);const done=await finished(manager,r.id);assert.equal(done.status,'failed');assert.match(done.error,/Not entitled/);assert.equal(done.usage,null);});
test('restart marks active records interrupted without relaunch',async t=>{const {manager}=fixture(t,'');manager.runs.push({id:'stale',status:'running'});manager.persist();const recovered=new CodexRuns(manager.directory);assert.equal(recovered.get('stale').status,'interrupted');assert.equal(recovered.active,null);assert.equal(usageFrom({input_tokens:-1}).inputTokens,null);});
test('runtime limit and malformed stream fail without invented usage or complete coverage',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();console.log('not-json');setInterval(()=>{},1000);`);manager.timeoutMs=2000;const r=await manager.start(input,project);const done=await finished(manager,r.id);assert.equal(done.status,'failed');assert.match(done.error,/Runtime limit/);assert.equal(done.usage,null);assert.equal(done.toolActivity.coverage.status,'partial');assert.match(done.toolActivity.coverage.reason,/malformed/);});
test('shutdown interrupts an active process without restarting it',async t=>{const {manager,project}=fixture(t,`process.stdin.resume();setInterval(()=>{},1000);`);const r=await manager.start(input,project);for(let i=0;i<50&&manager.get(r.id).status==='preparing';i++)await sleep(20);manager.shutdown();await sleep(100);assert.equal(manager.get(r.id).status,'interrupted');assert.equal(manager.active,null);});
test('supervisor stops Codex when its server parent is killed',async t=>{
 const {spawn}=await import('node:child_process');const {fileURLToPath}=await import('node:url');const {existsSync}=await import('node:fs');const {root}=fixture(t,'');const marker=path.join(root,'pid');const supervisor=fileURLToPath(new URL('../scripts/codex-child.mjs',import.meta.url));
 const childCode=`require('node:fs').writeFileSync(${JSON.stringify(marker)},String(process.pid));setInterval(()=>{},1000);`;
 const parentCode=`require('node:child_process').spawn(process.execPath,${JSON.stringify([supervisor,process.execPath,'-e',childCode])},{detached:true,stdio:'ignore'});setInterval(()=>{},1000);`;
 const parent=spawn(process.execPath,['-e',parentCode],{stdio:'ignore'});t.after(()=>parent.kill('SIGKILL'));
 for(let i=0;i<100&&!existsSync(marker);i++)await sleep(20);assert(existsSync(marker));const pid=Number(readFileSync(marker,'utf8'));parent.kill('SIGKILL');
 const alive=()=>{try{process.kill(pid,0);return true;}catch{return false;}};
 for(let i=0;i<150&&alive();i++)await sleep(20);assert.equal(alive(),false);
});
