import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync,mkdirSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import {createServer} from '../server.js';
const root=mkdtempSync(path.join(tmpdir(),'skd-codex-ui-'));const repo=path.join(root,'project');mkdirSync(repo);const binary=path.join(root,'fake-codex');writeFileSync(binary,`#!/usr/bin/env node
process.stdin.resume();process.stdin.on('end',()=>setTimeout(()=>{console.log(JSON.stringify({type:'item.started',item:{id:'fixture-call',type:'web_search'}}));console.log(JSON.stringify({type:'item.completed',item:{id:'fixture-call',type:'web_search',status:'completed'}}));console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Fixture response <script>not executable</script>'}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:120,cached_input_tokens:90,output_tokens:20}}));},500));`,{mode:0o755});
const server=createServer({directory:path.join(root,'data'),codexOptions:{binary,discover:async()=>({available:true,version:'fixture',auth:'Fixture',models:[{id:'fixture',name:'Fixture model',efforts:['low','high'],defaultEffort:'low',isDefault:true}]})}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'chrome'});
try{const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/#workflows/unassigned');await page.locator('#open-codex').click();assert.equal(await page.locator('#codex-start').isDisabled(),true);
 await page.locator('[data-add-project]').click();await page.getByLabel('Project name',{exact:true}).fill('Codex fixture');await page.getByLabel('Local folder',{exact:true}).fill(repo);await page.locator('#dialog').getByRole('button',{name:'Add project',exact:true}).click();await page.locator('main [data-view-link=codex]').click();await page.waitForFunction(()=>!document.querySelector('#codex-start').disabled);
 const projectID=await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project');const run=await (await fetch(url+'/api/codex/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectID,task:'Inspect fixture',model:'fixture',effort:'low',mode:'read-only'})})).json();await page.goto(url+'/#sessions/'+projectID+'/'+run.id);await page.reload();await page.getByRole('heading',{name:'Finished · review the result'}).waitFor();assert.match(await page.locator('.codex-output').first().textContent(),/Fixture response <script>/);assert.match(await page.locator('.metrics').textContent(),/140/);assert.match(await page.locator('.metrics').textContent(),/90/);assert.match(await page.getByText('Frozen configuration',{exact:true}).locator('..').textContent(),/No specialization/);assert.match(await page.locator('.tool-activity').textContent(),/complete.*codex-exec-jsonl/s);assert.match(await page.locator('.tool-activity').textContent(),/web_search · 1/);
 await page.reload();await page.getByRole('heading',{name:'Finished · review the result'}).waitFor();await page.getByRole('button',{name:'All sessions'}).click();await page.locator('[data-codex-run]').waitFor();assert.equal(await page.locator('[data-codex-run]').count(),1);
 await page.locator('[data-codex-run]').click();await page.getByRole('heading',{name:'Finished · review the result'}).waitFor();
 mkdirSync('output',{recursive:true});await page.locator('.tool-activity').evaluate(element=>element.open=true);await page.screenshot({path:'output/codex-fixture-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/codex-fixture-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Codex UI: frozen configuration, complete structured activity, output escaping, usage, reload/history and mobile checks passed (fixture provider).');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(root,{recursive:true,force:true});}
