import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from '../server.js';
const directory=mkdtempSync(path.join(tmpdir(),'flow-editor-'));
const server=createServer({directory});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1050}});
  page.setDefaultTimeout(6000);page.setDefaultNavigationTimeout(6000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  console.log('open',url);await page.goto(url+'/#workflows/unassigned');await page.locator('[data-flow]').first().click();await page.locator('[data-step]').first().waitFor();
  mkdirSync('output',{recursive:true});
  await page.screenshot({path:'output/editor-desktop.png',fullPage:true});
  console.log('duplicate');await page.getByRole('button',{name:'Duplicate',exact:true}).click();
  await page.getByLabel('New flow name').fill('Editor verification');
  await page.locator('#dialog').getByRole('button',{name:'Duplicate',exact:true}).click();
  await page.getByRole('heading',{name:'Editor verification'}).waitFor();console.log('configure');
  await page.locator('[data-step]').first().click();
  await page.getByLabel('Step name',{exact:true}).fill('Investigate the task');
  await page.getByLabel('Model',{exact:true}).fill('custom-model-v1');
  await page.getByLabel('Effort',{exact:true}).selectOption('low');
  await page.getByLabel('Instructions',{exact:true}).fill('Find the root cause and write acceptance checks.');
  await page.getByRole('button',{name:'Save flow',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save').disabled);
  console.log('reload');await page.reload();
  await page.getByRole('button',{name:'Editor verification',exact:true}).click();
  assert.match(await page.locator('[data-step]').first().textContent(),/Investigate the task/);
  console.log('add');await page.getByRole('button',{name:'+ Add a step',exact:true}).click();
  await page.locator('[data-type="check"]').click();
  await page.getByLabel('Step name',{exact:true}).fill('Run checks');
  await page.getByRole('button',{name:'Move step up',exact:true}).click();
  assert.match(await page.locator('[data-step]').nth(5).textContent(),/Run checks/);
  await page.getByRole('button',{name:'Remove step',exact:true}).click();
  await page.locator('#dialog').getByRole('button',{name:'Remove step',exact:true}).click();
  assert.equal(await page.locator('[data-step]').count(),6);
  await page.getByRole('button',{name:'Save flow',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save').disabled);
  await page.getByRole('button',{name:'Rename',exact:true}).click();
  await page.getByLabel('Flow name',{exact:true}).fill('Renamed flow');
  await page.locator('#dialog').getByRole('button',{name:'Rename',exact:true}).click();
  await page.getByRole('button',{name:'Save flow',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#save').disabled);
  await page.getByRole('button',{name:'Create new flow',exact:true}).click();
  await page.getByLabel('Flow name',{exact:true}).fill('Empty flow');
  await page.locator('#dialog').getByRole('button',{name:'Create flow',exact:true}).click();
  await page.getByRole('heading',{name:'Empty flow'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'▷ Try flow',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Plan, review, build',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'output/editor-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Editor browser checks passed: create, duplicate, rename, configure, save, reload, reorder, remove, empty run guard, mobile overflow.');
} finally {await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(directory,{recursive:true,force:true});}
