import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Skills} from '../lib/skills.js';
import {Connections} from '../lib/connections.js';
import {Playbooks} from '../lib/playbooks.js';
import {CodexRuns} from '../lib/codex.js';
import {terminalArgs} from '../lib/terminals.js';
import {claudeArgs} from '../lib/claude.js';

const wait=async(fn)=>{for(let i=0;i<100;i++){const value=fn();if(value)return value;await new Promise(resolve=>setTimeout(resolve,20));}throw new Error('timed out');};
function fixture(t){const root=mkdtempSync(path.join(tmpdir(),'skd-launch-context-')),home=path.join(root,'home'),projectFolder=path.join(root,'project'),directory=path.join(root,'data');mkdirSync(path.join(home,'.codex'),{recursive:true});mkdirSync(projectFolder);mkdirSync(directory);const project={id:'project',name:'Fixture',folderPath:projectFolder};t.after(()=>rmSync(root,{recursive:true,force:true}));return {root,home,projectFolder,directory,project};}

test('versioned skills reach structured and prompt-free interactive provider instruction channels',async t=>{
 const f=fixture(t),skills=new Skills(f.directory,{home:f.home}),entry=skills.create({revision:0,scope:{kind:'global'},name:'Exact skill',description:'',instructions:'EXACT SKILL BODY'},[f.project]);skills.savePolicy({revision:1,policyRevision:0,projectID:f.project.id,provider:'codex',mode:'inherit',skillIDs:[entry.id],excludedIDs:[]},[f.project]);
 const context=skills.resolve(f.project,'codex',{mode:'inherit',skillIDs:[]}),codexInteractive=terminalArgs({agent:'codex',model:'fixture',effort:'low',mode:'worktree',workingDirectory:f.projectFolder,agentContext:{skills:context,connections:{status:'native'}}}),claudeInteractive=terminalArgs({agent:'claude',model:'fixture',effort:'low',mode:'worktree',workingDirectory:f.projectFolder,agentContext:{skills:context,connections:{status:'native'}}});
 assert(codexInteractive.some(value=>value.includes('developer_instructions=')&&value.includes('EXACT SKILL BODY')));assert.equal(codexInteractive.at(-1),f.projectFolder);assert.deepEqual(claudeInteractive.slice(claudeInteractive.indexOf('--append-system-prompt'),claudeInteractive.indexOf('--append-system-prompt')+2),['--append-system-prompt',context.text]);assert.equal(claudeInteractive.at(-1),'dontAsk');
 const argvFile=path.join(f.root,'argv.json'),promptFile=path.join(f.root,'prompt.txt'),binary=path.join(f.root,'agent');writeFileSync(binary,`#!/usr/bin/env node\nconst fs=require('node:fs');fs.writeFileSync(${JSON.stringify(argvFile)},JSON.stringify(process.argv.slice(2)));let p='';process.stdin.on('data',c=>p+=c);process.stdin.on('end',()=>{fs.writeFileSync(${JSON.stringify(promptFile)},p);console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'done'}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:1,output_tokens:1}}));});`,{mode:0o755});
 const runs=new CodexRuns(f.directory,{binary,skills,discover:async()=>({version:'fixture',models:[{id:'fixture',efforts:['low']}]}),timeoutMs:2000});const started=await runs.start({task:'User task only',agent:'codex',model:'fixture',effort:'low',mode:'read-only'},f.project),done=await wait(()=>{const value=runs.get(started.id);return value.status==='completed'?value:null;});assert.equal(done.agentContext.skills.entries[0].version,1);assert.equal(done.agentContext.skills.entries[0].instructions,'EXACT SKILL BODY');assert(JSON.parse(readFileSync(argvFile,'utf8')).some(value=>value.includes('developer_instructions=')&&value.includes('EXACT SKILL BODY')));assert(!readFileSync(promptFile,'utf8').includes('EXACT SKILL BODY'));
 skills.update(entry.id,{revision:2,scope:{kind:'global'},name:'Exact skill',description:'',instructions:'NEW BODY'},[f.project]);assert.equal(runs.get(started.id).agentContext.skills.entries[0].instructions,'EXACT SKILL BODY');
 const excluded=await runs.start({task:'Proposal',agent:'codex',model:'fixture',effort:'low',mode:'read-only'},f.project,{issueProposal:true});await wait(()=>['completed','failed'].includes(runs.get(excluded.id).status));assert.equal(runs.get(excluded.id).agentContext.skills.status,'excluded');
});

test('managed MCP adapters isolate selected Codex names and use a private Claude config',async t=>{
 const f=fixture(t);writeFileSync(path.join(f.home,'.codex','config.toml'),'[mcp_servers.keep]\ncommand="node"\nargs=["keep.js"]\n[mcp_servers.drop]\ncommand="node"\nargs=["drop.js"]\n');writeFileSync(path.join(f.projectFolder,'.mcp.json'),JSON.stringify({mcpServers:{claude_keep:{command:'node',args:['claude.js']},claude_drop:{command:'node',args:['drop.js']}}}));const connections=new Connections(f.directory,{home:f.home,enumerateCodex:async()=>[{name:'keep',transport:'stdio'},{name:'drop',transport:'stdio'}]});
 let inventory=await connections.inventory([f.project],{kind:'project',projectID:f.project.id}),keep=inventory.connections.find(item=>item.provider==='codex'&&item.name==='keep');await connections.savePolicy({revision:0,policyRevision:0,projectID:f.project.id,provider:'codex',mode:'managed',connectionIDs:[keep.id]},[f.project]);let launch=await connections.prepareLaunch(f.project,'codex',{mode:'inherit',connectionIDs:[]},{mode:'worktree'});assert.equal(launch.snapshot.status,'managed');assert(launch.args.includes('mcp_servers.keep.enabled=true'));assert(launch.args.includes('mcp_servers.drop.enabled=false'));assert(!JSON.stringify(launch.snapshot).includes('keep.js'));
 writeFileSync(path.join(f.home,'.codex','config.toml'),'[mcp_servers.keep]\ncommand="node"\nargs=["changed.js"]\n[mcp_servers.drop]\ncommand="node"\nargs=["drop.js"]\n');await assert.rejects(connections.prepareLaunch(f.project,'codex',{mode:'inherit',connectionIDs:[]},{mode:'worktree'}),/changed after it was assigned/);
 inventory=await connections.inventory([f.project],{kind:'project',projectID:f.project.id});const claude=inventory.connections.find(item=>item.provider==='claude'&&item.name==='claude_keep');connections.data.checks.push({id:'check',projectID:f.project.id,connectionID:claude.id,provider:'claude',name:claude.name,fingerprint:claude.fingerprint,status:'available',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),tools:['fixture_tool'],error:null});connections.persist();await connections.savePolicy({revision:1,policyRevision:0,projectID:f.project.id,provider:'claude',mode:'managed',connectionIDs:[claude.id]},[f.project]);launch=await connections.prepareLaunch(f.project,'claude',{mode:'inherit',connectionIDs:[]},{mode:'worktree'});assert.equal(launch.snapshot.connections.length,1);assert.deepEqual(launch.tools,['mcp__claude_keep__fixture_tool']);const configPath=launch.args.at(-1);assert.equal(JSON.parse(readFileSync(configPath,'utf8')).mcpServers.claude_keep.args[0],'claude.js');assert(!readFileSync(configPath,'utf8').includes('claude_drop'));const args=terminalArgs({agent:'claude',model:'fixture',effort:'low',mode:'worktree',workingDirectory:f.projectFolder,agentContext:{skills:{text:''},connections:launch.snapshot}},launch.args,launch.tools);assert(!args.includes('--safe-mode'));assert(args.includes('--strict-mcp-config'));assert(args[args.indexOf('--tools')+1].includes('mcp__claude_keep__fixture_tool'));connections.cleanupLaunch(configPath);assert.equal(existsSync(configPath),false);
 const structured=claudeArgs({purpose:'workflow',mode:'worktree',model:'fixture',effort:'low',agentContext:{skills:{text:''},connections:{status:'excluded'}}});assert(structured.includes('--safe-mode'));assert.equal(structured[structured.indexOf('--mcp-config')+1],'{"mcpServers":{}}');
});

test('playbook preview and actual structured launch agree while later edits preserve the frozen run',async t=>{
 const f=fixture(t),skills=new Skills(f.directory,{home:f.home}),connections=new Connections(f.directory,{home:f.home,enumerateCodex:async()=>[]}),playbooks=new Playbooks(f.directory,{skills,connections}),entry=skills.create({revision:0,scope:{kind:'global'},name:'Playbook skill',description:'',instructions:'PLAYBOOK BODY'},[f.project]),playbook=await playbooks.create({revision:0,name:'Launch preset',scope:{kind:'project',projectID:f.project.id},providers:['codex'],skillIDs:[entry.id],connectionIDs:[]},[f.project]),preview=await playbooks.preview(f.project,'codex',{mode:'selected',playbookID:playbook.id},{mode:'read-only'});
 const binary=path.join(f.root,'playbook-agent');writeFileSync(binary,'#!/usr/bin/env node\nlet p="";process.stdin.on("data",c=>p+=c);process.stdin.on("end",()=>{console.log(JSON.stringify({type:"item.completed",item:{type:"agent_message",text:"done"}}));console.log(JSON.stringify({type:"turn.completed",usage:{input_tokens:1,output_tokens:1}}));});',{mode:0o755});
 const runs=new CodexRuns(f.directory,{binary,skills,connections,playbooks,discover:async()=>({version:'fixture',models:[{id:'fixture',efforts:['low']}]}),timeoutMs:2000}),started=await runs.start({task:'Run preset',agent:'codex',model:'fixture',effort:'low',mode:'read-only',playbook:{mode:'selected',playbookID:playbook.id,version:playbook.version,expectedSignature:preview.signature}},f.project),done=await wait(()=>{const value=runs.get(started.id);return value.status==='completed'?value:null;});
 assert.equal(done.agentContext.agentProfile.id,playbook.id);assert.equal(done.agentContext.agentProfile.signature,preview.signature);assert.equal(done.agentContext.skills.entries[0].instructions,'PLAYBOOK BODY');
 await playbooks.update(playbook.id,{revision:1,version:1,name:'Launch preset changed',description:'',scope:{kind:'project',projectID:f.project.id},providers:['codex'],skillIDs:[],connectionIDs:[]},[f.project]);assert.equal(runs.get(done.id).agentContext.agentProfile.version,1);assert.equal(runs.get(done.id).agentContext.skills.entries[0].instructions,'PLAYBOOK BODY');
 await assert.rejects(runs.start({task:'Stale preview',agent:'codex',model:'fixture',effort:'low',mode:'read-only',playbook:{mode:'selected',playbookID:playbook.id,version:1,expectedSignature:preview.signature}},f.project),/changed after preview/);
});
