import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {ReconciliationService} from '../lib/lifecycle-reconciliation.js';
import {LifecycleStore} from '../lib/lifecycle-store.js';
import {EvidenceStore} from '../lib/lifecycle-evidence.js';
import {WorktreeNotes} from '../lib/worktree-notes.js';
import {inspectFolder} from '../lib/projects.js';
import {inspectRepository} from '../lib/worktrees.js';
const run=(folder,...args)=>execFileSync('git',['-C',folder,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
async function fixture(t,{exclude=false,remote=false}={}){const root=mkdtempSync(path.join(tmpdir(),'reconciliation-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const repo=path.join(root,'main');mkdirSync(repo);run(repo,'init','-b','main');run(repo,'config','user.name','Fixture');run(repo,'config','user.email','fixture@example.invalid');writeFileSync(path.join(repo,'base.txt'),'base');run(repo,'add','.');run(repo,'commit','-m','base');const context=await inspectFolder(repo),base=context.git.commit,directory=path.join(root,'data'),notes=new WorktreeNotes(directory),store=new LifecycleStore(directory),evidence=new EvidenceStore(directory),project={id:'project1',version:1,folderPath:context.folderPath},executor={owner:null},sessions=[];let finishCallback;const terminals={executor,active:null,runs:sessions,get(id){const s=sessions.find(s=>s.id===id);assert.ok(s);return {...s};},async start(input,p,internal){assert.equal(executor.owner,null);executor.owner='terminal:fixture';this.active={id:'session1'};try{await internal.shouldLaunch();const s={id:'session'+(sessions.length+1),status:'running',projectID:p.id,quickAction:input.quickAction,input};sessions.push(s);finishCallback=input.onFinished;return {...s};}catch(e){executor.owner=null;this.active=null;throw e;}},async finish(status='completed'){const s=sessions.at(-1);s.status=status;await finishCallback(s);executor.owner=null;this.active=null;}};
 async function add(name,{parent=base,ready=true}={}){const destination=path.join(path.dirname(context.folderPath),name);run(repo,'worktree','add','-b','codex/'+name,destination,parent);writeFileSync(path.join(destination,name+'.txt'),name);run(destination,'add','.');run(destination,'commit','-m',name);const note=notes.prepare({intentID:name,projectID:project.id,sourceContext:context,destination,branch:'codex/'+name,purpose:name,origin:{kind:'task',id:name},ownerKey:'task:'+name});await notes.attach(name);const row=store.ensure(notes.get(note.id));const record=store.update(row.id,{expectedRevision:row.revision,criteria:[{id:'tests',label:'Tests pass',required:true}],nextAction:ready?'Integrate approved work':'Finish this experiment'});const tip=run(destination,'rev-parse','HEAD');if(ready)check(record.id,tip);return {id:record.id,path:destination,tip,branch:'codex/'+name};}
 function check(id,commit,environment='fixture'){const record=store.get(id),report=evidence.record({repositoryKey:record.repositoryKey,lifecycleID:id,commit,criteriaRevision:record.criteriaRevision,criterionID:'tests',environment,outcome:'passed',summary:'Fixture check passed',exitCode:0},{source:'fixture',observed:true});evidence.review(report.id,{expectedRevision:1,decision:'accepted',reason:'Reviewed fixture result',reviewer:'user'});return report;}
 const selected=await add('selected');let excluded=null;if(exclude){excluded=await add('excluded',{ready:false});writeFileSync(path.join(excluded.path,'excluded.txt'),'unfinished dirty bytes');}
 const lifecycle={async read(){const s=await inspectRepository(repo,{targetRef:'refs/heads/main'}),observations={};for(const r of store.list(store.get(selected.id).repositoryKey)){const n=notes.get(r.id),row=s.worktrees.find(w=>w.path===n.destination);let contained=false;try{run(repo,'merge-base','--is-ancestor',row.commit,s.target.commit);contained=true;}catch{}observations[r.id]={complete:!s.partial&&!s.stale,attached:true,exists:true,commit:row.commit,targetCommit:s.target.commit,dirty:row.dirty,active:Boolean(executor.owner),operations:row.operations,locked:row.locked,detached:row.detached,isTarget:false,benchmark:false,contained,assetsClear:true,connectedRoot:false,submodules:false,dependenciesResolved:true,path:row.path,branch:row.branch};}return {repositoryKey:store.get(selected.id).repositoryKey,complete:!s.partial&&!s.stale,observations,unknown:[]};}};
 let bare=null;if(remote){bare=path.join(root,'remote.git');execFileSync('git',['clone','--bare',repo,bare],{stdio:'ignore'});run(repo,'remote','add','origin','https://fixture.invalid/repository.git');}
 const advertise=async()=>({tips:{'refs/heads/main':run(bare,'rev-parse','refs/heads/main')}});const options={lifecycle,store,evidence,notes,terminals,project:()=>project,advertise};const service=new ReconciliationService(directory,options);const preview=(ids=[selected.id],scope='selected',synchronize=false)=>service.preview(project,{selected:ids,scope,synchronize});const start=p=>service.start(project,{previewID:p.id,requestKey:'request-'+p.id,agent:'codex',model:'fixture',effort:'low',confirmOwnership:true});return {root,repo,base,directory,project,notes,store,evidence,terminals,sessions,service,options,selected,excluded,add,check,preview,start,bare};}
test('selected reconciliation preserves dirty exclusion, needs final evidence, and never certifies process exit',async t=>{const f=await fixture(t,{exclude:true}),preview=await f.preview(),operation=await f.start(preview);assert.equal(operation.status,'running');assert.deepEqual(f.sessions[0].input.reconciliation.writeDirectories,[f.notes.get(f.selected.id).sourceContext.git.commonDirectory,f.project.folderPath]);run(f.repo,'merge','--no-ff',f.selected.branch,'-m','selected merge');await f.terminals.finish();let current=f.service.get(f.project,operation.id);assert.equal(current.status,'stopped');assert.equal(f.evidence.receipts(f.store.get(f.selected.id).repositoryKey).length,0);const unverified=await f.service.verify(f.project,operation.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(unverified.receipt.status,'unverified',JSON.stringify({errors:unverified.receipt.errors,observation:current.observation,operationError:current.error}));assert.equal(unverified.receipt.attempts[0].status,'integrated');f.check(f.selected.id,run(f.repo,'rev-parse','main'));current=f.service.get(f.project,operation.id);const verified=await f.service.verify(f.project,operation.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(verified.receipt.status,'verified',JSON.stringify({errors:verified.receipt.errors,synchronization:verified.receipt.synchronization}));assert.equal(verified.receipt.synchronization.status,'not-requested');assert.match(verified.receipt.summary,/1 unfinished items remain/);assert.equal(verified.receipt.exclusions[0].lifecycleID,f.excluded.id);assert.equal(readFileSync(path.join(f.excluded.path,'excluded.txt'),'utf8'),'unfinished dirty bytes');assert.equal(f.evidence.receipts(f.store.get(f.selected.id).repositoryKey).length,2);});
test('stale same-count dirty exclusion changes reject launch and full scope cannot park unfinished work',async t=>{const f=await fixture(t,{exclude:true});await assert.rejects(f.preview([f.selected.id],'full'),/Full reconciliation/);const p=await f.preview();writeFileSync(path.join(f.excluded.path,'excluded.txt'),'different dirty bytes');await assert.rejects(f.start(p),/changed/);assert.equal(f.sessions.length,0);});
test('selected descendant cannot indirectly integrate excluded unfinished ancestor',async t=>{const f=await fixture(t),ancestor=await f.add('ancestor',{ready:false}),descendant=await f.add('descendant',{parent:ancestor.tip});await assert.rejects(f.preview([descendant.id]),/indirectly includes excluded/);assert.equal(f.sessions.length,0);});
test('lost start response, concurrent attempt and restart never launch a replacement session',async t=>{const f=await fixture(t),p=await f.preview();const input={previewID:p.id,requestKey:'one-request',agent:'codex',model:'fixture',effort:'low',confirmOwnership:true};const settled=await Promise.allSettled([f.service.start(f.project,input),f.service.start(f.project,input)]);assert.equal(settled.filter(r=>r.status==='fulfilled').length,1);const operation=settled.find(r=>r.status==='fulfilled').value;assert.equal((await f.service.start(f.project,input)).id,operation.id);assert.equal(f.sessions.length,1);const restarted=new ReconciliationService(f.directory,f.options);assert.equal(restarted.get(f.project,operation.id).status,'interrupted');assert.equal((await restarted.start(f.project,input)).id,operation.id);assert.equal(f.sessions.length,1);});
test('postlaunch excluded drift prevents certification even after selected merge and accepted evidence',async t=>{const f=await fixture(t,{exclude:true}),p=await f.preview(),op=await f.start(p);run(f.repo,'merge','--no-ff',f.selected.branch,'-m','selected merge');writeFileSync(path.join(f.excluded.path,'excluded.txt'),'unexpected external change');await f.terminals.finish();f.check(f.selected.id,run(f.repo,'rev-parse','main'));const current=f.service.get(f.project,op.id),result=await f.service.verify(f.project,op.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(result.receipt.status,'failed');assert.match(result.receipt.errors[0],/workspace changed/);});
test('local verification and remote synchronization remain independent with injected bare-remote observation',async t=>{const f=await fixture(t,{remote:true}),p=await f.preview([f.selected.id],'selected',true),op=await f.start(p);run(f.repo,'merge','--no-ff',f.selected.branch,'-m','selected merge');await f.terminals.finish();const commit=run(f.repo,'rev-parse','main');f.check(f.selected.id,commit);let current=f.service.get(f.project,op.id);const pending=await f.service.verify(f.project,op.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(pending.receipt.status,'verified');assert.equal(pending.receipt.synchronization.status,'pending');run(f.repo,'push',f.bare,'main');current=f.service.get(f.project,op.id);const synchronized=await f.service.verify(f.project,op.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(synchronized.receipt.status,'verified');assert.equal(synchronized.receipt.synchronization.status,'observed');assert.equal(synchronized.receipt.synchronization.commit,commit);});
test('interrupted second merge preserves first integration and reports per-tip partial state',async t=>{const f=await fixture(t),second=await f.add('second'),p=await f.preview([f.selected.id,second.id]),op=await f.start(p);run(f.repo,'merge','--no-ff',f.selected.branch,'-m','first selected merge');const partial=run(f.repo,'rev-parse','HEAD');writeFileSync(path.join(f.repo,'unfinished.txt'),'interrupted attempt');await f.terminals.finish('interrupted');const current=f.service.get(f.project,op.id),result=await f.service.verify(f.project,op.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(result.receipt.status,'interrupted');assert.equal(result.receipt.targetCommit,partial);assert.equal(result.receipt.attempts.find(a=>a.lifecycleID===f.selected.id).status,'integrated');assert.equal(result.receipt.attempts.find(a=>a.lifecycleID===second.id).status,'not-integrated');assert.match(result.receipt.errors.join(' '),/uncommitted changes/);assert.equal(run(f.repo,'rev-parse','HEAD'),partial);assert.equal(readFileSync(path.join(f.repo,'unfinished.txt'),'utf8'),'interrupted attempt');});
test('unknown branch-only work and changed selected criteria block launch without provider execution',async t=>{const f=await fixture(t);run(f.repo,'branch','untracked-branch',f.selected.tip);await assert.rejects(f.preview(),/branch-only/);run(f.repo,'branch','-D','untracked-branch');const p=await f.preview(),r=f.store.get(f.selected.id);f.store.update(r.id,{expectedRevision:r.revision,blocker:'Review new failure'});await assert.rejects(f.start(p),/Review new failure|changed/);assert.equal(f.sessions.length,0);});
test('malformed persisted reconciliation manifest fails closed before any launch',t=>{const root=mkdtempSync(path.join(tmpdir(),'reconciliation-corrupt-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const file=path.join(root,'lifecycle-reconciliation.json'),raw=JSON.stringify({version:1,operations:[{id:'operation',projectID:'project1',requestKey:'request',revision:1,status:'preparing',receiptIDs:[],manifest:{repositoryKey:'a'.repeat(64),selected:[],exclusions:[]}}]});writeFileSync(file,raw);assert.throws(()=>new ReconciliationService(root,{terminals:{runs:[]}}),/damaged/);assert.equal(readFileSync(file,'utf8'),raw);});

test('verification refuses a main rewrite that contains selected work but drops captured main history',async t=>{const f=await fixture(t);writeFileSync(path.join(f.repo,'main-only.txt'),'preserve original main work');run(f.repo,'add','.');run(f.repo,'commit','-m','main-only history');const originalMain=run(f.repo,'rev-parse','main'),preview=await f.preview(),operation=await f.start(preview);assert.equal(preview.target.commit,originalMain);run(f.repo,'reset','--hard',f.selected.tip);await f.terminals.finish();f.check(f.selected.id,f.selected.tip);const current=f.service.get(f.project,operation.id),result=await f.service.verify(f.project,operation.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(result.receipt.status,'failed',JSON.stringify(result.receipt.errors));assert.match(result.receipt.errors.join(' '),/captured original main history/);assert.equal(result.receipt.targetBefore,originalMain);assert.equal(run(f.repo,'rev-parse','main'),f.selected.tip);});

test('verification refuses newly integrated excluded tips even when excluded files and refs are unchanged',async t=>{const f=await fixture(t,{exclude:true}),preview=await f.preview(),operation=await f.start(preview);const excludedBefore=readFileSync(path.join(f.excluded.path,'excluded.txt'),'utf8');run(f.repo,'merge','--no-ff',f.selected.branch,'-m','selected merge');run(f.repo,'merge','--no-ff',f.excluded.branch,'-m','unauthorized excluded merge');const final=run(f.repo,'rev-parse','main');assert.equal(run(f.excluded.path,'rev-parse','HEAD'),f.excluded.tip);assert.equal(readFileSync(path.join(f.excluded.path,'excluded.txt'),'utf8'),excludedBefore);await f.terminals.finish();f.check(f.selected.id,final);const current=f.service.get(f.project,operation.id),result=await f.service.verify(f.project,operation.id,{expectedRevision:current.revision,environment:'fixture'});assert.equal(result.receipt.status,'failed',JSON.stringify(result.receipt.errors));assert.match(result.receipt.errors.join(' '),/Excluded unfinished work was newly integrated/);assert.equal(run(f.repo,'rev-parse','main'),final);assert.equal(readFileSync(path.join(f.excluded.path,'excluded.txt'),'utf8'),excludedBefore);});

test('native reconciliation prompt redacts another project owner source reference',()=>{
 const service=Object.create(ReconciliationService.prototype);service.store={get:()=>({projectID:'sibling'})};
 const prompt=service.prompt({projectID:'original',scope:'selected',target:{path:'/fixture/main',commit:'a'.repeat(40)},synchronize:false,remoteName:null,selected:[],excluded:[],exclusions:[{lifecycleID:'fixture',ownerRef:'PRIVATE_SESSION_OWNER',reason:'working',nextAction:'Review later'}]});
 assert(!prompt.includes('PRIVATE_SESSION_OWNER'));assert(prompt.includes('other-project'));
});
