import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,existsSync,realpathSync,mkdirSync} from 'node:fs';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {inspectFolder} from '../lib/projects.js';
import {WorktreeNotes} from '../lib/worktree-notes.js';
import {LifecycleStore} from '../lib/lifecycle-store.js';
import {EvidenceStore} from '../lib/lifecycle-evidence.js';
import {RetirementService} from '../lib/lifecycle-retirement.js';
const git=(folder,args)=>execFileSync('git',['-C',folder,...args],{encoding:'utf8'}).trim();
async function fixture(t,{remove}={}){
 const directory=realpathSync(mkdtempSync(path.join(tmpdir(),'skd-retirement-'))),repo=path.join(directory,'repo'),data=path.join(directory,'data');t.after(()=>rmSync(directory,{recursive:true,force:true}));git(directory,['init','-b','main',repo]);writeFileSync(path.join(repo,'file.txt'),'source\n');writeFileSync(path.join(repo,'.gitignore'),'ignored/\n');git(repo,['add','.']);git(repo,['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','fixture']);
 const project={id:'project',version:1,folderPath:repo},projects=[project],sourceContext=await inspectFolder(repo),notes=new WorktreeNotes(data),store=new LifecycleStore(data),evidence=new EvidenceStore(data),executor={owner:null,active:null,starting:false,cleaning:0};let override={};
 const lifecycle={evidence,async read(){const records=store.list(repositoryKey).map(r=>{const n=notes.get(r.id),exists=existsSync(n.destination);return {...r,observation:{complete:true,attached:true,exists,commit:exists?git(n.destination,['rev-parse','HEAD']):null,targetCommit:git(repo,['rev-parse','main']),dirty:false,active:Boolean(executor.owner),operations:[],locked:false,detached:false,isTarget:false,benchmark:false,contained:true,assetsClear:true,submodules:false,connectedRoot:false,dependenciesResolved:true,path:n.destination,branch:exists?git(n.destination,['symbolic-ref','--short','HEAD']):n.branch,...override}};});return {repositoryKey,complete:true,records,reports:evidence.list(repositoryKey),receipts:evidence.receipts(repositoryKey)};}};
 let repositoryKey;async function add(){const intentID=randomUUID(),destination=path.join(directory,intentID),branch='codex/retire-'+intentID;const prepared=notes.prepare({intentID,projectID:project.id,sourceContext,destination,branch,purpose:'Fixture task',origin:{kind:'session',id:intentID},ownerKey:'session:'+intentID,classification:'development'});git(repo,['worktree','add','-b',branch,destination]);const registration=await notes.attach(intentID);let record=store.ensure(registration);repositoryKey=record.repositoryKey;record=store.update(record.id,{expectedRevision:record.revision,criteria:[{id:'tests',label:'Tests',required:true}]});const commit=git(destination,['rev-parse','HEAD']);let report=evidence.record({repositoryKey,lifecycleID:record.id,commit,criteriaRevision:record.criteriaRevision,criterionID:'tests',environment:'Git fixture',outcome:'passed',summary:'Fixture verified',exitCode:0},{source:'fixture',observed:true});report=evidence.review(report.id,{expectedRevision:report.revision,decision:'accepted',reason:'Verified fixture checks',reviewer:'user'});const receipt=evidence.receipt({repositoryKey,targetCommit:commit,criteriaRevision:record.criteriaRevision,selected:[{lifecycleID:record.id,commit}],exclusions:[],evidenceIDs:[report.id],environment:'Git fixture',status:'verified',summary:'Fixture integration verified'});return {record,registration,report,receipt,destination,branch};}
 const selected=await add(),options={lifecycle,store,notes,executor,project:()=>project,projects:()=>projects,...(remove?{remove}:{})},service=new RetirementService(data,options);
 return {directory,data,repo,project,projects,notes,store,evidence,executor,service,options,selected,add,setObservation:value=>{override=value;}};
}
const preview=f=>f.service.preview(f.project,{selected:[f.selected.record.id]});
const remove=(f,p,key='retire-request')=>f.service.remove(f.project,{previewID:p.id,requestKey:key,confirm:true});
test('explicit retirement removes only selected path and Git membership, preserving branch, evidence and lifecycle receipt',async t=>{const f=await fixture(t),p=await preview(f);assert.equal(p.eligible,true,JSON.stringify(p.records));assert(existsSync(f.selected.destination));assert.equal(f.store.get(f.selected.record.id).events.some(e=>e.type==='retired'),false);const result=await remove(f,p);assert.equal(result.status,'complete',JSON.stringify(result));assert.equal(result.items[0].status,'retired');assert(!existsSync(f.selected.destination));assert(!git(f.repo,['worktree','list','--porcelain']).includes(f.selected.destination));assert(git(f.repo,['show-ref','--verify','refs/heads/'+f.selected.branch]));assert.equal(readFileSync(path.join(f.repo,'file.txt'),'utf8'),'source\n');assert.equal(f.notes.get(f.selected.record.id).id,f.selected.record.id);assert.equal(f.evidence.get(f.selected.report.id).id,f.selected.report.id);const event=f.store.get(f.selected.record.id).events.find(e=>e.type==='retired');assert.equal(event.detail.receiptID,f.selected.receipt.id);assert.deepEqual(await remove(f,p),result);assert.equal(f.executor.owner,null);});
for(const [key,value]of [['complete',false],['attached',false],['exists',false],['dirty',true],['active',true],['operations',['merge']],['locked',true],['detached',true],['isTarget',true],['benchmark',true],['contained',false],['assetsClear',false],['submodules',true],['connectedRoot',true]])test(`retirement preview refuses ${key}`,async t=>{const f=await fixture(t);f.setObservation({[key]:value});const p=await preview(f);assert.equal(p.eligible,false);await assert.rejects(remove(f,p),/blockers/);assert(existsSync(f.selected.destination));});
test('independent file inspection refuses tracked, untracked and ignored files despite optimistic observation',async t=>{const f=await fixture(t);for(const filename of ['file.txt','untracked.txt','ignored/data']){if(filename.includes('/'))mkdirSync(path.dirname(path.join(f.selected.destination,filename)),{recursive:true});writeFileSync(path.join(f.selected.destination,filename),'keep');assert.equal((await preview(f)).eligible,false,filename);if(filename==='file.txt')git(f.selected.destination,['restore','file.txt']);else rmSync(path.join(f.selected.destination,filename));}assert(existsSync(f.selected.destination));});
test('fresh preflight refuses drift after preview and records failure without removing',async t=>{const f=await fixture(t),p=await preview(f);writeFileSync(path.join(f.selected.destination,'file.txt'),'changed');const result=await remove(f,p);assert.equal(result.status,'partial');assert.equal(result.items[0].status,'failed');assert(existsSync(f.selected.destination));assert(!f.store.get(f.selected.record.id).events.some(e=>e.type==='retired'));});
test('changed evidence, connected project ownership, lock and target main prevent removal',async t=>{const f=await fixture(t);const p=await preview(f);f.evidence.review(f.selected.report.id,{expectedRevision:f.selected.report.revision,decision:'rejected',reason:'Needs rerun',reviewer:'user'});assert.equal((await remove(f,p)).items[0].status,'failed');f.projects.push({id:'other',folderPath:f.selected.destination});assert.equal((await preview(f)).eligible,false);assert(existsSync(f.selected.destination));});
test('actual worktree lock and Git operation files block even optimistic lifecycle facts',async t=>{const f=await fixture(t);git(f.repo,['worktree','lock',f.selected.destination]);assert.equal((await preview(f)).eligible,false);git(f.repo,['worktree','unlock',f.selected.destination]);const admin=git(f.selected.destination,['rev-parse','--absolute-git-dir']);writeFileSync(path.join(admin,'MERGE_HEAD'),git(f.repo,['rev-parse','HEAD']));assert.equal((await preview(f)).eligible,false);});
test('partial removal retains first success and never touches later items after uncertainty',async t=>{let calls=0;const f=await fixture(t,{remove:({commonDirectory,path:destination})=>{calls++;if(calls===2)throw Error('Injected refusal');git(commonDirectory,['worktree','remove','--',destination]);}}),second=await f.add(),third=await f.add();const p=await f.service.preview(f.project,{selected:[f.selected.record.id,second.record.id,third.record.id]});assert.equal(p.eligible,true);const result=await remove(f,p);assert.equal(result.status,'partial');assert.deepEqual(result.items.map(i=>i.status),['retired','uncertain','not-attempted']);assert(!existsSync(f.selected.destination));assert(existsSync(second.destination));assert(existsSync(third.destination));assert.equal(calls,2);});
test('lost remove response stays uncertain; read-only inspect and restart never replay or label external disappearance retired',async t=>{let calls=0;const f=await fixture(t,{remove:({commonDirectory,path:destination})=>{calls++;git(commonDirectory,['worktree','remove','--',destination]);throw Error('Lost response');}}),p=await preview(f),result=await remove(f,p);assert.equal(result.items[0].status,'uncertain');assert(!f.store.get(f.selected.record.id).events.some(e=>e.type==='retired'));const before=readFileSync(f.service.file,'utf8'),inspected=await f.service.inspect(f.project,result.id);assert.equal(inspected.items[0].actual.pathExists,false);assert.equal(inspected.items[0].actual.registered,false);assert.equal(inspected.items[0].retired,false);assert.equal(readFileSync(f.service.file,'utf8'),before);const restored=new RetirementService(f.data,f.options);assert.equal((await restored.remove(f.project,{previewID:p.id,requestKey:'retire-request',confirm:true})).id,result.id);assert.equal(calls,1);});
test('restart marks in-flight intent interrupted and does no filesystem replay',async t=>{const f=await fixture(t),p=await preview(f);f.service.removeAdapter=()=>{throw Error('Retained');};const op=await remove(f,p);const data=JSON.parse(readFileSync(f.service.file,'utf8'));data.operations[0].status='running';data.operations[0].items[0].status='removing';writeFileSync(f.service.file,JSON.stringify(data));let calls=0;const recovered=new RetirementService(f.data,{...f.options,remove:()=>{calls++;}});assert.equal(recovered.get(f.project,op.id).status,'interrupted');assert.equal(recovered.get(f.project,op.id).items[0].status,'uncertain');assert.equal(calls,0);assert(existsSync(f.selected.destination));});
test('scope, project changes, global writer and corrupted intent history fail closed',async t=>{const f=await fixture(t),p=await preview(f);await assert.rejects(f.service.remove(f.project,{previewID:p.id,requestKey:'x',confirm:true,path:'/tmp/other'}),/Invalid/);f.executor.owner='another-agent';await assert.rejects(remove(f,p),/active/);f.executor.owner=null;const previous={...f.project};f.project.version++;await assert.rejects(f.service.remove(previous,{previewID:p.id,requestKey:'x',confirm:true}),/Project changed/);assert(existsSync(f.selected.destination));writeFileSync(f.service.file,'{}');assert.throws(()=>new RetirementService(f.data,f.options),/damaged/);});
