import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {EvidenceStore} from '../lib/lifecycle-evidence.js';
import {acceptedChecks,deriveLifecycle,batchEligibility} from '../lib/lifecycle-policy.js';
const repositoryKey='a'.repeat(64),commit='b'.repeat(40),targetCommit='c'.repeat(40);
function fixture(t){const directory=mkdtempSync(path.join(tmpdir(),'skd-policy-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));const store=new EvidenceStore(directory);const record={id:randomUUID(),repositoryKey,criteriaRevision:2,criteria:[{id:'tests',label:'Required tests',required:true}],ownerRef:'task:owner',attachmentState:'attached',blocker:'',nextAction:'Review changes',dependencies:[],events:[]};const observation={complete:true,attached:true,exists:true,commit,targetCommit,dirty:false,active:false,operations:[],locked:false,detached:false,isTarget:false,benchmark:false,contained:false,assetsClear:true,submodules:false,connectedRoot:false,dependenciesResolved:true};
 const check=(changes={},owner=record)=>{let r=store.record({repositoryKey:owner.repositoryKey,lifecycleID:owner.id,commit,criteriaRevision:owner.criteriaRevision,criterionID:'tests',environment:'Fixture Node',outcome:'passed',summary:'Assertion passed',exitCode:0,...changes},{source:'agent',observed:false});r=store.review(r.id,{expectedRevision:1,decision:'accepted',reason:'Read submitted evidence',reviewer:'user'});return r;};
 const receipt=(combined,changes={})=>store.receipt({repositoryKey,targetCommit,criteriaRevision:record.criteriaRevision,selected:[{lifecycleID:record.id,commit,criteriaRevision:record.criteriaRevision}],exclusions:[],evidenceIDs:[combined.id],environment:'Fixture Node',status:'verified',summary:'Observed contained tips and accepted combined checks',...changes});
 return {store,record,observation,check,receipt,state:(o=observation)=>deriveLifecycle(record,o,store.list(repositoryKey),store.receipts(repositoryKey))};
}
test('current accepted claims permit readiness without relabeling them independently observed',t=>{const f=fixture(t);const report=f.check();assert.equal(f.state().ready,true);assert.equal(f.state().verified,false);assert.equal(report.source,'agent');assert.equal(report.observed,false);assert.deepEqual(f.state().checks.evidenceIDs,[report.id]);});
for(const [field,value] of [['complete',false],['attached',false],['exists',false],['commit',null],['targetCommit',null],['dirty',true],['active',true],['operations',['merge']],['locked',true],['detached',true],['isTarget',true],['benchmark',true],['dependenciesResolved',false],['dirty',null],['active',null],['locked',undefined],['detached',undefined],['operations',null]])test(`readiness refuses ${field}=${JSON.stringify(value)}`,t=>{const f=fixture(t);f.check();const state=f.state({...f.observation,[field]:value});assert.equal(state.ready,false);assert.equal(state.verified,false);assert.equal(state.retirementEligible,false);assert(state.reasons.length);});
test('no required criteria, no owner, explicit blocker, imported attachment and stale criteria refuse readiness',t=>{const f=fixture(t);f.check();for(const edit of [{criteria:[]},{criteria:[{id:'tests',label:'Optional',required:false}]},{ownerRef:null},{blocker:'Repair first'},{attachmentState:'unattached'},{criteriaRevision:3}])assert.equal(deriveLifecycle({...f.record,...edit},f.observation,f.store.list(repositoryKey)).ready,false);});
test('failure, unknown, no run, nonzero exit, dirty check, missing review and rejected review are not accepted',t=>{const f=fixture(t);for(const change of [{outcome:'failed'},{outcome:'unknown'},{outcome:'not-run'},{exitCode:1},{dirtyFingerprint:'dirty'}]){const report=f.check(change);assert.equal(acceptedChecks(f.record,[report],commit).accepted,false);}let r=f.check();r={...r,reviews:[]};assert.equal(acceptedChecks(f.record,[r],commit).accepted,false);r=f.check();f.store.review(r.id,{expectedRevision:r.revision,decision:'rejected',reason:'Insufficient proof',reviewer:'user'});assert.equal(f.state().ready,false);});
test('latest report per criterion wins by time, not caller array ordering',t=>{const f=fixture(t);const good={...f.check(),createdAt:'2026-01-01T00:00:00Z'},bad={...f.check({outcome:'failed'}),createdAt:'2026-01-02T00:00:00Z'};assert.equal(acceptedChecks(f.record,[bad,good],commit).accepted,false);assert.equal(acceptedChecks(f.record,[good,bad],commit).accepted,false);assert.equal(acceptedChecks(f.record,[good,{...bad,commit:targetCommit}],commit).accepted,true);});
test('N/A requires explicit user reason and current criterion binding; required missing artifacts block passing claims',t=>{const f=fixture(t);let r=f.check({outcome:'not-run',artifacts:[{id:'log',label:'Log',required:true}]});assert.equal(f.state().ready,false);r=f.store.review(r.id,{expectedRevision:r.revision,decision:'not-applicable',reason:'No native target in this scoped change',reviewer:'user'});assert.equal(f.state().ready,true);assert.equal(acceptedChecks(f.record,[{...r,reviews:[{decision:'not-applicable',reason:'',reviewer:'user'}]}],commit).accepted,false);assert.equal(acceptedChecks({...f.record,criteriaRevision:3},[r],commit).accepted,false);});
test('foreign repository, missing environment, imported review and later ownership change cannot reuse checks',t=>{const f=fixture(t),r=f.check();for(const changes of [{repositoryKey:'d'.repeat(64)},{environment:''},{imported:true,reviews:r.reviews.map(v=>({...v,imported:true}))}])assert.equal(acceptedChecks(f.record,[{...r,...changes}],commit).accepted,false);assert.equal(acceptedChecks(f.record,[{...r,imported:true}],commit).accepted,true);const changed={...f.record,events:[{type:'updated',at:'2099-01-01T00:00:00Z',detail:{fields:['ownerRef']}}]};assert.equal(acceptedChecks(changed,[r],commit).accepted,false);});
test('verified requires current containment and receipt-linked final-commit evidence in the same environment',t=>{const f=fixture(t);f.check();const combined=f.check({commit:targetCommit});f.receipt(combined);assert.equal(f.state().verified,false);const o={...f.observation,contained:true};assert.equal(f.state(o).verified,true);assert.equal(f.state(o).retirementEligible,true);for(const k of ['assetsClear','connectedRoot','submodules'])assert.equal(f.state({...o,[k]:k==='assetsClear'?false:true}).retirementEligible,false);assert.equal(f.state({...o,targetCommit:'d'.repeat(40)}).verified,false);assert.equal(f.state({...o,commit:'e'.repeat(40)}).verified,false);});
test('historical/imported/unlinked/wrong-environment receipts cannot certify current work',t=>{const f=fixture(t);f.check();const combined=f.check({commit:targetCommit}),r=f.receipt(combined),o={...f.observation,contained:true},reports=f.store.list(repositoryKey);for(const changes of [{imported:true},{status:'interrupted'},{repositoryKey:'d'.repeat(64)},{evidenceIDs:[]},{environment:'Different runtime'},{selected:[{lifecycleID:f.record.id,commit,criteriaRevision:99}]}])assert.equal(deriveLifecycle(f.record,o,reports,[{...r,...changes}]).verified,false);const newer={...combined,id:randomUUID(),createdAt:'2099-01-01T00:00:00Z'};assert.equal(deriveLifecycle(f.record,o,[...reports,newer],[r]).verified,false);});
test('missing work is unknown rather than retired without an explicit observed retirement event',t=>{const f=fixture(t);assert.equal(f.state({...f.observation,exists:false}).state,'unknown');f.record.events.push({type:'retired'});assert.equal(f.state({...f.observation,exists:false,complete:false}).state,'unknown');assert.equal(f.state({...f.observation,exists:false}).state,'retired');assert.notEqual(f.state().state,'retired');});
function batch(f,records,observations,selected,extras={}){return batchEligibility({records,observations,selected,reports:f.store.list(repositoryKey),receipts:[],...extras});}
test('selected scope permits owned unfinished exclusions; full scope refuses them',t=>{const f=fixture(t);f.check();const excluded={...structuredClone(f.record),id:randomUUID(),blocker:'Needs repair',nextAction:'Repair failing check'};const records=[f.record,excluded],observations={[f.record.id]:f.observation,[excluded.id]:f.observation};const selected=batch(f,records,observations,[f.record.id]);assert.equal(selected.allowed,true);assert.equal(selected.exclusions[0].reason,'Needs repair');assert.equal(batch(f,records,observations,[f.record.id],{scope:'full'}).allowed,false);assert.equal(batch(f,records,observations,[f.record.id],{unknown:['external']} ).allowed,false);excluded.nextAction='';assert.equal(batch(f,records,observations,[f.record.id]).allowed,false);});
test('selected dependencies can become ready together; missing, unresolved and cyclic prerequisites refuse',t=>{const f=fixture(t),dep={...structuredClone(f.record),id:randomUUID()};f.record.dependencies=[dep.id];f.check();f.check({},dep);const records=[f.record,dep],observations={[f.record.id]:{...f.observation,dependenciesResolved:false},[dep.id]:f.observation};assert.equal(batch(f,records,observations,[f.record.id,dep.id]).allowed,true);assert.equal(batch(f,records,observations,[f.record.id]).allowed,false);observations[dep.id]={...f.observation,contained:true};assert.equal(batch(f,records,observations,[f.record.id]).allowed,true);observations[dep.id].complete=false;assert.equal(batch(f,records,observations,[f.record.id]).allowed,false);observations[dep.id]=f.observation;dep.dependencies=[f.record.id];assert.match(batch(f,records,observations,[f.record.id,dep.id]).reasons.join(' '),/cycle/);});
test('batch rejects duplicates, unknown scope, unknown selected identity, missing observation and mixed targets',t=>{const f=fixture(t);f.check();const records=[f.record],observations={[f.record.id]:f.observation};for(const [selected,extras] of [[[],{}],[[f.record.id,f.record.id],{}],[[randomUUID()],{}],[[f.record.id],{scope:'invalid'}],[[f.record.id],{observations:{}}]])assert.equal(batch(f,records,observations,selected,extras).allowed,false);const other={...structuredClone(f.record),id:randomUUID()};f.check({},other);assert.equal(batch(f,[...records,other],{...observations,[other.id]:{...f.observation,targetCommit:'f'.repeat(40)}},[f.record.id,other.id]).allowed,false);});

test('imported retirement history cannot become current retirement proof',t=>{const f=fixture(t);f.record.events.push({type:'retired'});f.record.importContext={sourceHash:'a'.repeat(64)};assert.notEqual(f.state({...f.observation,exists:false}).state,'retired');});
test('new verified retirement after explicit rebind remains current while imported events stay historical',t=>{const f=fixture(t);f.record.importContext={importedAt:'2026-01-01T00:00:00Z'};f.record.events=[{type:'retired',at:'2026-02-01T00:00:00Z',imported:true}];assert.notEqual(f.state({...f.observation,exists:false}).state,'retired');f.record.events.push({type:'retired',at:'2026-03-01T00:00:00Z'});assert.equal(f.state({...f.observation,exists:false}).state,'retired');});
