import test from 'node:test';
import assert from 'node:assert/strict';
import {realpathSync,mkdtempSync,mkdirSync,renameSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {createServer} from '../server.js';
import {Store} from '../lib/store.js';
import {WorktreeNotes} from '../lib/worktree-notes.js';
import {inspectFolder} from '../lib/projects.js';
const git=(root,...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
async function fixture(t){const base=realpathSync(mkdtempSync(path.join(tmpdir(),'lifecycle-api-'))),root=path.join(base,'repo'),data=path.join(base,'data'),work=path.join(base,'work');mkdirSync(root);git(root,'init','-b','main');git(root,'config','user.name','Fixture');git(root,'config','user.email','fixture@example.test');writeFileSync(path.join(root,'file'),'base');writeFileSync(path.join(root,'version.json'),JSON.stringify({version:'1.2.3',tangents:['1.2.4']}));git(root,'add','.');git(root,'commit','-m','base');git(root,'worktree','add','-b','codex/task',work);writeFileSync(path.join(work,'file'),'task');git(work,'commit','-am','task');const store=new Store(data),project=store.createProject({name:'Fixture',folderPath:root}),notes=new WorktreeNotes(data),context=await inspectFolder(root);const note=notes.prepare({intentID:'fixture',projectID:project.id,sourceContext:context,destination:work,branch:'codex/task',purpose:'Fixture task',origin:{kind:'session',id:'fixture'},ownerKey:'fixture',workRef:'local:fixture'});await notes.attach('fixture');writeFileSync(path.join(data,'codex-runs.json'),JSON.stringify([{id:'fixture',projectID:project.id,status:'completed',task:'Original fixture scope',acceptance:'Original acceptance must survive restore'}]));const server=createServer({directory:data});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 t.after(async()=>{server.shutdownCodex();await new Promise(r=>server.close(r));rmSync(base,{recursive:true,force:true});});
 const api=async(route='',method='GET',body)=>{const r=await fetch(url+'/api/projects/'+project.id+'/lifecycle'+route,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};return {base,root,work,data,project,note,api,url};}
test('lifecycle API uses canonical identity, rejects spoofed evidence and records reviewed checks without execution',async t=>{const f=await fixture(t);let read=await f.api();assert.equal(read.status,200,JSON.stringify(read.data));let record=read.data.records[0];assert.equal(record.id,f.note.id);assert.equal(record.state,'working');let update=await f.api('/'+record.id,'PUT',{expectedRevision:record.revision,criteria:[{id:'tests',label:'Tests pass',required:true}],nextAction:'Review check'});assert.equal(update.status,200);record=update.data;assert.equal((await f.api('/'+record.id,'PUT',{expectedRevision:1,blocker:'stale'})).status,409);
 const check={expectedRevision:record.revision,criterionID:'tests',commit:git(f.work,'rev-parse','HEAD'),environment:'fixture',outcome:'passed',summary:'Fixture check',requestKey:'check-fixture'};assert.equal((await f.api('/'+record.id+'/checks','POST',{...check,observed:true})).status,400);let report=await f.api('/'+record.id+'/checks','POST',check);assert.equal(report.status,200,JSON.stringify(report.data));assert.equal(report.data.observed,false);assert.equal((await f.api('/'+record.id+'/checks','POST',check)).data.id,report.data.id);let review=await f.api('/evidence/'+report.data.id+'/review','POST',{expectedRevision:report.data.revision,decision:'accepted',reason:'Reviewed fixture'});assert.equal(review.status,200);read=await f.api();assert.equal(read.data.records[0].state,'ready',JSON.stringify(read.data.records[0]));writeFileSync(path.join(f.work,'file'),'dirty');read=await f.api();assert.equal(read.data.records[0].ready,false);report=await f.api('/'+record.id+'/checks','POST',{...check,requestKey:'dirty-fixture',expectedRevision:read.data.records[0].revision});assert.equal(report.status,200);assert.equal(report.data.dirtyFingerprint,'unverified-dirty-workspace');});
test('migration previews metadata, preserves release files and replays without duplicate aliases',async t=>{const f=await fixture(t),before=git(f.root,'status','--porcelain'),p=await f.api('/migration/preview','POST',{});assert.equal(p.status,200);assert(p.data.sourceMetadata.some(s=>s.version==='1.2.3'));const input={previewID:p.data.id,requestKey:'migration-fixture',aliases:[{lifecycleID:f.note.id,alias:'1.2.4',context:{cycle:'1.2',repository:'fixture'}}],releaseConvention:'Preserve existing release versions',rulesAcknowledged:true};const applied=await f.api('/migration/apply','POST',input);assert.equal(applied.status,200,JSON.stringify(applied.data));assert.equal((await f.api('/migration/apply','POST',input)).status,200);assert.equal((await f.api()).data.records[0].aliases.length,1);assert.equal(git(f.root,'status','--porcelain'),before);const exported=await f.api('/export');assert.equal(exported.status,200);assert.equal(exported.data.artifactContentsIncluded,false);const bad=structuredClone(exported.data);bad.version=2;assert.equal((await f.api('/import/preview','POST',{bundle:bad})).status,400);});
test('portable metadata restore into an empty store preserves IDs but never grants ownership or launches',async t=>{const f=await fixture(t);const exported=(await f.api('/export')).data,secondData=realpathSync(mkdtempSync(path.join(tmpdir(),'lifecycle-restore-'))),secondStore=new Store(secondData),project=secondStore.createProject({name:'Restored project',folderPath:f.root}),server=createServer({directory:secondData});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.shutdownCodex();await new Promise(r=>server.close(r));rmSync(secondData,{recursive:true,force:true});});const url='http://127.0.0.1:'+server.address().port+'/api/projects/'+project.id+'/lifecycle';const call=async(s,method,body)=>{const r=await fetch(url+s,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};const p=await call('/import/preview','POST',{bundle:exported});assert.equal(p.status,200,JSON.stringify(p.data));const request={previewID:p.data.id,requestKey:'restore-fixture',confirm:true},applied=await call('/import/apply','POST',request);assert.equal(applied.status,200,JSON.stringify(applied.data));assert.equal((await call('/import/apply','POST',request)).status,200);
 const siblingFolder=path.join(f.root,'restore-sibling');mkdirSync(siblingFolder);const siblingResponse=await fetch('http://127.0.0.1:'+server.address().port+'/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Another project',folderPath:siblingFolder})});const sibling=await siblingResponse.json();assert.equal(siblingResponse.status,201);
 const siblingURL='http://127.0.0.1:'+server.address().port+'/api/projects/'+sibling.id+'/lifecycle';const p2=await fetch(siblingURL+'/import/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bundle:exported})});assert.equal(p2.status,200);const p2data=await p2.json();const conflicting=await fetch(siblingURL+'/import/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...request,previewID:p2data.id})});assert.equal(conflicting.status,409);
 const read=(await call('','GET')).data;assert.equal(read.records.length,1);assert.equal(read.records[0].id,f.note.id);assert.equal(read.records[0].attachmentState,'unattached');assert.equal(read.records[0].ownerRef,null);assert.equal(read.records[0].state,'unknown');assert.equal(read.records[0].projectID,project.id);assert.equal(read.records[0].originalTask,'Original fixture scope');assert.equal(read.records[0].originalAcceptance,'Original acceptance must survive restore');renameSync(f.work,f.work+'-moved');const missing=await call('/'+f.note.id+'/rebind','POST',{expectedRevision:read.records[0].revision,confirm:true});assert(missing.status>=400);renameSync(f.work+'-moved',f.work);const rebound=await call('/'+f.note.id+'/rebind','POST',{expectedRevision:read.records[0].revision,confirm:true});assert.equal(rebound.status,200,JSON.stringify(rebound.data));assert.equal(rebound.data.id,f.note.id);assert.equal(rebound.data.attachmentState,'attached');assert.equal(git(f.work,'status','--porcelain'),'');});
test('shared repository export redacts foreign source details and malformed evidence import is rejected before writes',async t=>{const f=await fixture(t);let read=(await f.api()).data,r=read.records[0];r=(await f.api('/'+r.id,'PUT',{expectedRevision:r.revision,criteria:[{id:'check',label:'Check',required:true}]})).data;await f.api('/'+r.id+'/checks','POST',{expectedRevision:r.revision,criterionID:'check',commit:git(f.work,'rev-parse','HEAD'),environment:'fixture',outcome:'failed',summary:'PRIVATE_DIAGNOSTIC',command:'PRIVATE_COMMAND'});const folder=path.join(f.root,'subproject');mkdirSync(folder);const made=await fetch(f.url+'/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Sibling',folderPath:folder})});assert.equal(made.status,201);const sibling=await made.json(),foreign=await fetch(f.url+'/api/projects/'+sibling.id+'/lifecycle/export'),bundle=await foreign.json();assert.equal(foreign.status,200,JSON.stringify(bundle));assert(!JSON.stringify(bundle).includes('PRIVATE_DIAGNOSTIC'));assert(!JSON.stringify(bundle).includes('PRIVATE_COMMAND'));assert.equal(bundle.annotations.length,0);assert.equal(bundle.lifecycle.records[0].sourceRefs.length,0);
 const own=(await f.api('/export')).data;own.evidence.artifactContentsIncluded=true;const {sha256,...payload}=own;const {createHash}=await import('node:crypto');own.sha256=createHash('sha256').update(JSON.stringify(payload)).digest('hex');const before=(await f.api()).data.revision;assert.equal((await f.api('/import/preview','POST',{bundle:own})).status,400);assert.equal((await f.api()).data.revision,before);
});

test('lost evidence response replays the original report after source and acceptance change',async t=>{
 const f=await fixture(t);let record=(await f.api()).data.records[0];record=(await f.api('/'+record.id,'PUT',{expectedRevision:record.revision,criteria:[{id:'tests',label:'Tests',required:true}]})).data;
 const input={expectedRevision:record.revision,criterionID:'tests',commit:git(f.work,'rev-parse','HEAD'),environment:'fixture',outcome:'passed',summary:'Original immutable report',requestKey:'lost-check-response'};
 const original=await f.api('/'+record.id+'/checks','POST',input);assert.equal(original.status,200);
 writeFileSync(path.join(f.work,'file'),'next revision');git(f.work,'commit','-am','next');record=(await f.api()).data.records[0];await f.api('/'+record.id,'PUT',{expectedRevision:record.revision,criteria:[{id:'replacement',label:'Changed acceptance',required:true}]});
 const replay=await f.api('/'+record.id+'/checks','POST',input);assert.equal(replay.status,200,JSON.stringify(replay.data));assert.equal(replay.data.id,original.data.id);assert.equal(replay.data.commit,original.data.commit);assert.equal(replay.data.criteriaRevision,original.data.criteriaRevision);
 assert.equal((await f.api('/'+record.id+'/checks','POST',{...input,summary:'Different claim'})).status,409);
});

test('explicit check records source changes while initial and unchanged observations are not activity',async t=>{
 const f=await fixture(t),initial=(await f.api()).data.records[0];assert.equal(initial.sourceActivity.state,'unobserved');
 let checked=await f.api('/check','POST',{});assert.equal(checked.status,200,JSON.stringify(checked.data));let row=checked.data.records[0];assert.equal(row.lastActivityAt,initial.lastActivityAt);assert.equal(row.sourceActivity.state,'known');
 const stable=await f.api('/check','POST',{});assert.equal(stable.data.records[0].lastActivityAt,initial.lastActivityAt);
 writeFileSync(path.join(f.work,'file'),'changed bytes');checked=await f.api('/check','POST',{});row=checked.data.records[0];assert.equal(checked.status,200,JSON.stringify(checked.data));assert(row.sourceActivity.changedAt);assert(Date.parse(row.lastActivityAt)>Date.parse(initial.lastActivityAt));
 const unchanged=(await f.api()).data.records[0];assert.equal(unchanged.lastActivityAt,row.lastActivityAt);assert.equal(unchanged.sourceActivity.changedAt,row.sourceActivity.changedAt);
});
