import {chooseAgentCard} from './agent-card-helpers.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createServer} from '../server.js';

const root=mkdtempSync(path.join(tmpdir(),'skd-playbook-session-ui-')),projectFolder=path.join(root,'project'),binary=path.join(root,'agent');mkdirSync(projectFolder);writeFileSync(binary,'#!/usr/bin/env node\nconsole.log("session fixture");process.stdin.resume();',{mode:0o755});
const server=createServer({directory:path.join(root,'data'),terminalOptions:{binaries:{codex:binary},discover:async()=>({version:'fixture',auth:'Signed in',models:[{id:'fixture',name:'Fixture',efforts:['low'],defaultEffort:'low',isDefault:true}]})}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;
async function request(route,method='GET',body){const response=await fetch(url+'/api/'+route,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});assert(response.ok,await response.clone().text());return response.json();}
const project=await request('projects','POST',{name:'Save source',folderPath:projectFolder}),profile=await request('agent-profiles','POST',{revision:0,name:'Fixture specialist',systemPrompt:'FROZEN SPECIALIZATION',scope:{kind:'global'},providers:['codex'],skillIDs:[],connectionIDs:[]}),preview=await request(`projects/${project.id}/agent-profile-preview`,'POST',{agent:'codex',mode:'read-only',agentProfile:{mode:'selected',agentProfileID:profile.id}}),session=await request('terminal-sessions','POST',{projectID:project.id,agent:'codex',model:'fixture',effort:'low',mode:'read-only',agentProfile:{mode:'selected',agentProfileID:profile.id,expectedSignature:preview.signature}});
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1200,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`${url}/#sessions/${project.id}/${session.id}`);await page.getByRole('heading',{name:'Session terminal'}).waitFor();await page.getByRole('button',{name:'Hide',exact:true}).click();assert.match(await page.locator('.tool-activity').textContent(),/unavailable/);
 await page.getByRole('button',{name:'Save as Agent',exact:true}).click();await page.getByRole('heading',{name:'Save as Agent',exact:true}).waitFor();assert.match(await page.locator('#dialog').textContent(),/frozen configuration/i);assert.match(await page.locator('#dialog').textContent(),/Observed-only selection is unavailable/);await page.locator('#dialog [name="name"]').fill('Active copy');assert.equal(await page.locator('#dialog [name=systemPrompt]').inputValue(),'FROZEN SPECIALIZATION');await page.locator('#dialog').getByRole('button',{name:'Save Agent',exact:true}).click();await page.getByText('Agent saved from the session.',{exact:true}).waitFor();assert.equal((await request('terminal-sessions/'+session.id)).status,'running');
 await request('terminal-sessions/'+session.id+'/stop','POST',{});for(let index=0;index<100;index++){if((await request('terminal-sessions/'+session.id)).status==='cancelled')break;await new Promise(resolve=>setTimeout(resolve,20));}await page.reload();await page.getByRole('heading',{name:'Session terminal'}).waitFor();await page.getByRole('button',{name:'Hide',exact:true}).click();await page.getByRole('button',{name:'Save as Agent',exact:true}).click();await page.locator('#dialog [name="name"]').fill('Ended copy');assert.equal(await page.locator('#dialog [name=systemPrompt]').inputValue(),'FROZEN SPECIALIZATION');await page.locator('#dialog').getByRole('button',{name:'Save Agent',exact:true}).click();await page.getByText('Agent saved from the session.',{exact:true}).waitFor();
 const library=await request(`playbooks?scope=project&projectID=${project.id}`);assert.equal(library.entries.length,3);assert(library.entries.filter(item=>item.id!==profile.id).every(item=>item.source.sessionID===session.id&&item.systemPrompt==='FROZEN SPECIALIZATION'));assert(!JSON.stringify(library).includes('session fixture'));await page.goto(`${url}/#sessions/${project.id}`);await chooseAgentCard(page,page.locator('.agent-selection-card'),'Codex','Fixture','Home');await page.locator('#codex-mode').selectOption('read-only');await page.getByText('Agent, Skills and Connections',{exact:true}).click();await page.locator('#session-playbook').selectOption('selected:'+profile.id);await page.getByRole('button',{name:'Start session',exact:true}).click();await page.getByRole('heading',{name:'Agent configuration'}).waitFor();await page.getByRole('button',{name:'Use configuration'}).click();await page.getByRole('heading',{name:'Session terminal'}).waitFor();const launched=await request('sessions');assert.equal(launched.length,2);const newest=launched.find(r=>r.id!==session.id);assert.equal(newest.agentContext.agentProfile.systemPrompt,'FROZEN SPECIALIZATION');assert.equal(newest.initialPrompt,undefined);assert.deepEqual(errors,[]);console.log('Save session as playbook browser passed for active and ended PTY sessions, unavailable observed-only coverage, safe provenance and no source mutation.');
}finally{await browser.close();server.shutdownCodex();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));rmSync(root,{recursive:true,force:true});}
