import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createServer} from '../server.js';

const root=mkdtempSync(path.join(tmpdir(),'skd-playbook-session-ui-')),projectFolder=path.join(root,'project'),binary=path.join(root,'agent');mkdirSync(projectFolder);writeFileSync(binary,'#!/usr/bin/env node\nconsole.log("session fixture");process.stdin.resume();',{mode:0o755});
const server=createServer({directory:path.join(root,'data'),terminalOptions:{binaries:{codex:binary},discover:async()=>({version:'fixture',auth:'Signed in',models:[{id:'fixture',name:'Fixture',efforts:['low'],defaultEffort:'low',isDefault:true}]})}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;
async function request(route,method='GET',body){const response=await fetch(url+'/api/'+route,{method,headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});assert(response.ok,await response.clone().text());return response.json();}
const project=await request('projects','POST',{name:'Save source',folderPath:projectFolder}),session=await request('terminal-sessions','POST',{projectID:project.id,agent:'codex',model:'fixture',effort:'low',mode:'read-only',playbook:{mode:'legacy',skills:{mode:'replace',skillIDs:[]},connections:{mode:'replace',connectionIDs:[]}}});
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1200,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`${url}/#sessions/${project.id}/${session.id}`);await page.getByRole('heading',{name:'Session terminal'}).waitFor();await page.getByRole('button',{name:'Hide',exact:true}).click();assert.match(await page.locator('.tool-activity').textContent(),/unavailable/);
 await page.getByRole('button',{name:'Save as playbook',exact:true}).click();await page.getByRole('heading',{name:'Save as playbook',exact:true}).waitFor();assert.match(await page.locator('#dialog').textContent(),/frozen configuration/i);assert.match(await page.locator('#dialog').textContent(),/Observed-only selection is unavailable/);await page.locator('#dialog [name="name"]').fill('Active copy');await page.locator('#dialog').getByRole('button',{name:'Save playbook',exact:true}).click();await page.getByText('Playbook saved from the session.',{exact:true}).waitFor();assert.equal((await request('terminal-sessions/'+session.id)).status,'running');
 await request('terminal-sessions/'+session.id+'/stop','POST',{});for(let index=0;index<100;index++){if((await request('terminal-sessions/'+session.id)).status==='cancelled')break;await new Promise(resolve=>setTimeout(resolve,20));}await page.reload();await page.getByRole('heading',{name:'Session terminal'}).waitFor();await page.getByRole('button',{name:'Hide',exact:true}).click();await page.getByRole('button',{name:'Save as playbook',exact:true}).click();await page.locator('#dialog [name="name"]').fill('Ended copy');await page.locator('#dialog').getByRole('button',{name:'Save playbook',exact:true}).click();await page.getByText('Playbook saved from the session.',{exact:true}).waitFor();
 const library=await request(`playbooks?scope=project&projectID=${project.id}`);assert.equal(library.entries.length,2);assert(library.entries.every(item=>item.source.sessionID===session.id));assert(!JSON.stringify(library).includes('session fixture'));assert.deepEqual(errors,[]);console.log('Save session as playbook browser passed for active and ended PTY sessions, unavailable observed-only coverage, safe provenance and no source mutation.');
}finally{await browser.close();server.shutdownCodex();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));rmSync(root,{recursive:true,force:true});}
