import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, renameSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from '../server.js';
const root=mkdtempSync(path.join(tmpdir(),'skd-project-browser-'));
const directory=path.join(root,'data'),repo=path.join(root,'Newton fixture'),plain=path.join(root,'TT fixture');mkdirSync(repo);mkdirSync(plain);
const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
git('init','-b','main');writeFileSync(path.join(repo,'README.md'),'fixture');git('add','.');git('-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','baseline');git('remote','add','origin','git@github.com:example/newton-fixture.git');
const initialCommit=git('rev-parse','HEAD');
const server=createServer({directory});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(7000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 // Workflows are off the sidebar (#18); open the project's Workflows route, retrying while the page settles.
 const openWorkflows=async()=>{for(let i=0;i<60;i++){await page.evaluate(()=>{if(!location.hash.startsWith('#workflows/')&&/^#[a-z-]+\/[\w-]+/.test(location.hash))location.hash='#workflows/'+location.hash.split('/')[1];});await page.waitForTimeout(150);if(await page.evaluate(()=>location.hash.startsWith('#workflows/')))return;}throw Error('Workflows route did not open: '+await page.evaluate(()=>location.hash));};
 const openDetails=async()=>{const back=page.url();if(await page.locator('#project-home').count())await page.locator('#project-home').click();await page.getByRole('button',{name:'Project details',exact:true}).click();await page.evaluate(back=>document.querySelector('#dialog').addEventListener('close',()=>{setTimeout(()=>{location.replace(back);location.reload();},0);},{once:true}),back);};
 await page.goto(url+'/#workflows/unassigned');await page.getByRole('button',{name:'+ Add project',exact:true}).waitFor();assert.equal(await page.title(),'SKD Workbench');
 assert.equal(await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project'),'unassigned');assert.equal(await page.locator('[data-overview-flow]').count(),2);
 const original=await(await fetch(url+'/api/state')).json();
 const legacyRun=await(await fetch(url+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({flowID:original.flows[0].id,flowVersion:1,task:'Original project'})})).json();
 await page.locator('[data-add-project]').click();
 await page.getByLabel('Project name',{exact:true}).fill('Newton');await page.getByLabel('Local folder',{exact:true}).fill(repo);
 await page.locator('#dialog').getByRole('button',{name:'Add project',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-sidebar-project][aria-current]')?.textContent.replace('▱','').trim()==='Newton');assert.equal(await page.locator('[data-overview-flow]').count(),0);
 const projectA=await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project');
 await openDetails();
 await page.waitForFunction(()=>document.querySelector('#connection-details').textContent.includes('github.com'));
 assert.match(await page.locator('#connection-details').textContent(),/main/);assert.match(await page.locator('#connection-details').textContent(),/No remote configured|origin/);
 mkdirSync('output',{recursive:true});await page.screenshot({path:'output/skd-project-details.png',fullPage:true});
 await page.keyboard.press('Escape');
 await page.locator('.brand').click();await page.locator('[data-sidebar-project=\"'+'unassigned'+'\"]').click();await openWorkflows();
 await page.locator('[data-overview-flow]').first().click();await page.getByRole('button',{name:'Move',exact:true}).click();await page.getByLabel('Destination project',{exact:true}).selectOption(projectA);await page.getByRole('button',{name:'Move workflow',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-sidebar-project][aria-current]')?.textContent.replace('▱','').trim()==='Newton');assert.equal(await page.locator('[data-step]').count()>0,true);
 await page.locator('[data-crumb-view=overview]').click();await page.getByRole('button',{name:/Run history/}).click();assert.equal(await page.locator('[data-open-run]').count(),0);
 await page.locator('.brand').click();await page.locator('[data-sidebar-project=\"'+'unassigned'+'\"]').click();await openWorkflows();await page.getByRole('button',{name:/Run history/}).click();assert.equal(await page.locator('[data-open-run]').count(),1);
 await page.locator('.brand').click();await page.locator('.project-card[data-project=\"'+projectA+'\"]').click();await openWorkflows();
 await page.locator('[data-overview-flow]').first().click();await page.locator('[data-step]').first().click();await page.getByLabel('Step name',{exact:true}).fill('Unsaved project edit');
 await page.locator('.sidebar-all-projects').click();await page.getByRole('heading',{name:'Keep your changes?',exact:true}).waitFor();await page.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project'),projectA);
 await page.getByRole('button',{name:'Save flow',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#save').disabled);
 await page.getByRole('button',{name:'Close step settings',exact:true}).click();
 await page.getByRole('button',{name:'▷ Try flow',exact:true}).click();assert.equal(await page.getByLabel('Task',{exact:true}).inputValue(),'');await page.getByLabel('Task',{exact:true}).fill('Project provenance check');await page.getByRole('button',{name:'Start simulation',exact:true}).click();
 await page.getByRole('button',{name:'Simulate this step →',exact:true}).waitFor();await page.getByText('Project & code at run start',{exact:true}).click();assert.match(await page.locator('.run-context').textContent(),new RegExp(initialCommit));
 const newState=await(await fetch(url+'/api/state')).json(),r=newState.runs.find(r=>r.task==='Project provenance check');assert.equal(r.projectID,projectA);assert.equal(r.sourceContext.git.dirty,false);
 // Project edits and file changes cannot rewrite the saved run context.
 await openDetails();await page.getByLabel('Project name',{exact:true}).fill('Newton Dev');await page.getByRole('button',{name:'Save project',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-sidebar-project][aria-current]')?.textContent.replace('▱','').trim()==='Newton Dev');
 writeFileSync(path.join(repo,'README.md'),'changed');
 await page.waitForURL('**/#run/'+r.id);await page.waitForLoadState('load');
 await page.getByText('Project & code at run start',{exact:true}).click();assert.match(await page.locator('.run-context').textContent(),/Newton/);assert.doesNotMatch(await page.locator('.run-context').textContent(),/Newton Dev/);assert.match(await page.locator('.run-context').textContent(),/Clean/);
 await openDetails();await page.waitForFunction(()=>document.querySelector('#connection-details').textContent.includes('Uncommitted changes'));await page.keyboard.press('Escape');
 // A second, non-Git project remains usable, with a useful missing-folder state.
 await page.locator('[data-add-project]').click();await page.getByLabel('Project name',{exact:true}).fill('TT');await page.getByLabel('Local folder',{exact:true}).fill(plain);await page.locator('#dialog').getByRole('button',{name:'Add project',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-sidebar-project][aria-current]')?.textContent.replace('▱','').trim()==='TT');const projectB=await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project');
 await openDetails();await page.waitForFunction(()=>document.querySelector('#connection-details').textContent.includes('not in a Git repository'));await page.keyboard.press('Escape');
 await openWorkflows();await page.getByRole('button',{name:'Create a flow',exact:true}).click();await page.getByLabel('Flow name',{exact:true}).fill('TT only');await page.locator('#dialog').getByRole('button',{name:'Create flow',exact:true}).click();
 await page.getByRole('button',{name:'+ Add a step',exact:true}).click();await page.locator('[data-type="agent"]').click();await page.getByRole('button',{name:'Save flow',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#save').disabled);
 renameSync(plain,plain+' moved');await openDetails();await page.waitForFunction(()=>document.querySelector('#connection-details').textContent.includes('missing'));await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'▷ Try flow',exact:true}).click();await page.getByLabel('Task',{exact:true}).fill('Missing folder');await page.getByRole('button',{name:'Start simulation',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#dialog-error').textContent.includes('missing'));await page.keyboard.press('Escape');
 await openDetails();await page.getByLabel('Local folder',{exact:true}).fill(plain+' moved');await page.getByRole('button',{name:'Save project',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);
 await page.locator('.brand').click();await page.locator('.project-card[data-project=\"'+projectA+'\"]').click();await openWorkflows();assert.equal(await page.locator('[data-overview-flow]').count(),1);assert.equal(await page.getByRole('button',{name:'TT only',exact:true}).count(),0);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'output/skd-project-mobile.png',fullPage:true});
 await page.locator('.brand').click();await page.locator('.project-card[data-project=\"'+projectB+'\"]').click();await openWorkflows();assert.equal(await page.locator('[data-overview-flow]').count(),1);await page.reload();assert.equal(await page.locator('[data-sidebar-project][aria-current]').getAttribute('data-sidebar-project'),projectB);
 await page.locator('.brand').click();await page.locator('.project-card[data-project=\"'+projectA+'\"]').click();await page.setViewportSize({width:1440,height:1050});await page.screenshot({path:'output/skd-project-desktop.png',fullPage:true});
 const final=await(await fetch(url+'/api/state')).json();assert.equal(final.runs.find(x=>x.id===legacyRun.id).projectID,'unassigned');assert.deepEqual(errors,[]);
 console.log('Project browser checks passed: rename, add/edit/canonical folder, Git/non-Git/missing/refresh, move, scoped history, dirty navigation, immutable run provenance, mobile/reload.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(root,{recursive:true,force:true});}
