import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,chmodSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createServer} from '../server.js';

const root=mkdtempSync(path.join(tmpdir(),'skd-resources-browser-')),home=path.join(root,'home'),projectFolder=path.join(root,'project'),directory=path.join(root,'data');mkdirSync(home,{recursive:true});mkdirSync(projectFolder,{recursive:true});
const skill=(base,area,name,body)=>{const folder=path.join(base,area,'skills',name);mkdirSync(folder,{recursive:true});writeFileSync(path.join(folder,'SKILL.md'),body);};
skill(home,'.agents','native-global','---\nname: Native global\ndescription: User skill\n---\nGlobal native instructions.');skill(projectFolder,'.agents','native-project','---\nname: Native project\ndescription: Project skill\n---\nProject native instructions.');
const mcpServer=path.join(root,'mcp-fixture.mjs');writeFileSync(mcpServer,`#!/usr/bin/env node\nlet b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;let n;while((n=b.indexOf('\\n'))>=0){const l=b.slice(0,n);b=b.slice(n+1);if(!l)continue;const m=JSON.parse(l);if(m.id===1)console.log(JSON.stringify({jsonrpc:'2.0',id:1,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'fixture',version:'1'}}}));if(m.id===2)console.log(JSON.stringify({jsonrpc:'2.0',id:2,result:{tools:[{name:'workbench_fixture_tool',inputSchema:{type:'object'}}]}}));}});`);chmodSync(mcpServer,0o755);mkdirSync(path.join(home,'.codex'),{recursive:true});writeFileSync(path.join(home,'.codex','config.toml'),`[mcp_servers.fixture]\ncommand=${JSON.stringify(process.execPath)}\nargs=[${JSON.stringify(mcpServer)}]\nenv_vars=["FIXTURE_ENV"]\n[mcp_servers.secret]\nurl="https://example.invalid/mcp?token=never-render"\n`);
const server=createServer({directory,skillsOptions:{home},connectionsOptions:{home,timeoutMs:2000,enumerateCodex:async()=>[{name:'fixture',transport:'stdio'},{name:'secret',transport:'http'}]},codexOptions:{discover:async()=>({version:'fixture',auth:'Fixture',models:[{id:'fixture',name:'Fixture',efforts:['low'],defaultEffort:'low',isDefault:true}]})}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;
const post=async(route,data)=>{const response=await fetch(url+'/api/'+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});assert(response.ok,await response.clone().text());return response.json();};const project=await post('projects',{name:'Resource fixture',folderPath:projectFolder}),flow=await post('flows',{name:'Context flow',projectID:project.id,steps:[{id:'agent-step',type:'agent',name:'Use context',instructions:'Inspect context.',model:'fixture',effort:'low',skills:{mode:'inherit',skillIDs:[]}}]});
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url+'/#home');await page.getByRole('heading',{name:'Home',exact:true}).waitFor();assert.equal(await page.locator('[data-global-skills]').count(),1);assert.equal(await page.locator('[data-global-connections]').count(),1);assert.equal(await page.locator('[data-global-playbooks]').count(),1);
 await page.locator('[data-global-skills]').click();await page.getByRole('heading',{name:'Skills',exact:true}).waitFor();assert.match(page.url(),/#skills$/);await page.getByRole('button',{name:/^Native global/}).click();assert.match(await page.locator('.resource-detail').textContent(),/AVAILABLE ON DISK/i);
 await page.getByRole('button',{name:'Import instruction text'}).click();await page.getByText('Instruction text imported.',{exact:true}).waitFor();await page.getByRole('button',{name:'New skill'}).click();await page.getByLabel('Name',{exact:true}).fill('Managed global');await page.getByLabel('Description',{exact:true}).fill('Global managed entry');await page.getByLabel('Instructions',{exact:true}).fill('Use exact managed instructions.');await page.getByRole('button',{name:'Save skill'}).click();await page.getByText('Skill saved.',{exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:/^Managed global/}).click();assert.match(await page.locator('.resource-detail').textContent(),/Use exact managed instructions/);
 await page.getByRole('button',{name:'New skill'}).click();await page.getByLabel('Name',{exact:true}).fill('Unsaved');await page.locator('.brand').click();await page.getByRole('heading',{name:'Keep your changes?'}).waitFor();await page.getByRole('button',{name:'Keep editing'}).click();assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Unsaved');await page.locator('.brand').click();await page.getByRole('button',{name:'Discard changes'}).click();
 await page.locator(`[data-project="${project.id}"]`).click();await page.locator('.sidebar [data-sidebar-view="skills"]').click();await page.getByRole('heading',{name:'Skills',exact:true}).waitFor();assert.match(page.url(),new RegExp(`#skills/${project.id}$`));await page.getByRole('button',{name:/^Managed global/}).waitFor();const skillBox=page.locator('[data-policy-skill]').first();await skillBox.check();await page.getByRole('button',{name:'Save assignments'}).click();await page.getByText('Skill assignments saved for future launches.',{exact:true}).waitFor();await page.reload();await page.locator('[data-policy-skill]').first().waitFor();assert(await page.locator('[data-policy-skill]:checked').count()>=1);
 await page.goto(url+'/#connections');await page.getByRole('heading',{name:'Connections (MCP)',exact:true}).waitFor();await page.getByRole('button',{name:/^fixture/}).click();const globalText=await page.locator('#connections-view').textContent();assert(!globalText.includes('never-render'));assert(!globalText.includes(mcpServer));assert.match(globalText,/FIXTURE_ENV/);
 await page.goto(url+`/#connections/${project.id}`);await page.getByRole('heading',{name:'Connections (MCP)',exact:true}).waitFor();await page.getByLabel('Workbench selection').check();await page.locator('[data-policy-connection]').first().check();await page.getByRole('button',{name:'Save connection policy'}).click();await page.getByText('Connection policy saved for future sessions.',{exact:true}).waitFor();await page.getByRole('button',{name:/^fixture/}).click();await page.getByRole('button',{name:'Check tool catalog'}).click();await page.getByText('workbench_fixture_tool',{exact:true}).waitFor();assert.match(await page.locator('.resource-detail').textContent(),/Tools available|available/);
 await page.goto(url+`/#playbooks/${project.id}`);await page.getByRole('heading',{name:'Agents',exact:true}).waitFor();assert.match(page.url(),new RegExp(`#agents/${project.id}$`));const newPlaybook=page.getByRole('button',{name:'New Agent'});await newPlaybook.focus();await page.keyboard.press('Enter');await page.locator('[data-editor] [name="name"]').fill('Development');await page.getByLabel('Agent system prompt',{exact:true}).fill('Review interfaces for accessibility.');await page.locator('[data-editor-skill]').first().check();const fixtureConnection=page.locator('[data-editor-connection][data-provider="codex"]').first();await fixtureConnection.check();await page.getByRole('button',{name:'Save Agent'}).click();await page.getByText('Agent saved.',{exact:true}).waitFor();await page.getByRole('button',{name:/^Development/}).click();assert.match(await page.locator('.resource-detail').textContent(),/1 prior version|0 prior versions/);await page.getByRole('button',{name:'Duplicate'}).click();await page.getByText('Agent duplicated.',{exact:true}).waitFor();assert.equal(await page.locator('[data-playbook-id]').count(),2);const defaultValue=await page.locator('[data-default-playbook] option').nth(1).getAttribute('value');await page.locator('[data-default-playbook]').selectOption(defaultValue);await page.getByRole('button',{name:'Save default'}).click();await page.getByText('Project default saved.',{exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'Agents',exact:true}).waitFor();assert.notEqual(await page.locator('[data-default-playbook]').inputValue(),'');
 await page.locator('[data-playbook-id]').first().click();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('[data-editor] [name="description"]').fill('Updated through the library UI.');await page.getByRole('button',{name:'Save Agent'}).click();await page.getByText('Agent saved.',{exact:true}).waitFor();await page.locator('[data-playbook-id]').nth(1).click();await page.getByRole('button',{name:'Archive',exact:true}).click();await page.getByRole('button',{name:'Restore',exact:true}).waitFor();await page.getByRole('button',{name:'Restore',exact:true}).click();await page.getByRole('button',{name:'Archive',exact:true}).waitFor();
 await page.goto(url+`/#sessions/${project.id}`);await page.getByRole('heading',{name:'Sessions',exact:true}).waitFor();await page.getByText('Agent, Skills and Connections',{exact:true}).click();await page.getByText('Managed global',{exact:true}).waitFor();assert.equal(await page.locator('[data-session-skill]').count()>=1,true);assert.equal(await page.locator('[data-session-connection]').count()>=1,true);
 assert.equal(await page.locator('#session-playbook').inputValue(),'inherit');assert.equal(await page.locator('[data-session-skill]:checked').count(),1);assert.equal(await page.locator('[data-session-connection]:checked').count(),1);assert.equal(await page.locator('[data-codex-run]').count(),0);
 await page.goto(url+`/#flow/${flow.id}`);await page.getByRole('heading',{name:'Context flow',exact:true}).waitFor();await page.getByRole('button',{name:'Run settings'}).click();await page.getByLabel('Task',{exact:true}).fill('Verify saved skill override.');await page.getByText('Skills for this step',{exact:true}).click();await page.getByLabel('Replace with this set').check();await page.locator('[data-workflow-skill]').first().check();await page.getByRole('button',{name:'Save run settings'}).click();await page.getByText('Run settings saved. Agent configuration is reviewed before execution.',{exact:true}).waitFor();await page.getByRole('button',{name:'Run settings'}).click();await page.getByText('Skills for this step',{exact:true}).click();assert.equal(await page.getByLabel('Replace with this set').isChecked(),true);assert.equal(await page.locator('[data-workflow-skill]:checked').count(),1);await page.getByRole('button',{name:'Cancel'}).click();
 await page.goto(url+'/#agents');await page.getByRole('button',{name:'New Agent',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Global specialist');await page.getByLabel('Agent system prompt',{exact:true}).fill('GLOBAL SPECIALIZATION');await page.getByRole('button',{name:'Save Agent',exact:true}).click();await page.getByText('Agent saved.',{exact:true}).waitFor();
 await page.goto(url+`/#agents/${project.id}`);await page.getByRole('button',{name:/^Global specialist/}).click();await page.getByRole('button',{name:'Copy to project'}).click();await page.getByText('Agent duplicated.',{exact:true}).waitFor();const profiles=await(await fetch(url+'/api/agent-profiles')).json();const original=profiles.entries.find(e=>e.name==='Global specialist'),copy=profiles.entries.find(e=>e.name==='Global specialist copy');assert.equal(original.scope,'global');assert.equal(copy.projectID,project.id);assert.equal(copy.systemPrompt,'GLOBAL SPECIALIZATION');assert.notEqual(original.id,copy.id);
 await page.getByRole('button',{name:/^Global specialist copy/}).click();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Agent system prompt',{exact:true}).fill('UNSAVED');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await(await fetch(url+'/api/agent-profiles')).json()).entries.find(e=>e.id===copy.id).systemPrompt,'GLOBAL SPECIALIZATION');
 await page.goto(url+'/#skills/not-a-project');await page.getByRole('heading',{name:'Page unavailable'}).waitFor();await page.getByRole('button',{name:'Return home'}).click();
 await page.goto(url+`/#playbooks/${project.id}`);await page.getByRole('heading',{name:'Agents',exact:true}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(button=>button.textContent.trim()==='Refresh'&&!button.disabled));await page.getByLabel('Appearance',{exact:true}).selectOption('dark');await page.evaluate(()=>{const toast=document.querySelector('#toast');if(toast)toast.style.display='none';});mkdirSync('output',{recursive:true});await page.screenshot({path:'output/playbooks-project-desktop.png',fullPage:true,animations:'disabled'});await page.goto(url+`/#connections/${project.id}`);await page.getByRole('heading',{name:'Connections (MCP)',exact:true}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(button=>button.textContent.trim()==='Refresh inventory'&&!button.disabled));await page.getByLabel('Appearance',{exact:true}).selectOption('light');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{const toast=document.querySelector('#toast');if(toast)toast.style.display='none';});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/connections-project-mobile.png',fullPage:true});await page.goto(url+`/#playbooks/${project.id}`);await page.getByRole('heading',{name:'Agents',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/playbooks-project-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 console.log('Skills, Connections and Playbooks browser passed: global/project routes, CRUD/defaults, session overrides without launch, dirty guard, redacted MCP details, explicit tool-list check, dark desktop and mobile overflow.');
}finally{await browser.close();server.shutdownCodex();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));rmSync(root,{recursive:true,force:true});}
