import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createServer} from '../server.js';
const root=mkdtempSync(path.join(tmpdir(),'skd-settings-browser-')),repo=path.join(root,'project');mkdirSync(repo);writeFileSync(path.join(repo,'AGENTS.md'),'Fixture agent instructions <script>bad()</script>');
const provider={auth:'fixture',models:[{id:'one',name:'Model One',efforts:['low','high'],defaultEffort:'low',isDefault:true},{id:'two',name:'Model Two',efforts:['low','high'],defaultEffort:'high'}]};
const server=createServer({directory:path.join(root,'data'),terminalOptions:{discover:async()=>provider}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});
try{
 const project=await(await fetch(url+'/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Settings fixture',folderPath:repo})})).json();
 const page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/#home');await page.getByRole('button',{name:'Global settings',exact:true}).first().click();
 const dialog=page.getByRole('dialog');
 const choose=async name=>dialog.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name,exact:true}).click();
 const bounds=await dialog.boundingBox();assert(bounds.width>=1100&&bounds.width>bounds.height);
 const navBounds=await page.locator('.settings-menu').boundingBox(),contentBounds=await page.locator('.settings-content').boundingBox();assert(navBounds.x+navBounds.width<=contentBounds.x+1);
 await page.screenshot({path:'output/settings-landscape-appearance.png'});
 await dialog.getByLabel('Light mode',{exact:true}).fill('#2266cc');await dialog.getByLabel('Dark mode',{exact:true}).fill('#bb77ff');
 await choose('Codex');
 const one=dialog.getByRole('button',{name:'Model One',exact:true}).first();await one.click();assert.equal(await one.getAttribute('aria-pressed'),'false');
 assert.equal(await one.locator('.model-visibility-state').innerText(),'Hidden');
 await choose('Claude');assert.equal(await dialog.getByRole('button',{name:'Model One',exact:true}).getAttribute('aria-pressed'),'true');
 await choose('Appearance');assert.equal(await dialog.getByLabel('Light mode',{exact:true}).inputValue(),'#2266cc');
 await choose('Reference documents');await dialog.getByLabel('Reference document',{exact:true}).selectOption({label:'instructions/2026-09-20-development-lanes.md'});
 assert.match(await page.locator('#settings-references .settings-document-status').innerText(),/future work, not implementation authorization/);
 const footerBefore=await dialog.getByRole('button',{name:'Save settings',exact:true}).boundingBox();
 await page.locator('.settings-content').evaluate(el=>el.scrollTop=el.scrollHeight);
 const footerAfter=await dialog.getByRole('button',{name:'Save settings',exact:true}).boundingBox();assert.equal(footerBefore.y,footerAfter.y);assert(footerAfter.y+footerAfter.height<1000);
 // Hidden preference panels still contribute their draft values when saving from a document.
 await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()),'#2266cc');
 await page.getByLabel('Appearance',{exact:true}).selectOption('dark');
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()),'#bb77ff');
 await page.reload();await page.getByRole('button',{name:'Global settings',exact:true}).first().click();assert.equal(await page.getByLabel('Dark mode',{exact:true}).inputValue(),'#bb77ff');
 const codexButton=dialog.getByRole('navigation').getByRole('button',{name:'Codex',exact:true});await codexButton.focus();await page.keyboard.press('Enter');assert.equal(await codexButton.getAttribute('aria-current'),'page');
 await one.waitFor();assert.equal(await one.getAttribute('aria-pressed'),'false');
 await page.screenshot({path:'output/settings-landscape-models.png'});
 await choose('Repository rules');await page.getByLabel('Rule file',{exact:true}).selectOption({label:'AGENTS.md'});
 assert.match(await page.locator('#settings-rules pre').innerText(),/SKD Workbench agent guidance/);
 assert.equal(await page.locator('#settings-rules option').filter({hasText:'instructions/'}).count(),0);
 await page.screenshot({path:'output/settings-landscape-guidance.png'});
 await choose('Appearance');await dialog.getByLabel('Light mode',{exact:true}).fill('#112233');await choose('Codex');await one.click();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Global settings',exact:true}).first().click();assert.equal(await dialog.getByLabel('Light mode',{exact:true}).inputValue(),'#2266cc');await choose('Codex');assert.equal(await one.getAttribute('aria-pressed'),'false');
 await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});
 await page.goto(url+'/#system/'+project.id);await page.reload();await page.getByText('AGENTS.md',{exact:true}).click();assert.match(await page.locator('#project-instructions pre').innerText(),/Fixture agent instructions/);assert.equal(await page.locator('#project-instructions script').count(),0);
 await page.screenshot({path:'output/project-system.png',fullPage:true});
 await page.goto(url+'/#sessions/'+project.id);await page.reload();await page.locator('[data-agent-parameter="model"]').click();await page.getByRole('radio',{name:'Model Two',exact:true}).waitFor();assert.equal(await page.getByRole('radio',{name:'Model One',exact:true}).count(),0);
 await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Global settings',exact:true}).first().click();await page.getByLabel('Dark mode',{exact:true}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await dialog.getByLabel('Settings section',{exact:true}).selectOption('codex');await one.waitFor();
 await page.screenshot({path:'output/settings-mobile-models.png'});
 await dialog.getByLabel('Settings section',{exact:true}).selectOption('references');await dialog.getByLabel('Reference document',{exact:true}).waitFor();
 assert(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth));assert(await page.locator('.settings-content').evaluate(el=>el.scrollWidth<=el.clientWidth));
 const mobileFooter=await dialog.getByRole('button',{name:'Save settings',exact:true}).boundingBox();assert(mobileFooter.y+mobileFooter.height<844);
 await page.screenshot({path:'output/settings-mobile-guidance.png'});
 await page.setViewportSize({width:1100,height:700});await choose('Appearance');const compact=await dialog.boundingBox();assert(compact.y>=0&&compact.y+compact.height<=700);
 assert.deepEqual(errors,[]);console.log('Settings browser passed: landscape hierarchy, keyboard navigation, drafts across sections, save from guidance, cancel, persistence, provider visibility, read-only previews, fixed footer, desktop/mobile overflow.');
}finally{await browser.close();await new Promise(r=>server.close(r));rmSync(root,{recursive:true,force:true});}
