import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Store} from '../lib/store.js';
import {createServer} from '../server.js';
const root=mkdtempSync(path.join(tmpdir(),'skd-sidebar-')),directory=path.join(root,'data');
const store=new Store(directory);mkdirSync(path.join(root,'second'));
const a=store.createProject({name:'First project',folderPath:root}),b=store.createProject({name:'Second project',folderPath:path.join(root,'second')});
const flow=store.createFlow({name:'Sidebar check',projectID:a.id,steps:[{id:'check',type:'check',name:'Verify',instructions:''}]});
let folderChoice=0;const server=createServer({directory,folderPicker:async()=>{folderChoice++;if(folderChoice===1)return {cancelled:true};if(folderChoice===2)return {folderPath:root};throw Error('Picker unavailable');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}/#flow/${flow.id}`);
 const views=page.getByRole('navigation',{name:'Project views',exact:true});await views.waitFor();
 assert.equal(await views.locator('.view-icon').count(),8);assert.equal(await page.getByRole('navigation',{name:'Projects',exact:true}).count(),0);
 assert.equal(await views.locator('[aria-current]').getAttribute('data-sidebar-view'),'overview');
 assert(await views.getByRole('button',{name:/Scratchpad/}).isDisabled());
 await page.locator('[data-step]').click();await page.getByLabel('Step name',{exact:true}).fill('Unsaved');
 await views.getByRole('link',{name:'Issues',exact:true}).click();await page.getByRole('button',{name:'Keep editing',exact:true}).click();
 assert.equal(await views.locator('[aria-current]').getAttribute('data-sidebar-view'),'overview');
 await page.locator('.sidebar-all-projects').click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();
 await page.getByRole('navigation',{name:'Projects',exact:true}).getByRole('button',{name:'Second project'}).click();
 await page.getByRole('heading',{name:'Second project',exact:true}).waitFor();
 assert.equal(await page.locator('.project-views .view-icon').count(),8);
 await page.getByRole('button',{name:'Project details',exact:true}).click();await page.getByLabel('Project name',{exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.locator('[data-add-project]').click();await page.getByLabel('Project name',{exact:true}).fill('Selected project');
 await page.getByLabel('Local folder',{exact:true}).fill('/keep/manual');
 await page.locator('#choose-folder').click();await page.waitForFunction(()=>!document.querySelector('#choose-folder').disabled);assert.equal(await page.getByLabel('Local folder',{exact:true}).inputValue(),'/keep/manual');
 await page.locator('#choose-folder').click();await page.waitForFunction(()=>!document.querySelector('#choose-folder').disabled);assert.equal(await page.getByLabel('Local folder',{exact:true}).inputValue(),root);assert.equal(await page.getByLabel('Project name',{exact:true}).inputValue(),'Selected project');
 await page.locator('#choose-folder').click();await page.waitForFunction(()=>document.querySelector('#dialog-error').textContent.length>0);assert.equal(await page.getByLabel('Local folder',{exact:true}).inputValue(),root);await page.keyboard.press('Escape');
 await page.locator('main [data-view-link="overview"]').click();await page.getByRole('heading',{name:'Workflows',exact:true}).waitFor();
 assert.equal(await views.locator('[aria-current]').getAttribute('data-sidebar-view'),'overview');
 mkdirSync('output',{recursive:true});await page.screenshot({path:'output/projects-sidebar-desktop.png'});
 await page.reload();await views.waitFor();assert.equal(await views.locator('[aria-current]').getAttribute('data-sidebar-view'),'overview');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/projects-sidebar-mobile.png',fullPage:true});
 await views.getByRole('link',{name:'System',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'System',exact:true}).waitFor();await page.locator('.sidebar-all-projects').click();await page.getByRole('navigation',{name:'Projects',exact:true}).getByRole('button',{name:'First project'}).click();await page.getByRole('heading',{name:'First project',exact:true}).waitFor();
 assert.deepEqual(errors,[]);console.log('Project sidebar passed: eight icons, scoped view links, active view, planned Scratchpad, dirty guard, All projects, details/add, reload, keyboard and mobile.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(root,{recursive:true,force:true});}
