import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';import {WebSocket} from 'ws';import {attachTerminalStreams} from '../lib/terminal-stream.js';import {createWorkspaceTerminal} from '../lib/workspace-terminal.js';
async function fixture(t){let emit,exit,spawned=0,writes=[];const manager=createWorkspaceTerminal('.',{spawn:()=>{spawned++;return {onData:fn=>emit=fn,onExit:fn=>exit=fn,write:data=>writes.push(data),resize(){},kill(){exit();}};}});const session=manager.open(),server=http.createServer(),streams=attachTerminalStreams(server,{workspace:manager,agents:manager,ackTimeout:150});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 t.after(async()=>{streams.shutdown();manager.shutdown();await new Promise(r=>server.close(r));});
 const connect=(cursor=0,path='workspace-terminal')=>{const ws=new WebSocket(origin.replace('http','ws')+`/api/${path}/${session.id}/stream?cursor=${cursor}`,{origin});const queue=[],waiters=[];ws.on('message',data=>{const message=JSON.parse(data);if(waiters.length)waiters.shift()(message);else queue.push(message);});ws.next=()=>queue.length?Promise.resolve(queue.shift()):new Promise(r=>waiters.push(r));ws.ack=m=>ws.send(JSON.stringify({type:'ack',cursor:m.cursor}));return ws;};return {manager,session,origin,connect,emit:data=>emit(data),writes,spawned:()=>spawned};}
test('stream emits immediately, reconnects by cursor without launching, and cleans up on end',async t=>{const f=await fixture(t),ws=f.connect();const initial=await ws.next();ws.ack(initial);f.emit('hello');const next=await ws.next();assert.equal(next.data,'hello');ws.ack(next);ws.send(JSON.stringify({type:'input',data:'a'}));await new Promise(r=>setTimeout(r,10));assert.deepEqual(f.writes,['a']);ws.close();await once(ws,'close');f.emit(' world');const second=f.connect(next.cursor,'terminal-sessions');const resumed=await second.next();assert.equal(resumed.data,' world');assert.equal(f.spawned(),1);second.ack(resumed);f.manager.stop(f.session.id);const stopped=await second.next();assert.equal(stopped.session.status,'stopped');second.ack(stopped);});
test('upgrade rejects foreign/missing origin, invalid cursor and unknown sessions',async t=>{const f=await fixture(t);for(const [origin,suffix] of [['https://evil.test',''],[undefined,''],[f.origin,'?cursor=-1']]){const ws=new WebSocket(f.origin.replace('http','ws')+`/api/workspace-terminal/${f.session.id}/stream${suffix}`,{origin});ws.on('error',()=>{});const [,res]=await once(ws,'unexpected-response');assert(res.statusCode>=400);res.resume();ws.terminate();}const ws=new WebSocket(f.origin.replace('http','ws')+'/api/workspace-terminal/missing/stream',{origin:f.origin});ws.on('error',()=>{});const [,res]=await once(ws,'unexpected-response');assert.equal(res.statusCode,404);res.resume();ws.terminate();assert.equal(f.spawned(),1);});
test('slow clients get bounded frames, truncation reset and timeout; invalid input closes',async t=>{const f=await fixture(t),ws=f.connect();const initial=await ws.next();f.emit('x'.repeat(250000));ws.ack(initial);const frame=await ws.next();assert(frame.reset);assert.equal(frame.data.length,32768);const [code]=await once(ws,'close');assert.equal(code,1008);const other=f.connect();await other.next();other.send(JSON.stringify({type:'resize',cols:1,rows:0}));assert.equal((await once(other,'close'))[0],1008);const big=f.connect();await big.next();big.send(JSON.stringify({type:'input',data:'x'.repeat(16385)}));assert.equal((await once(big,'close'))[0],1008);assert.deepEqual(f.writes,[]);});
test('stream preserves Unicode across chunk boundaries and rejects invalid acknowledgement',async t=>{const f=await fixture(t),ws=f.connect();const initial=await ws.next();f.emit('x'.repeat(32767)+'😀tail');ws.ack(initial);const first=await ws.next();assert.equal(first.data.length,32767);ws.ack(first);const second=await ws.next();assert.equal(second.data,'😀tail');ws.send(JSON.stringify({type:'ack',cursor:second.cursor+1}));assert.equal((await once(ws,'close'))[0],1008);});
test('upgrade rejects hostile Host even with matching Origin',async t=>{const f=await fixture(t);const ws=new WebSocket(f.origin.replace('http','ws')+`/api/workspace-terminal/${f.session.id}/stream`,{origin:'http://evil.test:4390',headers:{Host:'evil.test:4390'}});ws.on('error',()=>{});const [,res]=await once(ws,'unexpected-response');assert.equal(res.statusCode,403);res.resume();ws.terminate();});
