import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {createServer} from '../server.js';
const root=mkdtempSync(path.join(tmpdir(),'skd-workflow-ui-')),repo=path.join(root,'project');mkdirSync(repo);const binary=path.join(root,'codex-fixture');writeFileSync(binary,`#!/usr/bin/env node
let p='';process.stdin.on('data',c=>p+=c);process.stdin.on('end',()=>setTimeout(()=>{console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:p.includes('Please revise')?'Revised output':'First output <script>escaped</script>'}}));console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:100,cached_input_tokens:80,output_tokens:20}}));},150));`,{mode:0o755});
const server=createServer({directory:path.join(root,'data'),codexOptions:{binary,discover:async()=>({version:'fixture',models:[{id:'fixture',name:'Fixture',efforts:['low','high'],defaultEffort:'low',isDefault:true}]})}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;const post=async(route,body)=>(await fetch(url+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})).json();const project=await post('projects',{name:'Flow fixture',folderPath:repo});const flow=await post('flows',{projectID:project.id,name:'Real review loop',steps:[{id:'agent',name:'Plan',type:'agent',model:'Fable',effort:'high',instructions:'Plan it.'},{id:'review',name:'My review',type:'human',instructions:'Review it.',maxRetries:1,retryFrom:'agent'},{id:'check',name:'Check',type:'check',instructions:'Verify the result.'}]});
const browser=await chromium.launch({channel:'chrome'});
try{const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/#flow/'+flow.id);await page.getByRole('button',{name:'Run',exact:true}).click();await page.getByRole('heading',{name:'Run flow with Codex'}).waitFor();assert.equal(await page.getByLabel('Codex model for Plan').inputValue(),'');await page.locator('#workflow-all-model').selectOption('fixture');await page.getByLabel('Task',{exact:true}).fill('Test a real workflow');await page.getByRole('button',{name:'Start real workflow'}).click();await page.getByRole('button',{name:'Continue workflow'}).waitFor();assert.match(await page.locator('.codex-output').first().textContent(),/First output <script>/);
 await page.getByLabel('Workflow review note').fill('Please revise');await page.locator('[data-live-step="review"]').click();assert.equal(await page.getByLabel('Workflow review note').inputValue(),'Please revise');assert.equal(await page.evaluate(()=>document.activeElement.dataset.liveStep),'review');await page.getByRole('button',{name:'Request changes',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.loop-note')?.textContent.includes('1 / 1'));await page.getByRole('button',{name:'Continue workflow'}).waitFor();assert(await page.getByRole('button',{name:'Request changes',exact:true}).isDisabled());await page.locator('[data-live-step="agent"]').click();assert.equal(await page.locator('.attempt').count(),2);assert.match(await page.locator('.codex-output').allTextContents().then(v=>v.join('\n')),/Revised output/);
 await page.reload();await page.getByRole('button',{name:'Continue workflow'}).waitFor();await page.getByRole('button',{name:'Continue workflow'}).click();await page.getByRole('button',{name:'Record check & continue'}).waitFor();await page.getByLabel('Workflow review note').fill('Checked fixture output');await page.getByRole('button',{name:'Record check & continue'}).click();await page.waitForFunction(()=>document.querySelector('.workflow-summary strong')?.textContent==='Flow finished');assert.match(await page.locator('.metrics').textContent(),/240/);assert.equal((await(await fetch(url+'/api/codex/runs')).json()).length,0);
 mkdirSync('output',{recursive:true});await page.screenshot({path:'output/workflow-fixture-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/workflow-fixture-mobile.png',fullPage:true});await page.getByRole('button',{name:'All workflow runs'}).click();await page.locator('[data-workflow-run]').waitFor();assert.equal(await page.locator('[data-workflow-run]').count(),1);assert.deepEqual(errors,[]);console.log('Workflow UI passed: explicit mapping, launch, real-step output, review notes/retry, retained attempts, reload, manual check, totals, scoped history and mobile.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(root,{recursive:true,force:true});}
