import {mkdirSync,existsSync,statSync,readFileSync,writeFileSync,renameSync,openSync,closeSync,fsyncSync} from 'node:fs';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {assert} from './domain.js';
import {readGit} from './git-read.js';
import {repositoryIdentity} from './lifecycle-service.js';
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.length<=max&&!v.includes('\0');
export class RuntimeObservations{
 constructor(directory,sourceRoot){mkdirSync(directory,{recursive:true});this.file=path.join(directory,'lifecycle-runtime.json');if(existsSync(this.file))assert(statSync(this.file).size<1024*1024,'Runtime history exceeds limit.');this.rows=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):[];assert(Array.isArray(this.rows)&&this.rows.length<=1000&&this.rows.every(r=>text(r.id,100)&&/^[a-f0-9]{64}$/.test(r.repositoryKey)&&text(r.environment,500)&&text(r.method,2000)&&text(r.observedAt,80)),'Damaged runtime observation history.');const observedAt=new Date().toISOString();this.startup=(async()=>{try{const common=await readGit(sourceRoot,['rev-parse','--path-format=absolute','--git-common-dir']),commit=await readGit(sourceRoot,['rev-parse','HEAD']),dirty=await readGit(sourceRoot,['status','--porcelain']);if(!common.ok||!commit.ok||!dirty.ok)return null;const repositoryKey=createHash('sha256').update(JSON.stringify(await repositoryIdentity(common.value))).digest('hex');return {repositoryKey,status:'observed',environment:'SKD Workbench server',commit:commit.value,dirty:!!dirty.value,version:null,source:'process-start',method:'Source identity captured at server startup; dirty state is not a reproducible build',observedAt,shellVersion:'0.5.0-79'};}catch{return null;}})();}
 async read(repositoryKey){const startup=await this.startup;return {current:startup?.repositoryKey===repositoryKey?startup:this.rows.findLast(r=>r.repositoryKey===repositoryKey)||{status:'unknown'},history:this.rows.filter(r=>r.repositoryKey===repositoryKey)};}
 record(repositoryKey,input){assert(input&&Object.keys(input).every(k=>['environment','version','commit','artifactHash','method'].includes(k)),'Invalid runtime observation.');assert(text(input.environment,500)&&text(input.method,2000)&&(!input.version||text(input.version,500))&&(!input.commit||/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(input.commit))&&(!input.artifactHash||/^[a-f0-9]{64}$/.test(input.artifactHash)),'Provide observed environment, identity and method.');assert(input.version||input.commit||input.artifactHash,'Provide an actually observed version, commit or artifact hash.');assert(this.rows.length<1000,'Runtime observation history is full.');const row={...input,id:randomUUID(),repositoryKey,source:'user',status:'reported',observedAt:new Date().toISOString()},next=[...this.rows,row],body=JSON.stringify(next);assert(Buffer.byteLength(body)<1024*1024,'Runtime history exceeds limit.');writeFileSync(this.file+'.tmp',body,{mode:0o600});const fd=openSync(this.file+'.tmp','r');try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(this.file+'.tmp',this.file);this.rows=next;return structuredClone(row);}
}
