import {dirtyIdentity} from './workspace-tasks.js';
import {realpath,stat,open} from 'node:fs/promises';
import {constants,mkdirSync,existsSync,readFileSync,writeFileSync,renameSync,statSync,openSync,closeSync,fsyncSync,unlinkSync} from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {assert} from './domain.js';
import {readGit} from './git-read.js';
import {withRegistrations} from './workspace-registration.js';
import {deriveLifecycle} from './lifecycle-policy.js';
const clone=structuredClone,hash=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const only=(v,keys)=>assert(v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k)),'Invalid lifecycle request.');
async function git(folder,args){const r=await readGit(folder,args,{raw:true});assert(r.ok,'Git inspection is unavailable or exceeded its limit.',409);return r.value;}
export async function repositoryIdentity(folder){const canonical=await realpath(folder),s=await stat(canonical,{bigint:true});return {path:canonical,device:String(s.dev),inode:String(s.ino),birthTime:String(s.birthtimeNs)};}
export async function observeOverlap(records,observations,targetCommit){
 const paths=new Map(),overlaps=[];let complete=records.length<=20;
 for(const record of records.slice(0,20)){const o=observations[record.id];if(!o?.exists||!o.commit||!targetCommit){complete=false;continue;}try{const base=(await git(o.path,['merge-base',o.commit,targetCommit])).trim();const names=new Set();for(const args of [['diff','--name-only','-z',base,o.commit,'--'],['diff','--name-only','-z','--'],['diff','--cached','--name-only','-z','--'],['ls-files','--others','--exclude-standard','-z']])for(const name of (await git(o.path,args)).split('\0').filter(Boolean))names.add(name);assert(names.size<=1000,'Overlap inventory exceeded its limit.');paths.set(record.id,names);}catch{complete=false;}}
 const ids=[...paths.keys()];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const shared=[...paths.get(ids[i])].filter(p=>paths.get(ids[j]).has(p));if(shared.length)overlaps.push({ids:[ids[i],ids[j]],paths:shared.slice(0,100),incomplete:shared.length>100,revision:hash([observations[ids[i]].commit,observations[ids[j]].commit,shared])});}
 return {overlaps,overlapComplete:complete};
}
export class LifecycleService{
 constructor(directory,{store,evidence,attention,notes,gitStatus,executor,projects,project,workspaceTasks,runtime,activity}){Object.assign(this,{store,evidence,attention,notes,gitStatus,executor,projects,project,workspaceTasks,runtime});this.sourceActivity=activity;this.previews=new Map();mkdirSync(directory,{recursive:true});this.file=path.join(directory,'lifecycle-imports.json');if(existsSync(this.file))assert(statSync(this.file).size<=32*1024*1024,'Lifecycle import history exceeds its limit.');this.imports=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):{version:1,operations:[]};assert(this.imports.version===1&&Array.isArray(this.imports.operations)&&this.imports.operations.length<=1000&&this.imports.operations.every(o=>typeof o.requestKey==='string'&&o.requestKey.length<=100&&/^[a-f0-9]{64}$/.test(o.hash)&&/^[a-f0-9]{64}$/.test(o.repositoryKey)&&['pending','failed','complete'].includes(o.status)),'Damaged lifecycle import history.');assert(!this.imports.taskContexts||Array.isArray(this.imports.taskContexts)&&this.imports.taskContexts.length<=10000&&this.imports.taskContexts.every(c=>typeof c.lifecycleID==='string'&&typeof c.projectID==='string'&&typeof c.task==='string'&&c.task.length<=100000&&typeof c.acceptance==='string'&&c.acceptance.length<=20000),'Damaged imported task context.');if(this.imports.annotations)this.notes.validate({version:1,records:this.imports.annotations});}
 saveImports(){assert(this.imports.operations.length<=1000,'Import history is full.');const body=JSON.stringify(this.imports);assert(Buffer.byteLength(body)<32*1024*1024,'Import history is full.');const temporary=this.file+'.'+randomUUID()+'.tmp';try{writeFileSync(temporary,body,{mode:0o600,flag:'wx'});const fd=openSync(temporary,'r');try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(temporary,this.file);const directory=openSync(path.dirname(this.file),'r');try{fsyncSync(directory);}finally{closeSync(directory);}}finally{try{unlinkSync(temporary);}catch{}}}

 current(project){const p=this.project(project.id);assert(p.version===project.version&&p.folderPath===project.folderPath,'Project changed. Refresh before continuing.',409);return p;}
 idle(){assert(!this.executor.owner&&!this.executor.active&&!this.executor.starting&&!this.executor.cleaning,'Finish active execution before changing lifecycle state.',409);}
 async context(project){this.current(project);const snapshot=await this.gitStatus.read(project,{targetRef:'refs/heads/main'});assert(snapshot.status==='connected','Connect a Git repository first.',409);const repositoryKey=hash(await repositoryIdentity(snapshot.commonDirectory));this.current(project);return {snapshot,repositoryKey};}
 async scoped(project,id){const context=await this.context(project),record=this.store.get(id);assert(record.repositoryKey===context.repositoryKey,'Lifecycle belongs to another repository.',403);return {...context,record};}
 own(project,record){assert(record.projectID===project.id||record.attachmentState==='unattached','Use the original project to edit this task.',403);}
 async read(project){
  const {snapshot,repositoryKey}=await this.context(project),s=await withRegistrations(snapshot,project,this.notes),records=this.store.list(repositoryKey),reports=this.evidence.list(repositoryKey),receipts=this.evidence.receipts(repositoryKey),observations={},result=[];
  const complete=!s.stale&&!s.partial&&!s.truncated,active=Boolean(this.executor.owner||this.executor.active||this.executor.starting||this.executor.cleaning),connected=await Promise.all(this.projects().filter(p=>p.folderPath).map(p=>realpath(p.folderPath).catch(()=>null)));
  const target=s.worktrees.find(w=>w.branch==='main'),unknown=s.worktrees.filter(w=>w.path!==target?.path&&!w.current&&w.registration?.status!=='managed').map(w=>({id:w.id,path:w.path,branch:w.branch,reason:w.registration?.status||'unassigned'}));
  const branchOnly=s.branches.filter(b=>!b.worktreeIDs.length&&b.name!=='main'&&b.comparison?.ahead!==0);unknown.push(...branchOnly.map(b=>({id:'branch:'+b.name,branch:b.name,reason:'Branch without a tracked worktree'})));
  const tasks=this.workspaceTasks.list(project).tasks;
  for(const record of records){
   const row=s.worktrees.find(w=>w.registration?.id===record.id),annotation=this.notes.list().find(n=>n.id===record.id);let contained=null,assetsClear=false,submodules=null;
   if(row?.available&&row.commit&&s.target?.commit){try{const r=await readGit(s.root,['merge-base','--is-ancestor',row.commit,s.target.commit],{raw:true});contained=r.ok?true:r.exitCode===1?false:null;}catch{}}
   if(row?.available&&complete){try{assetsClear=!(await git(row.path,['ls-files','--others','--exclude-standard','-z']))&&!(await git(row.path,['ls-files','--others','--ignored','--exclude-standard','-z']));submodules=(await git(row.path,['ls-files','--stage','-z'])).split('\0').some(x=>x.startsWith('160000 '));}catch{}}
   observations[record.id]={complete,attached:row?.registration?.status==='managed',exists:Boolean(row?.available),commit:row?.commit||null,targetCommit:s.target?.commit||null,dirty:row?.dirty??null,active,operations:row?.operations||null,locked:row?.locked,detached:row?.detached,isTarget:row?.branch==='main'||row?.current,benchmark:annotation?.classification==='benchmark',contained,assetsClear,submodules,connectedRoot:row?connected.some(p=>p&&(p===row.path||p.startsWith(row.path+path.sep))):true,dependenciesResolved:!(record.dependencies||[]).length,path:row?.path||annotation?.destination||null,branch:row?.branch||null};
  }
  for(const r of records){const o=observations[r.id];o.dependenciesResolved=(r.dependencies||[]).every(id=>observations[id]?.contained===true);const state=deriveLifecycle(r,o,reports,receipts);const annotation=this.notes.list().find(n=>n.id===r.id),task=tasks.find(t=>t.registrationID===r.id),original=r.projectID===project.id?(task?{task:task.originalTask,acceptance:task.acceptance}:annotation?await this.workspaceTasks.originContext(annotation):this.imports.taskContexts?.find(c=>c.lifecycleID===r.id&&c.projectID===project.id)):null;result.push({...r,...this.sourceActivity?.project(r),originalTask:original?.task||'',originalAcceptance:original?.acceptance||'',ownerRef:r.projectID===project.id?r.ownerRef:(r.ownerRef?'other-project':null),registrationOwnerRef:r.projectID===project.id?r.registrationOwnerRef:null,importContext:r.projectID===project.id?r.importContext:r.importContext?{...r.importContext,originalOwnerRef:null}:null,events:r.projectID===project.id?r.events:r.events.map(e=>({...e,detail:{redacted:true}})),sourceRefs:r.projectID===project.id?r.sourceRefs:[],annotationSnapshot:r.projectID===project.id?r.annotationSnapshot:{...r.annotationSnapshot,origin:null},purpose:annotation?.purpose||r.annotationSnapshot?.purpose||'Unassigned task',sources:r.projectID===project.id?annotation?.sources||[]:[],sourceAccess:r.projectID===project.id?'project':'other-project',taskID:tasks.find(t=>t.registrationID===r.id&&t.state==='attached')?.id||null,observation:o,...state,effectiveState:state.state,isTarget:o.isTarget});}
  const overlap=await observeOverlap(records.filter(r=>!observations[r.id]?.isTarget&&!observations[r.id]?.benchmark),observations,s.target?.commit);
  const attentionObservations={complete,activity:Object.fromEntries(records.map((r,index)=>[r.id,{state:active||!complete||index>=20||this.sourceActivity&&this.sourceActivity.get(repositoryKey,r.id)?.complete!==true?'unknown':'idle'}])),targetDirty:target?.dirty!==false,unknownCandidates:unknown,interruptedOperations:this.imports.operations.filter(o=>o.repositoryKey===repositoryKey&&o.status!=='complete'),...overlap};
  this.current(project);return {repositoryKey,projectID:project.id,projectVersion:project.version,revision:this.store.revision,checkedAt:s.checkedAt,complete,records:result,unknown,observations,attention:this.attention.evaluate(repositoryKey,{records:result.filter(r=>!r.observation.benchmark),observations:attentionObservations,now:Date.now()}),receipts,reports:this.publicEvidence(project,reports,records),target:{commit:s.target?.commit||null,path:target?.path||null,dirty:target?.dirty??null},snapshotID:s.snapshotID,migration:this.store.snapshot(repositoryKey).migrations||[],runtime:(await this.runtime?.read(repositoryKey))?.current||{status:'unknown'},runtimeHistory:(await this.runtime?.read(repositoryKey))?.history||[]};
 }
 async check(project,input){
  only(input,[]);const live=await this.read(project),entries=[];
  for(const record of live.records.slice(0,20)){
   const o=record.observation;let fingerprint=null,complete=false;
   if(live.complete&&o.exists&&o.attached&&!o.active){try{fingerprint=await dirtyIdentity(o.path);complete=true;}catch{}}
   entries.push({id:record.id,commit:o.commit,fingerprint,complete});
  }
  this.current(project);this.sourceActivity?.observe({repositoryKey:live.repositoryKey,entries});return this.read(project);
 }

 async update(project,id,input){only(input,['expectedRevision','criteria','blocker','nextAction','dependencies','ownerRef']);this.idle();const {record,repositoryKey}=await this.scoped(project,id);this.own(project,record);for(const dep of input.dependencies||[])assert(this.store.get(dep).repositoryKey===repositoryKey,'Dependency belongs to another repository.',403);this.idle();this.current(project);return this.store.update(id,input);}
 async recordCheck(project,id,input){
  only(input,['expectedRevision','criterionID','commit','dirtyFingerprint','environment','outcome','summary','command','exitCode','expected','actual','reproduction','artifacts','requestKey']);
  const {record,repositoryKey}=await this.scoped(project,id);this.own(project,record);
  const {expectedRevision,...data}=input,requestFingerprint=hash(Object.fromEntries(Object.entries(data).sort(([a],[b])=>a.localeCompare(b))));
  const prior=input.requestKey&&this.evidence.list(repositoryKey,id).find(r=>r.requestKey===input.requestKey);
  if(prior){assert(prior.requestFingerprint===requestFingerprint,'Evidence request key belongs to another report.',409);this.activity(id,'check-recorded',prior.id);return prior;}
  assert(expectedRevision===record.revision,'Task changed. Refresh before recording evidence.',409);assert(record.criteria.some(c=>c.id===input.criterionID),'Choose a defined acceptance check.');
  const live=await this.read(project),row=live.records.find(r=>r.id===id),o=row.observation;
  assert(input.commit===o.commit||input.commit===o.targetCommit,'Record a check for the observed source or target commit.',409);
  if(!live.complete||(input.commit===o.commit&&o.dirty!==false)||(input.commit===o.targetCommit&&live.target.dirty!==false))data.dirtyFingerprint='unverified-dirty-workspace';
  this.current(project);assert(this.store.get(id).revision===expectedRevision,'Task changed while inspecting evidence.',409);
  const report=this.evidence.record({...data,repositoryKey,lifecycleID:id,criteriaRevision:record.criteriaRevision},{source:'user',observed:false,requestFingerprint});this.activity(id,'check-recorded',report.id);return report;
 }
 async review(project,id,input){only(input,['expectedRevision','decision','reason','requestKey']);const evidence=this.evidence.get(id),{record}=await this.scoped(project,evidence.lifecycleID);this.own(project,record);const result=this.evidence.review(id,{...input,reviewer:'user'});this.activity(record.id,'evidence-reviewed',result.reviews.at(-1).id);return result;}
 activity(id,type,reference){const current=this.store.get(id);if(!current.events.some(e=>e.type===type&&e.detail.reference===reference))this.store.event(id,{expectedRevision:current.revision,type,detail:{reference}});}
 async settings(project,input){only(input,['expectedRevision','timezone','unfinishedLimit','inactivityDays','retentionDays']);const {repositoryKey}=await this.context(project);return this.attention.update(repositoryKey,input);}
 async snooze(project,input){only(input,['expectedRevision','key','reason','until']);const {repositoryKey}=await this.context(project);return this.attention.snooze(repositoryKey,input);}
 preview(kind,project,value){for(const [k,p]of this.previews)if(p.expires<Date.now())this.previews.delete(k);assert(this.previews.size<100,'Too many lifecycle previews.',429);const id=randomUUID();const result={...value,id,kind,project:clone(project),expires:Date.now()+120000};this.previews.set(id,result);return result;}
 take(project,id,kind){const p=this.previews.get(id);assert(p&&p.kind===kind&&p.project.id===project.id&&p.project.version===project.version&&p.expires>Date.now(),'Preview expired. Review a fresh preview.',409);this.current(project);return p;}
 async legacy(project){const {snapshot,repositoryKey}=await this.context(project),files=[];for(const name of ['version.json','package.json','AGENTS.md','CLAUDE.md']){const filename=path.join(snapshot.root,name);let handle;try{handle=await open(filename,constants.O_RDONLY|constants.O_NOFOLLOW);const info=await handle.stat();assert(info.isFile()&&info.size<=256*1024,'Legacy metadata is too large for preview.',409);const buffer=Buffer.alloc(256*1024+1);const {bytesRead}=await handle.read(buffer,0,buffer.length,0);assert(bytesRead<=256*1024,'Legacy metadata grew during preview.',409);const content=buffer.subarray(0,bytesRead).toString('utf8');let json=null;try{json=JSON.parse(content);}catch{}files.push({name,sha256:hash(content),version:typeof json?.version==='string'?json.version:null,aliases:[...new Set(content.match(/\b\d+\.\d+\.\d+\b/g)||[])].slice(0,100),numberingRules:/tangent|checkpoint.{0,30}number|version\.json/i.test(content)});}catch(e){if(e.code!=='ENOENT')throw e;}finally{await handle?.close();}}
  return {repositoryKey,sourceHash:hash(files),sourceMetadata:files,inventory:snapshot.worktrees.map(w=>({id:w.id,path:w.path,branch:w.branch})),complete:!snapshot.stale&&!snapshot.partial&&!snapshot.truncated};}
 async migrationPreview(project){const data=await this.legacy(project);return this.preview('migration',project,{...data,expectedRevision:this.store.revision,records:this.store.list(data.repositoryKey).map(r=>({id:r.id,aliases:r.aliases}))});}
 async migrate(project,input){only(input,['previewID','requestKey','aliases','releaseConvention','rulesAcknowledged']);this.idle();const p=this.take(project,input.previewID,'migration'),fresh=await this.legacy(project);assert(fresh.sourceHash===p.sourceHash&&fresh.repositoryKey===p.repositoryKey&&fresh.complete,'Legacy metadata or repository changed. Preview again.',409);assert(input.rulesAcknowledged===true,'Review legacy numbering rules before accepting migration.');for(const a of input.aliases||[])assert(this.store.get(a.lifecycleID).repositoryKey===p.repositoryKey,'Alias target belongs to another repository.',403);this.idle();this.current(project);return this.store.migration(p.repositoryKey,{requestKey:input.requestKey,expectedRevision:p.expectedRevision,aliases:input.aliases||[],releaseConvention:input.releaseConvention,sourceHash:p.sourceHash,sourceMetadata:p.sourceMetadata,rulesAcknowledged:true});}
 publicEvidence(project,reports,records){return reports.map(r=>records.find(x=>x.id===r.lifecycleID)?.projectID===project.id?r:{...r,requestFingerprint:undefined,sourceID:null,summary:'Evidence from another project',command:null,expected:null,actual:null,reproduction:null,reviews:r.reviews.map(v=>({...v,reason:'Review from another project'})),artifacts:r.artifacts.map(a=>({...a,label:'Artifact from another project'}))});}
 async export(project){const {repositoryKey}=await this.context(project),live=await this.read(project);const taskContexts=live.records.filter(r=>r.projectID===project.id&&(r.originalTask||r.originalAcceptance)).map(r=>({lifecycleID:r.id,task:r.originalTask,acceptance:r.originalAcceptance,...(r.taskID?{taskID:r.taskID}:{})}));const payload={version:1,repositoryKey,taskContexts,annotations:this.notes.list().filter(n=>n.projectID===project.id&&hash(n.sourceRepositoryIdentity)===repositoryKey),lifecycle:this.store.snapshot(repositoryKey,{projectID:project.id}),evidence:{...this.evidence.snapshot(repositoryKey),reports:this.publicEvidence(project,this.evidence.list(repositoryKey),this.store.list(repositoryKey))},artifactContentsIncluded:false};return {...payload,sha256:hash(payload)};}
 async importPreview(project,input){only(input,['bundle']);const bundle=input.bundle;assert(bundle&&Buffer.byteLength(JSON.stringify(bundle))<=16*1024*1024,'Import exceeds 16 MiB.');const {sha256,...payload}=bundle;assert(payload.version===1&&sha256===hash(payload),'Import checksum or schema does not match.');this.store.validate({version:1,revision:bundle.lifecycle.revision,records:bundle.lifecycle.records,migrations:bundle.lifecycle.migrations,imports:[]});this.evidence.validate({version:1,revision:0,reports:bundle.evidence.reports,receipts:bundle.evidence.receipts});assert(bundle.lifecycle.repositoryKey===bundle.repositoryKey&&bundle.evidence.repositoryKey===bundle.repositoryKey,'Bundle repository identities differ.');const lifecycleIDs=new Set(bundle.lifecycle.records.map(r=>r.id));this.notes.validate({version:1,records:bundle.annotations||[]});assert((bundle.annotations||[]).every(n=>lifecycleIDs.has(n.id)&&hash(n.sourceRepositoryIdentity)===bundle.repositoryKey),'Annotation scope does not match the bundle.');assert(Array.isArray(bundle.taskContexts||[])&&(bundle.taskContexts||[]).length<=10000&&(bundle.taskContexts||[]).every(c=>lifecycleIDs.has(c.lifecycleID)&&typeof c.task==='string'&&c.task.length<=100000&&typeof c.acceptance==='string'&&c.acceptance.length<=20000&&(!c.taskID||/^[a-f0-9-]{36}$/.test(c.taskID))),'Invalid original task context.');assert(bundle.evidence.reports.every(r=>lifecycleIDs.has(r.lifecycleID))&&bundle.evidence.receipts.every(r=>r.selected.every(s=>lifecycleIDs.has(s.lifecycleID))),'Evidence references missing lifecycle records.');const {repositoryKey}=await this.context(project);this.evidence.importSnapshot(bundle.evidence,{repositoryKey,dryRun:true});return this.preview('import',project,{bundle:clone(bundle),repositoryKey,expectedRevision:this.store.revision,originalRepositoryKey:bundle.repositoryKey,attachments:'unattached',artifactContentsIncluded:false});}
 async importApply(project,input){only(input,['previewID','requestKey','confirm']);this.idle();assert(input.confirm===true,'Confirm metadata-only import with unverified attachments.');const p=this.take(project,input.previewID,'import');const currentContext=await this.context(project);assert(currentContext.repositoryKey===p.repositoryKey,'Repository changed. Preview import again.',409);this.idle();this.current(project);assert(typeof input.requestKey==='string'&&input.requestKey.length<=100&&input.requestKey.length>=8,'Invalid import request key.');const old=this.imports.operations.find(o=>o.requestKey===input.requestKey);if(old){assert(old.hash===p.bundle.sha256&&old.repositoryKey===p.repositoryKey&&old.projectID===project.id,'Import key belongs to different data.',409);if(old.status==='complete')return clone(old);}else{this.imports.operations.push({projectID:project.id,requestKey:input.requestKey,hash:p.bundle.sha256,repositoryKey:p.repositoryKey,status:'pending',createdAt:new Date().toISOString()});this.saveImports();}
  const operation=this.imports.operations.find(o=>o.requestKey===input.requestKey);this.executor.owner='lifecycle-import:'+input.requestKey;try{this.store.importSnapshot(p.bundle.lifecycle,{requestKey:input.requestKey,expectedRevision:p.expectedRevision,repositoryKey:p.repositoryKey,projectID:project.id});this.evidence.importSnapshot(p.bundle.evidence,{repositoryKey:p.repositoryKey});this.imports.annotations??=[];for(const annotation of p.bundle.annotations||[])if(!this.imports.annotations.some(a=>a.id===annotation.id))this.imports.annotations.push(annotation);this.imports.taskContexts??=[];for(const context of p.bundle.taskContexts||[])if(!this.imports.taskContexts.some(c=>c.lifecycleID===context.lifecycleID&&c.projectID===project.id))this.imports.taskContexts.push({...context,projectID:project.id});for(const candidate of this.imports.operations)if(candidate.projectID===project.id&&candidate.repositoryKey===p.repositoryKey&&candidate.hash===p.bundle.sha256)candidate.status='complete';this.saveImports();return clone(operation);}catch(e){operation.status='failed';operation.error=e.message;this.saveImports();throw e;}finally{if(this.executor.owner==='lifecycle-import:'+input.requestKey)this.executor.owner=null;}}
 async rebind(project,id,input){only(input,['expectedRevision','confirm']);this.idle();assert(input.confirm===true,'Confirm reattachment of the verified workspace.');const {record}=await this.scoped(project,id);let note=this.notes.list().find(n=>n.id===id);if(!note){const snapshot=this.imports.annotations?.find(n=>n.id===id);assert(snapshot,'Original attachment metadata is unavailable; retain this record for manual recovery.',404);note=await this.notes.restore(snapshot,{projectID:project.id,validate:()=>{this.current(project);this.idle();}});}assert(note.projectID===project.id,'Use the original project for reattachment.',403);await this.notes.verify(id,note.destination,note.ownerKey);this.current(project);this.idle();return this.store.rebind(note,{expectedRevision:input.expectedRevision});}
}
