import {mkdirSync,existsSync,readFileSync,writeFileSync,renameSync,unlinkSync,openSync,closeSync,fsyncSync,statSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {assert,copy,now} from './domain.js';

const MAX_BYTES=32*1024*1024,MAX_RECORDS=10000,MAX_EVENTS=2000,BACKUPS=8;
const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const text=(v,label,max,empty=false)=>{assert(typeof v==='string'&&Buffer.byteLength(v)<=max&&!v.includes('\0')&&(empty||v.trim()),`Invalid ${label}.`);return v;};
const uuid=v=>{assert(typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(v),'Invalid lifecycle UUID.');return v;};
const key=v=>{assert(typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),'Invalid repository key or source hash.');return v;};
const revision=v=>assert(Number.isSafeInteger(v)&&v>=0,'Invalid revision.');
const stamp=v=>{assert(typeof v==='string'&&v.length<=40&&Number.isFinite(Date.parse(v)),'Invalid event timestamp.');return v;};
function json(v,max=8192){assert(v!==undefined,'Missing metadata.');let nodes=0;const visit=(value,depth)=>{assert(++nodes<=10000&&depth<=12,'Metadata exceeds nesting limit.');if(value===null)return;if(typeof value==='string'){text(value,'metadata text',max,true);return;}if(typeof value==='boolean'||typeof value==='number'&&Number.isFinite(value))return;assert(typeof value==='object'&&(Array.isArray(value)||Object.getPrototypeOf(value)===Object.prototype),'Invalid metadata value.');for(const [k,item] of Object.entries(value)){text(k,'metadata key',240,true);visit(item,depth+1);}};visit(v,0);assert(Buffer.byteLength(JSON.stringify(v))<=max,'Metadata exceeds size limit.');return copy(v);}
function criteria(values){assert(Array.isArray(values)&&values.length<=50,'At most 50 acceptance criteria are allowed.');const seen=new Set();return values.map(v=>{assert(v&&Object.keys(v).every(k=>['id','label','required'].includes(k)),'Invalid criterion.');text(v.id,'criterion ID',120);text(v.label,'criterion label',2048);assert(!seen.has(v.id)&&typeof v.required==='boolean','Duplicate or invalid criterion.');seen.add(v.id);return {id:v.id,label:v.label,required:v.required};});}
function source(v){assert(v&&Object.keys(v).every(k=>['kind','id'].includes(k)),'Invalid source reference.');return {kind:text(v.kind,'source kind',80),id:text(v.id,'source ID',240)};}
function alias(v){assert(v&&Object.keys(v).every(k=>['lifecycleID','alias','context'].includes(k)),'Invalid legacy alias.');return {lifecycleID:uuid(v.lifecycleID),alias:text(v.alias,'legacy alias',240),context:json(v.context,8192)};}
function registrationInput(r){uuid(r?.id);text(r.projectID,'project ID',240);text(r.ownerKey,'registration owner',500);assert(r.sourceRepositoryIdentity&&typeof r.sourceRepositoryIdentity.path==='string','Registration repository identity is required.');json(r.sourceRepositoryIdentity,8192);assert(['prepared','attached','attachment_failed'].includes(r.state),'Invalid registration attachment state.');assert(Array.isArray(r.sources)&&r.sources.length<=1000,'Invalid registration source links.');return {repositoryKey:digest(r.sourceRepositoryIdentity),sources:r.sources.map(source),ownerRef:r.ownerKey,attachmentState:r.state==='attached'?'attached':'pending'};}
function writeAtomic(file,body){const temporary=file+'.'+randomUUID()+'.tmp';try{writeFileSync(temporary,body,{flag:'wx',mode:0o600});const fd=openSync(temporary,'r');try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(temporary,file);const fdDir=openSync(path.dirname(file),'r');try{fsyncSync(fdDir);}finally{closeSync(fdDir);}}finally{try{unlinkSync(temporary);}catch{}}}

export class LifecycleStore {
 constructor(directory){mkdirSync(directory,{recursive:true});this.file=path.join(directory,'lifecycle.json');this.backups=path.join(directory,'lifecycle-backups');if(existsSync(this.file)){try{assert(statSync(this.file).size<=MAX_BYTES,'Lifecycle store exceeds 32 MiB.');const raw=readFileSync(this.file,'utf8');assert(Buffer.byteLength(raw)<=MAX_BYTES,'Lifecycle store exceeds 32 MiB.');this.data=JSON.parse(raw);this.validate(this.data);}catch(e){throw new Error(`Lifecycle store is damaged or unsupported; restore a versioned backup. ${e.message}`);}}else{this.data={version:1,revision:0,records:[],migrations:[],imports:[]};writeAtomic(this.file,JSON.stringify(this.data,null,2));}}
 get revision(){return this.data.revision;}
 validateRecord(r){uuid(r.id);assert(r.registrationID===r.id,'Lifecycle identity must equal annotation identity.');key(r.repositoryKey);text(r.projectID,'project ID',240);revision(r.revision);assert(r.revision>=1,'Invalid record revision.');revision(r.criteriaRevision);assert(r.criteriaRevision>=1,'Invalid criteria revision.');criteria(r.criteria);assert(Array.isArray(r.dependencies)&&r.dependencies.length<=100&&new Set(r.dependencies).size===r.dependencies.length,'Invalid lifecycle dependencies.');for(const id of r.dependencies){uuid(id);assert(id!==r.id,'Lifecycle cannot depend on itself.');}if(r.ownerRef!==null)text(r.ownerRef,'owner reference',500);if(r.registrationOwnerRef!==null)text(r.registrationOwnerRef,'registration owner reference',500);text(r.blocker,'blocker',2048,true);text(r.nextAction,'next action',2048,true);assert(['pending','attached','unattached'].includes(r.attachmentState),'Invalid attachment state.');stamp(r.createdAt);stamp(r.lastActivityAt);assert(Array.isArray(r.criteriaHistory)&&r.criteriaHistory.length<=100,'Invalid criteria history.');for(const h of r.criteriaHistory){revision(h.revision);criteria(h.criteria);stamp(h.at);}assert(r.criteriaHistory.some(h=>h.revision===r.criteriaRevision&&same(h.criteria,r.criteria)),'Current criteria history is missing.');json(r.annotationSnapshot,16384);if(r.originalRepositoryKey)key(r.originalRepositoryKey);if(r.originalProjectID)text(r.originalProjectID,'original project ID',240);assert(Array.isArray(r.sourceRefs)&&r.sourceRefs.length<=1000,'Invalid source links.');r.sourceRefs.forEach(source);assert(Array.isArray(r.aliases)&&r.aliases.length<=100,'Too many legacy aliases.');assert(new Set(r.aliases.map(v=>v.alias)).size===r.aliases.length,'Duplicate legacy alias.');r.aliases.forEach(v=>{alias(v);assert(v.lifecycleID===r.id,'Alias references another lifecycle.');});assert(Array.isArray(r.events)&&r.events.length<=MAX_EVENTS,'Lifecycle event history exceeds limit.');const seen=new Set();for(const e of r.events){uuid(e.id);assert(!seen.has(e.id),'Duplicate lifecycle event.');seen.add(e.id);text(e.type,'event type',80);stamp(e.at);json(e.detail,8192);}if(r.importContext){json(r.importContext,8192);assert(r.importContext.sourceHash,'Missing import provenance.');key(r.importContext.sourceHash);}}
 validate(data){assert(data?.version===1&&Array.isArray(data.records)&&data.records.length<=MAX_RECORDS&&Array.isArray(data.migrations)&&data.migrations.length<=1000&&Array.isArray(data.imports)&&data.imports.length<=1000,'Invalid lifecycle store schema.');revision(data.revision);const ids=new Map();for(const r of data.records){this.validateRecord(r);assert(!ids.has(r.id),'Duplicate lifecycle ID.');ids.set(r.id,r);}for(const r of data.records)for(const dependency of r.dependencies)assert(ids.get(dependency)?.repositoryKey===r.repositoryKey,'Dependency missing or belongs to another repository.');const requests=new Set();for(const m of data.migrations){key(m.repositoryKey);text(m.requestKey,'migration request',240);key(m.sourceHash);text(m.releaseConvention,'release convention',2048);json(m.sourceMetadata,65536);assert(m.rulesAcknowledged===true&&Array.isArray(m.aliases)&&m.aliases.length<=1000,'Invalid migration policy.');for(const a of m.aliases){alias(a);assert(ids.get(a.lifecycleID)?.repositoryKey===m.repositoryKey,'Migration alias repository mismatch.');}key(m.inputHash);stamp(m.at);const k=m.repositoryKey+':'+m.requestKey;assert(!requests.has(k),'Duplicate migration request.');requests.add(k);}const imports=new Set();for(const i of data.imports){text(i.requestKey,'import request',240);key(i.sourceHash);key(i.repositoryKey);stamp(i.at);assert(Array.isArray(i.recordIDs)&&i.recordIDs.length<=MAX_RECORDS,'Invalid import records.');i.recordIDs.forEach(uuid);assert(!imports.has(i.requestKey),'Duplicate import request.');imports.add(i.requestKey);}}
 backup(){mkdirSync(this.backups,{recursive:true});const file=path.join(this.backups,`lifecycle-v1-r${String(this.revision).padStart(12,'0')}-${randomUUID()}.json`);writeAtomic(file,JSON.stringify(this.data,null,2));const files=readdirSync(this.backups).filter(f=>/^lifecycle-v1-r\d{12}-[a-f0-9-]+\.json$/.test(f)).sort();while(files.length>BACKUPS)unlinkSync(path.join(this.backups,files.shift()));}
 change(fn){const data=copy(this.data),result=fn(data);data.revision++;this.validate(data);const body=JSON.stringify(data,null,2);assert(Buffer.byteLength(body)<=MAX_BYTES,'Lifecycle store exceeds 32 MiB.');this.backup();writeAtomic(this.file,body);this.data=data;return copy(result);}
 get(id){const r=this.data.records.find(r=>r.id===id);assert(r,'Lifecycle record not found.',404);return copy(r);}
 list(repositoryKey){key(repositoryKey);return copy(this.data.records.filter(r=>r.repositoryKey===repositoryKey));}
 append(r,type,detail,at=now()){assert(r.events.length<MAX_EVENTS,'Lifecycle event history is full. Export history before continuing.');r.events.push({id:randomUUID(),type,detail:json(detail),at});r.lastActivityAt=Date.parse(at)>Date.parse(r.lastActivityAt)?at:r.lastActivityAt;r.revision++;}
 ensure(registration){const info=registrationInput(registration),existing=this.data.records.find(r=>r.id===registration.id);if(existing){assert(existing.repositoryKey===info.repositoryKey&&existing.projectID===registration.projectID,'Canonical registration identity changed; explicit reassociation is required.',409);if(existing.importContext&&existing.attachmentState==='unattached')return copy(existing);const sources=info.sources.filter(s=>!existing.sourceRefs.some(old=>same(old,s))),ownerChanged=existing.registrationOwnerRef!==info.ownerRef,attachmentChanged=existing.attachmentState!==info.attachmentState;if(!sources.length&&!ownerChanged&&!attachmentChanged)return copy(existing);return this.change(d=>{const r=d.records.find(r=>r.id===existing.id);for(const s of sources)r.sourceRefs.push(s);if(ownerChanged){this.bumpCriteria(r);this.append(r,'owner-linked',{previous:r.registrationOwnerRef,current:info.ownerRef,criteriaRevision:r.criteriaRevision});r.ownerRef=info.ownerRef;r.registrationOwnerRef=info.ownerRef;}if(sources.length)this.append(r,'sources-linked',{sourceCount:sources.length});if(attachmentChanged){r.attachmentState=info.attachmentState;this.append(r,'attachment-observed',{state:info.attachmentState});}return r;});}
  return this.change(d=>{const at=now(),r={id:registration.id,registrationID:registration.id,repositoryKey:info.repositoryKey,projectID:registration.projectID,revision:1,criteriaRevision:1,criteria:[],criteriaHistory:[{revision:1,criteria:[],at}],annotationSnapshot:{purpose:registration.purpose??'',workRef:registration.workRef??'',origin:registration.origin?source(registration.origin):null},dependencies:[],ownerRef:info.ownerRef,registrationOwnerRef:info.ownerRef,blocker:'',nextAction:'',aliases:[],sourceRefs:info.sources,events:[{id:randomUUID(),type:'registered',detail:{ownerRef:info.ownerRef,sourceCount:info.sources.length},at}],lastActivityAt:at,createdAt:at,attachmentState:info.attachmentState,importContext:null};d.records.push(r);return r;});
 }
 update(id,input){assert(input&&Object.keys(input).every(k=>['expectedRevision','criteria','blocker','nextAction','dependencies','ownerRef'].includes(k)),'Invalid lifecycle edit.');const existing=this.get(id);assert(input.expectedRevision===existing.revision,'Lifecycle changed. Refresh before saving.',409);const edits={};if('criteria' in input)edits.criteria=criteria(input.criteria);for(const k of ['blocker','nextAction'])if(k in input)edits[k]=text(input[k],k,2048,true);if('ownerRef' in input){edits.ownerRef=input.ownerRef===null?null:text(input.ownerRef,'owner reference',500);assert(existing.attachmentState!=='unattached'||edits.ownerRef===null,'Rebind imported work before assigning ownership.',409);}if('dependencies' in input){assert(Array.isArray(input.dependencies)&&input.dependencies.length<=100,'Too many dependencies.');edits.dependencies=input.dependencies.map(uuid);assert(new Set(edits.dependencies).size===edits.dependencies.length&&!edits.dependencies.includes(id),'Invalid dependencies.');for(const dependency of edits.dependencies)assert(this.get(dependency).repositoryKey===existing.repositoryKey,'Dependency belongs to another repository.',403);}
  if(Object.entries(edits).every(([k,v])=>same(existing[k],v)))return existing;
  return this.change(d=>{const r=d.records.find(r=>r.id===id);const changes={};for(const [k,v] of Object.entries(edits))if(!same(r[k],v)){changes[k]={before:r[k],after:v};r[k]=v;}if(changes.criteria||changes.ownerRef||changes.dependencies)this.bumpCriteria(r);this.append(r,'updated',{fields:Object.keys(changes),criteriaRevision:r.criteriaRevision,...(changes.ownerRef?{previousOwnerRef:changes.ownerRef.before,ownerRef:changes.ownerRef.after}:{})});return r;});
 }
 bumpCriteria(r){assert(r.criteriaHistory.length<100,'Criteria history is full. Export history before continuing.');r.criteriaRevision++;r.criteriaHistory.push({revision:r.criteriaRevision,criteria:copy(r.criteria),at:now()});}
 event(id,input){assert(input&&Object.keys(input).every(k=>['expectedRevision','type','detail','at'].includes(k)),'Invalid lifecycle event.');const existing=this.get(id);assert(input.expectedRevision===existing.revision,'Lifecycle changed. Refresh before recording.',409);const type=text(input.type,'event type',80),detail=json(input.detail),at=input.at===undefined?now():stamp(input.at);assert(Date.parse(at)<=Date.now()+60000,'Event time is in the future.');return this.change(d=>{const r=d.records.find(r=>r.id===id);this.append(r,type,detail,at);return r;});}
 rebind(registration,{expectedRevision}){const info=registrationInput(registration),existing=this.get(registration.id);assert(existing.revision===expectedRevision,'Lifecycle changed. Refresh before rebind.',409);assert(existing.repositoryKey===info.repositoryKey&&existing.projectID===registration.projectID&&registration.state==='attached','Verified matching registration is required for rebind.',409);assert(existing.attachmentState==='unattached','Lifecycle is already bound.',409);return this.change(d=>{const r=d.records.find(r=>r.id===existing.id);r.attachmentState='attached';r.ownerRef=info.ownerRef;r.registrationOwnerRef=info.ownerRef;this.bumpCriteria(r);for(const s of info.sources)if(!r.sourceRefs.some(old=>same(old,s)))r.sourceRefs.push(s);this.append(r,'rebound',{registrationID:r.id,repositoryKey:r.repositoryKey,ownerRef:info.ownerRef});return r;});}
 snapshot(repositoryKey,{projectID}={}){key(repositoryKey);if(projectID!==undefined)text(projectID,'project scope',240);const records=this.list(repositoryKey).map(r=>{if(projectID===undefined||r.projectID===projectID)return r;r.sourceRefs=[];r.annotationSnapshot.origin=null;r.ownerRef=null;r.registrationOwnerRef=null;if(r.importContext)r.importContext.originalOwnerRef=null;for(const event of r.events)event.detail={redacted:true};return r;});const body={version:1,kind:'skd-lifecycle',repositoryKey,revision:this.revision,records,migrations:copy(this.data.migrations.filter(m=>m.repositoryKey===repositoryKey)),artifacts:{included:false,references:[],message:'Lifecycle metadata only; evidence and artifact contents are not included.'}};return {...body,hash:digest(body)};}
 importSnapshot(snapshot,{requestKey,expectedRevision,repositoryKey,projectID}){text(requestKey,'import request',240);if(projectID!==undefined)text(projectID,'target project ID',240);assert(snapshot&&typeof snapshot==='object'&&Buffer.byteLength(JSON.stringify(snapshot))<=MAX_BYTES,'Invalid or oversized lifecycle snapshot.');const {hash:sourceHash,...body}=snapshot;key(sourceHash);assert(body.version===1&&body.kind==='skd-lifecycle'&&digest(body)===sourceHash,'Lifecycle snapshot checksum or version does not match.');key(body.repositoryKey);const targetRepositoryKey=repositoryKey===undefined?body.repositoryKey:key(repositoryKey);assert(Array.isArray(body.records)&&body.records.every(r=>r.repositoryKey===body.repositoryKey)&&Array.isArray(body.migrations)&&body.migrations.every(m=>m.repositoryKey===body.repositoryKey),'Snapshot crosses repository scope.');this.validate({version:1,revision:body.revision,records:body.records,migrations:body.migrations,imports:[]});const prior=this.data.imports.find(i=>i.requestKey===requestKey);if(prior){assert(prior.sourceHash===sourceHash&&prior.repositoryKey===targetRepositoryKey&&(prior.projectID??null)===(projectID??null),'Import request key was used for another snapshot or repository.',409);return copy(prior);}assert(expectedRevision===this.revision,'Lifecycle store changed. Refresh restore preview.',409);const repeated=this.data.imports.find(i=>i.sourceHash===sourceHash&&i.repositoryKey===targetRepositoryKey&&(i.projectID??null)===(projectID??null));if(repeated)return copy(repeated);for(const r of body.records)assert(!this.data.records.some(old=>old.id===r.id),'Lifecycle ID already exists. Restore does not overwrite local history.',409);for(const m of body.migrations)assert(!this.data.migrations.some(old=>old.repositoryKey===targetRepositoryKey&&old.requestKey===m.requestKey),'Migration history already exists.',409);
  return this.change(d=>{const at=now();for(const original of body.records){const r=copy(original);r.originalRepositoryKey=r.originalRepositoryKey||r.repositoryKey;r.repositoryKey=targetRepositoryKey;if(projectID!==undefined){r.originalProjectID=r.originalProjectID||r.projectID;r.projectID=projectID;}r.events=r.events.map(e=>({...e,imported:true}));r.importContext={sourceHash,originalAttachmentState:r.attachmentState,originalOwnerRef:r.ownerRef,importedAt:at};r.attachmentState='unattached';r.ownerRef=null;r.registrationOwnerRef=null;r.revision++;d.records.push(r);}d.migrations.push(...copy(body.migrations).map(m=>({...m,originalRepositoryKey:m.originalRepositoryKey||m.repositoryKey,repositoryKey:targetRepositoryKey})));const receipt={requestKey,sourceHash,repositoryKey:targetRepositoryKey,originalRepositoryKey:body.repositoryKey,projectID:projectID??null,recordIDs:body.records.map(r=>r.id),at};d.imports.push(receipt);return receipt;});
 }
 migration(repositoryKey,input){key(repositoryKey);assert(input&&Object.keys(input).every(k=>['requestKey','expectedRevision','aliases','releaseConvention','sourceHash','sourceMetadata','rulesAcknowledged'].includes(k)),'Invalid migration request.');text(input.requestKey,'migration request',240);assert(input.rulesAcknowledged===true,'Acknowledge the change of authority and release rules before migration.');assert(Array.isArray(input.aliases)&&input.aliases.length<=1000,'Too many migration aliases.');const payload={repositoryKey,requestKey:input.requestKey,aliases:input.aliases.map(alias),releaseConvention:text(input.releaseConvention,'release convention',2048),sourceHash:key(input.sourceHash),sourceMetadata:json(input.sourceMetadata,65536),rulesAcknowledged:true},inputHash=digest(payload);const previous=this.data.migrations.find(m=>m.repositoryKey===repositoryKey&&m.requestKey===input.requestKey);if(previous){assert(previous.inputHash===inputHash||previous.originalRepositoryKey&&previous.inputHash===digest({...payload,repositoryKey:previous.originalRepositoryKey}),'Migration request key was already used for different metadata.',409);return copy(previous);}assert(input.expectedRevision===this.revision,'Lifecycle store changed. Refresh migration preview.',409);for(const a of payload.aliases){const r=this.get(a.lifecycleID);assert(r.repositoryKey===repositoryKey,'Legacy alias belongs to another repository.',403);const old=r.aliases.find(v=>v.alias===a.alias);assert(!old||same(old,a),'Legacy alias context is immutable.',409);}
  return this.change(d=>{for(const a of payload.aliases){const r=d.records.find(r=>r.id===a.lifecycleID);if(!r.aliases.some(v=>same(v,a))){r.aliases.push(a);this.append(r,'legacy-alias-imported',{alias:a.alias,sourceHash:payload.sourceHash});}}const migration={...payload,inputHash,at:now()};d.migrations.push(migration);return migration;});
 }
}
