import {copyFileSync,existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {assert} from './domain.js';

const providers=['codex','claude'],clone=value=>structuredClone(value),stamp=()=>new Date().toISOString();
const text=(value,label,max,required=true)=>{assert(typeof value==='string'&&(!required||value.trim())&&Buffer.byteLength(value)<=max,`${label} is invalid.`);return value.trim();};
const ids=(value,label)=>{assert(Array.isArray(value)&&value.length<=100&&value.every(id=>typeof id==='string'&&id.length<=300),`${label} are invalid.`);return [...new Set(value)];};
function validateScope(scope,projects){assert(scope&&['global','project'].includes(scope.kind),'Choose a playbook scope.');if(scope.kind==='project')assert(projects.some(project=>project.id===scope.projectID&&project.id!=='unassigned'),'Project not found.',404);return scope;}
function validateStore(value){
 assert(value&&value.schema===1&&Number.isInteger(value.revision)&&value.revision>=0&&Array.isArray(value.entries)&&Array.isArray(value.defaults),'Damaged playbooks library. Restore playbooks.json from backup.');
 for(const entry of value.entries)assert(entry&&typeof entry.id==='string'&&Number.isInteger(entry.version)&&entry.version>0&&['global','project'].includes(entry.scope)&&Array.isArray(entry.providers)&&entry.providers.length&&entry.providers.every(provider=>providers.includes(provider))&&Array.isArray(entry.skillIDs)&&Array.isArray(entry.connectionIDs)&&Array.isArray(entry.history)&&typeof entry.archived==='boolean','Damaged playbooks library. Restore playbooks.json from backup.');
 for(const item of value.defaults)assert(item&&typeof item.projectID==='string'&&providers.includes(item.provider)&&typeof item.playbookID==='string'&&Number.isInteger(item.revision)&&item.revision>=0,'Damaged playbook defaults. Restore playbooks.json from backup.');
 return value;
}
function historical(entry){return {version:entry.version,name:entry.name,description:entry.description,scope:entry.scope,projectID:entry.projectID||null,providers:clone(entry.providers),skillIDs:clone(entry.skillIDs),connectionIDs:clone(entry.connectionIDs),source:clone(entry.source||null),updatedAt:entry.updatedAt};}
function provenance(source){if(!source)return null;assert(source&&['session','playbook'].includes(source.kind),'Invalid playbook provenance.');if(source.kind==='session'){assert(typeof source.sessionID==='string'&&source.sessionID.length<=100,'Invalid source session.');return {kind:'session',sessionID:source.sessionID,agent:providers.includes(source.agent)?source.agent:null,playbookID:typeof source.playbookID==='string'?source.playbookID:null,playbookVersion:Number.isInteger(source.playbookVersion)?source.playbookVersion:null,snapshotVersion:1};}assert(typeof source.playbookID==='string'&&Number.isInteger(source.version),'Invalid source playbook.');return {kind:'playbook',playbookID:source.playbookID,version:source.version};}

export class Playbooks {
 constructor(directory,{skills,connections}={}){
  mkdirSync(directory,{recursive:true});this.file=path.join(directory,'playbooks.json');this.skills=skills;this.connections=connections;
  this.data=existsSync(this.file)?validateStore(JSON.parse(readFileSync(this.file,'utf8'))):{schema:1,revision:0,entries:[],defaults:[]};
  if(!existsSync(this.file))this.persist(false);
 }
 persist(backup=true){const temporary=this.file+'.tmp';writeFileSync(temporary,JSON.stringify(this.data,null,2),{mode:0o600});if(backup&&existsSync(this.file))copyFileSync(this.file,this.file+'.bak');renameSync(temporary,this.file);}
 change(expectedRevision,fn){assert(expectedRevision===this.data.revision,'Playbooks changed in another tab. Reload before saving.',409);const draft=clone(this.data),result=fn(draft);draft.revision++;validateStore(draft);const previous=this.data;this.data=draft;try{this.persist();}catch(error){this.data=previous;throw error;}return clone(result);}
 visible(projectID=null){return clone(this.data.entries.filter(entry=>!projectID||entry.scope==='global'||entry.projectID===projectID));}
 inventory(projects,scope){const checked=validateScope(scope,projects),entries=this.visible(checked.kind==='project'?checked.projectID:null);return {scope:clone(checked),revision:this.data.revision,entries,defaults:clone(this.data.defaults.filter(item=>checked.kind==='global'||item.projectID===checked.projectID))};}
 async eligible(input,projects,ignoreID=null){
  const scope=validateScope(input.scope,projects),providerList=ids(input.providers,'Providers');assert(providerList.length&&providerList.every(provider=>providers.includes(provider)),'Choose at least one supported provider.');
  const skillIDs=ids(input.skillIDs||[],'Skill selections'),connectionIDs=ids(input.connectionIDs||[],'Connection selections');
  if(!this.skills&&!this.connections)return {scope,providers:providerList,skillIDs,connectionIDs};
  const skillInventory=this.skills?await this.skills.inventory(projects,scope):{managed:[]},connectionInventory=this.connections?await this.connections.inventory(projects,scope):{connections:[]};
  for(const id of skillIDs){const entry=skillInventory.managed.find(item=>item.id===id&&!item.archived);assert(entry,'A selected skill is missing, archived, or outside this playbook scope.',409);if(scope.kind==='global')assert(entry.scope==='global','Global playbooks cannot include project skills.',409);}
  for(const id of connectionIDs){const entry=connectionInventory.connections.find(item=>item.id===id&&!item.shadowed&&item.configured);assert(entry,'A selected connection is missing, unavailable, or outside this playbook scope.',409);assert(providerList.includes(entry.provider),'A selected connection belongs to a provider this playbook does not support.',409);if(scope.kind==='global')assert(!entry.projectID,'Global playbooks cannot include project connections.',409);}
  return {scope,providers:providerList,skillIDs,connectionIDs};
 }
 async create(input,projects){
  if(input.creationRequestKey){const prior=this.data.entries.find(entry=>entry.creationRequestKey===input.creationRequestKey);if(prior)return clone(prior);}
  const selection=await this.eligible(input,projects),name=text(input.name,'Playbook name',100),description=text(input.description||'','Description',1000,false);
  return this.change(input.revision,draft=>{const at=stamp(),source=provenance(input.source),entry={id:randomUUID(),version:1,scope:selection.scope.kind,...(selection.scope.kind==='project'?{projectID:selection.scope.projectID}:{}),name,description,providers:selection.providers,skillIDs:selection.skillIDs,connectionIDs:selection.connectionIDs,archived:false,createdAt:at,updatedAt:at,history:[],...(input.creationRequestKey?{creationRequestKey:text(input.creationRequestKey,'Creation request key',200)}:{}),...(source?{source}:{})};draft.entries.push(entry);return entry;});
 }
 async update(id,input,projects){const selection=await this.eligible(input,projects,id),name=text(input.name,'Playbook name',100),description=text(input.description||'','Description',1000,false);return this.change(input.revision,draft=>{const entry=draft.entries.find(item=>item.id===id);assert(entry,'Playbook not found.',404);assert(entry.version===input.version,'Playbook changed in another tab. Reload before saving.',409);entry.history.push(historical(entry));entry.history=entry.history.slice(-50);Object.assign(entry,{version:entry.version+1,scope:selection.scope.kind,name,description,providers:selection.providers,skillIDs:selection.skillIDs,connectionIDs:selection.connectionIDs,updatedAt:stamp()});if(selection.scope.kind==='project')entry.projectID=selection.scope.projectID;else delete entry.projectID;return entry;});}
 archive(id,input){return this.change(input.revision,draft=>{const entry=draft.entries.find(item=>item.id===id);assert(entry,'Playbook not found.',404);assert(entry.version===input.version,'Playbook changed in another tab. Reload before saving.',409);entry.history.push(historical(entry));entry.history=entry.history.slice(-50);entry.archived=Boolean(input.archived);entry.version++;entry.updatedAt=stamp();if(entry.archived)draft.defaults=draft.defaults.filter(item=>item.playbookID!==entry.id);return entry;});}
 async duplicate(id,input,projects){const source=this.data.entries.find(item=>item.id===id);assert(source,'Playbook not found.',404);return this.create({revision:input.revision,name:input.name||`${source.name} copy`,description:source.description,scope:source.scope==='project'?{kind:'project',projectID:source.projectID}:{kind:'global'},providers:source.providers,skillIDs:source.skillIDs,connectionIDs:source.connectionIDs,creationRequestKey:input.creationRequestKey,source:{kind:'playbook',playbookID:source.id,version:source.version}},projects);}
 async saveDefault(input,projects){const project=projects.find(item=>item.id===input.projectID&&item.id!=='unassigned');assert(project,'Project not found.',404);assert(providers.includes(input.provider),'Choose Codex or Claude.');const entry=this.data.entries.find(item=>item.id===input.playbookID&&!item.archived&&(item.scope==='global'||item.projectID===project.id)&&item.providers.includes(input.provider));assert(entry,'Choose an eligible playbook.',409);await this.eligible({scope:entry.scope==='project'?{kind:'project',projectID:entry.projectID}:{kind:'global'},providers:entry.providers,skillIDs:entry.skillIDs,connectionIDs:entry.connectionIDs},projects);return this.change(input.revision,draft=>{let item=draft.defaults.find(item=>item.projectID===project.id&&item.provider===input.provider);if(!item){assert(input.defaultRevision===0,'Playbook default changed in another tab. Reload before saving.',409);item={projectID:project.id,provider:input.provider,playbookID:entry.id,revision:0};draft.defaults.push(item);}else assert(item.revision===input.defaultRevision,'Playbook default changed in another tab. Reload before saving.',409);item.playbookID=entry.id;item.revision++;item.updatedAt=stamp();return item;});}
 clearDefault(input,projects){assert(projects.some(item=>item.id===input.projectID&&item.id!=='unassigned'),'Project not found.',404);assert(providers.includes(input.provider),'Choose Codex or Claude.');return this.change(input.revision,draft=>{const index=draft.defaults.findIndex(item=>item.projectID===input.projectID&&item.provider===input.provider);if(index<0){assert(input.defaultRevision===0,'Playbook default changed in another tab. Reload before saving.',409);return null;}assert(draft.defaults[index].revision===input.defaultRevision,'Playbook default changed in another tab. Reload before saving.',409);return draft.defaults.splice(index,1)[0];});}
 get(id){const entry=this.data.entries.find(item=>item.id===id);assert(entry,'Playbook not found.',404);return clone(entry);}
 select(project,provider,input={mode:'inherit'}){
  assert(project?.id&&providers.includes(provider),'Invalid playbook launch context.');assert(input&&['inherit','selected','legacy'].includes(input.mode||'inherit'),'Invalid playbook selection.');
  if(input.mode==='legacy')return {status:'legacy',source:'explicit',skillSelection:input.skills||{mode:'inherit',skillIDs:[]},connectionSelection:input.connections||{mode:'inherit',connectionIDs:[]}};
  const defaultItem=this.data.defaults.find(item=>item.projectID===project.id&&item.provider===provider),id=input.mode==='selected'?input.playbookID:defaultItem?.playbookID;
  if(!id)return {status:'legacy',source:'fallback',skillSelection:input.skills||{mode:'inherit',skillIDs:[]},connectionSelection:input.connections||{mode:'inherit',connectionIDs:[]}};
  const entry=this.data.entries.find(item=>item.id===id);assert(entry&&!entry.archived,'Selected playbook is missing or archived. Refresh before launching.',409);assert(entry.scope==='global'||entry.projectID===project.id,'Selected playbook belongs to another project.',403);assert(entry.providers.includes(provider),'Selected playbook does not support this provider.',409);if(input.version!==undefined)assert(entry.version===input.version,'Selected playbook changed after preview. Review it before launching.',409);
  const skillIDs=input.overrides&&Object.hasOwn(input.overrides,'skillIDs')?ids(input.overrides.skillIDs,'Skill overrides'):clone(entry.skillIDs),connectionIDs=input.overrides&&Object.hasOwn(input.overrides,'connectionIDs')?ids(input.overrides.connectionIDs,'Connection overrides'):clone(entry.connectionIDs);
  return {status:'selected',source:input.mode==='selected'?'explicit':'project-default',id:entry.id,version:entry.version,name:entry.name,scope:entry.scope,projectID:entry.projectID||null,providers:clone(entry.providers),base:{skillIDs:clone(entry.skillIDs),connectionIDs:clone(entry.connectionIDs)},overrides:{skills:Boolean(input.overrides&&Object.hasOwn(input.overrides,'skillIDs')),connections:Boolean(input.overrides&&Object.hasOwn(input.overrides,'connectionIDs'))},skillSelection:{mode:'replace',skillIDs},connectionSelection:{mode:'replace',connectionIDs}};
 }
 async preview(project,provider,input={mode:'inherit'},{purpose='session',mode='worktree'}={}){
  const selected=this.select(project,provider,input);if(selected.status==='legacy')return {...selected,signature:null,skills:null,connections:null,exclusions:[]};
  const skills=this.skills?.resolve(project,provider,selected.skillSelection,{purpose})||{status:'empty',entries:[],text:''},connections=this.connections?await this.connections.resolve(project,provider,selected.connectionSelection,{purpose,mode}):{status:'excluded',connections:[],reason:'Connections are unavailable.'};
  if(selected.connectionSelection.connectionIDs.length)assert(['managed','empty'].includes(connections.status),'This playbook contains MCP connections that are not supported in the selected workspace or entry point.',409);
  const deliveredSkills=new Set(skills.entries.map(entry=>entry.id)),exclusions=selected.skillSelection.skillIDs.filter(id=>!deliveredSkills.has(id)).map(id=>({type:'skill',id,reason:'Excluded by current project policy.'}));
  const safeConnections=clone(connections);delete safeConnections._connections;
  const proof={playbook:{id:selected.id,version:selected.version},skills:skills.entries.map(entry=>({id:entry.id,version:entry.version})),connections:safeConnections.connections.map(entry=>({id:entry.id,fingerprint:entry.fingerprint}))};
  const signature=createHash('sha256').update(JSON.stringify(proof)).digest('hex');return {...selected,signature,skills,connections:safeConnections,exclusions};
 }
 async resolveLaunch(project,provider,input,{purpose='session',mode='worktree'}={}){const preview=await this.preview(project,provider,input,{purpose,mode});if(preview.status==='selected'){assert(typeof input.expectedSignature==='string'&&input.expectedSignature===preview.signature,'Playbook resources changed after preview. Review the effective selection before launching.',409);}return preview;}
 async sessionDraft(session,projects){
  assert(session&&session.id&&providers.includes(session.agent),'Session not found.',404);const project=projects.find(item=>item.id===session.projectID);assert(project,'The source session project is unavailable.',409);const scope={kind:'project',projectID:project.id},[skillsInventory,connectionsInventory]=await Promise.all([this.skills?.inventory(projects,scope),this.connections?.inventory(projects,scope)]),configuredSkills=session.agentContext?.skills?.entries||[],configuredConnections=session.agentContext?.connections?.connections||[],observedConnections=new Set((session.toolActivity?.aggregates?.connections||[]).map(item=>item.id).filter(Boolean));
  const skills=configuredSkills.map(frozen=>{const current=skillsInventory?.managed?.find(item=>item.id===frozen.id);return {id:frozen.id,name:frozen.name||current?.name||frozen.id,configured:true,observed:'unknown',status:!current?'missing':current.archived?'archived':current.scope==='global'||current.projectID===project.id?'available':'incompatible',frozenVersion:frozen.version,currentVersion:current?.version||null};}),connections=configuredConnections.map(frozen=>{const current=connectionsInventory?.connections?.find(item=>item.id===frozen.id&&!item.shadowed);return {id:frozen.id,name:frozen.name||current?.name||frozen.id,provider:frozen.provider||session.agent,configured:true,observed:observedConnections.has(frozen.id),status:!current?'missing':!current.configured?'revoked':current.provider!==session.agent?'incompatible':'available',frozenFingerprint:frozen.fingerprint||null,currentFingerprint:current?.fingerprint||null};});
  const native=session.agentContext?.connections?.status==='native',legacy=!session.agentContext;return {sourceSessionID:session.id,projectID:project.id,agent:session.agent,name:`${session.task||'Session'} playbook`.slice(0,100),scope,providers:[session.agent],skillIDs:skills.map(item=>item.id),connectionIDs:connections.map(item=>item.id),skills,connections,coverage:clone(session.toolActivity?.coverage||{status:'unknown',source:'legacy',reason:'This session predates structured activity capture.'}),observedOnlyAvailable:session.toolActivity?.coverage?.status==='complete',incomplete:legacy||native,reasons:[...(legacy?['This legacy session has no frozen managed configuration.']:[]),...(native?['The session used native provider MCP configuration, whose exact reusable identities were not frozen.']:[])],sourcePlaybook:session.agentContext?.playbook?.status==='selected'?{id:session.agentContext.playbook.id,version:session.agentContext.playbook.version}:null};
 }
 async createFromSession(input,session,projects){const draft=await this.sessionDraft(session,projects);assert(input.sourceSessionID===session.id,'Source session changed. Reload the draft.',409);return this.create({...input,providers:input.providers||draft.providers,source:{kind:'session',sessionID:session.id,agent:session.agent,playbookID:draft.sourcePlaybook?.id,playbookVersion:draft.sourcePlaybook?.version}},projects);}
}

export const playbookProviders=providers;
