import {mkdirSync,existsSync,readFileSync,writeFileSync,renameSync,unlinkSync,openSync,closeSync,fsyncSync,statSync,constants} from 'node:fs';
import {realpath,stat,lstat,readlink,open} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {assert,copy,now} from './domain.js';
import {readGit} from './git-read.js';
import {inspectFolder} from './projects.js';

const MAX_BYTES=32*1024*1024,MAX_RECORDS=10000,PREVIEW_MS=120000;
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const text=(value,label,max,required=true)=>{assert(typeof value==='string'&&value.length<=max&&!value.includes('\0')&&(!required||value.trim()),`Invalid ${label}.`);return value;};
const hash=value=>createHash('sha256').update(value).digest('hex');
const inside=(folder,root)=>folder===root||folder.startsWith(root+path.sep);
async function git(folder,args){const r=await readGit(folder,args,{raw:true});assert(r.ok,'Workspace inspection failed or exceeded its output limit. Refresh and inspect the workspace.',409);return r.value;}
async function identity(folder){const canonical=await realpath(folder),s=await stat(canonical,{bigint:true});assert(s.isDirectory(),'Workspace directory is unavailable.',409);return {path:canonical,device:String(s.dev),inode:String(s.ino),birthTime:String(s.birthtimeNs)};}
async function dirtyCapture(folder){
 const status=await git(folder,['status','--porcelain=v2','--branch','-z','--untracked-files=all','--ignore-submodules=none']);
 assert(!(await git(folder,['ls-files','--stage','-z'])).split('\0').some(row=>row.startsWith('160000 ')),'Workspaces with submodules require manual inspection before continuation.',409);
 const staged=await git(folder,['diff','--cached','--binary','--no-ext-diff','--no-textconv','HEAD','--']);
 const unstaged=await git(folder,['diff','--binary','--no-ext-diff','--no-textconv','--']);
 const names=(await git(folder,['ls-files','--others','--exclude-standard','-z'])).split('\0').filter(Boolean).sort();assert(names.length<=1000,'Workspace has too many untracked files to safely preview.',409);
 let bytes=0;const untracked=[];
 for(const name of names){
  const file=path.resolve(folder,name);assert(inside(file,folder)&&inside(await realpath(path.dirname(file)),folder),'Untracked path is outside the workspace.',409);
  const s=await lstat(file);assert(s.isFile()||s.isSymbolicLink(),'Unsupported untracked file. Inspect it manually.',409);let digest;
  if(s.isSymbolicLink()){const content=await readlink(file);bytes+=Buffer.byteLength(content);assert(bytes<=16*1024*1024,'Untracked content exceeds the 16 MiB preview limit.',409);digest=hash(content);}
  else{const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const initial=await handle.stat();assert(initial.isFile(),'Untracked file type changed.',409);const hasher=createHash('sha256');const buffer=Buffer.alloc(65536);for(;;){const maximum=Math.min(buffer.length,16*1024*1024-bytes+1);const {bytesRead}=await handle.read(buffer,0,maximum,null);if(!bytesRead)break;bytes+=bytesRead;assert(bytes<=16*1024*1024,'Untracked content exceeds the 16 MiB preview limit.',409);hasher.update(buffer.subarray(0,bytesRead));}const final=await handle.stat();assert(initial.ino===final.ino&&initial.size===final.size&&initial.mtimeMs===final.mtimeMs,'Untracked file changed during inspection.',409);digest=hasher.digest('hex');}finally{await handle.close();}}
  untracked.push([name,s.mode,digest]);
 }
 assert(status===await git(folder,['status','--porcelain=v2','--branch','-z','--untracked-files=all','--ignore-submodules=none']),'Workspace changed during preview. Refresh and try again.',409);
 return hash(JSON.stringify({status,staged,unstaged,untracked}));
}
async function dirtyIdentity(folder){const first=await dirtyCapture(folder);assert(first===await dirtyCapture(folder),'Workspace content changed during inspection. Refresh and try again.',409);return first;}
export class WorkspaceTasks {
 constructor(directory,{notes,gitStatus,executor,terminals,project,projects,originContext=()=>null}){
  Object.assign(this,{notes,gitStatus,executor,terminals,project,projects,originContext});this.previews=new Map();this.pending=new Set();mkdirSync(directory,{recursive:true});this.file=path.join(directory,'workspace-tasks.json');
  if(existsSync(this.file)){try{assert(statSync(this.file).size<=MAX_BYTES,'Store exceeds size limit.');const raw=readFileSync(this.file,'utf8');assert(Buffer.byteLength(raw)<=MAX_BYTES,'Store exceeds size limit.');this.data=JSON.parse(raw);this.validate(this.data);}catch(e){throw new Error(`Workspace task store is damaged or unsupported; restore a backup. ${e.message}`);}}
  else{this.data={version:1,tasks:[],operations:[]};this.persist(this.data);}
 }
 validate(data){assert(data?.version===1&&Array.isArray(data.tasks)&&Array.isArray(data.operations)&&data.tasks.length<=MAX_RECORDS&&data.operations.length<=MAX_RECORDS,'Invalid workspace task store.');const ids=new Set(),keys=new Set();for(const t of data.tasks){text(t.id,'task ID',240);assert(!ids.has(t.id),'Duplicate task identity.');ids.add(t.id);text(t.projectID,'project ID',240);assert(typeof t.destination==='string'&&path.isAbsolute(t.destination)&&t.destination.length<=4096&&!t.destination.includes('\0'),'Invalid task destination.');assert(t.registrationID===null||typeof t.registrationID==='string'&&/^[0-9a-f-]{36}$/i.test(t.registrationID),'Invalid task registration.');if(t.state==='attached')assert(t.registrationID,'Attached task requires registration.');text(t.createdAt,'task creation time',80);assert(t.error===null||typeof t.error==='string'&&t.error.length<=1000,'Invalid task error.');text(t.originalTask,'original task',100000,false);text(t.acceptance,'acceptance',20000,false);text(t.purpose,'purpose',240,false);text(t.workRef,'work reference',500);assert(['pending','attached','failed'].includes(t.state),'Invalid task state.');}for(const o of data.operations){text(o.id,'operation ID',240);text(o.projectID,'project ID',240);text(o.requestKey,'request key',240);const key=o.projectID+':'+o.requestKey;assert(!keys.has(key),'Duplicate operation request.');keys.add(key);assert(['adopt','continue'].includes(o.kind)&&['pending','attached','started','failed'].includes(o.state)&&ids.has(o.taskID),'Invalid operation.');assert(o.request&&o.previewIdentity&&typeof o.previewIdentity.content==='string'&&o.previewIdentity.content.length===64&&typeof o.previewIdentity.git==='string','Missing operation identity.');for(const key of ['root','common','admin']){const value=o.previewIdentity[key];assert(value&&typeof value.path==='string'&&path.isAbsolute(value.path),'Invalid operation filesystem path.');for(const field of ['device','inode','birthTime'])text(value[field],'operation filesystem identity',100);}assert(data.tasks.find(t=>t.id===o.taskID).projectID===o.projectID,'Operation project mismatch.');text(o.createdAt,'operation creation time',80);if(o.kind==='adopt'){text(o.request.purpose,'request purpose',240,false);text(o.request.workRef,'request reference',500,false);text(o.request.acceptance,'request acceptance',20000,false);assert(['pending','attached','failed'].includes(o.state),'Invalid adoption state.');}else{for(const field of ['agent','model','effort'])text(o.request[field],'continuation selection',240);text(o.request.task,'next instruction',20000);assert(['pending','started','failed'].includes(o.state),'Invalid continuation state.');if(o.state==='started')text(o.sessionID,'session ID',240);}}}
 persist(data){const body=JSON.stringify(data,null,2);assert(Buffer.byteLength(body)<=MAX_BYTES,'Workspace task store exceeds 32 MiB.');const temporary=this.file+'.'+randomUUID()+'.tmp';try{writeFileSync(temporary,body,{flag:'wx',mode:0o600});const fd=openSync(temporary,'r');try{fsyncSync(fd);}finally{closeSync(fd);}renameSync(temporary,this.file);const dir=openSync(path.dirname(this.file),'r');try{fsyncSync(dir);}finally{closeSync(dir);}}finally{try{unlinkSync(temporary);}catch{}}}
 change(fn){const data=copy(this.data),result=fn(data);this.validate(data);this.persist(data);this.data=data;return copy(result);}
 list(project){return copy({tasks:this.data.tasks.filter(t=>t.projectID===project.id),operations:this.data.operations.filter(o=>o.projectID===project.id&&['pending','failed'].includes(o.state)).map(({previewIdentity,request,...o})=>o)});}
 current(project){const current=this.project(project.id);assert(current&&current.version===project.version&&current.folderPath===project.folderPath,'Project changed. Reopen workspace details.',409);assert(!current.benchmark,'Benchmark projects cannot adopt or continue workspaces.',409);return current;}
 available(){assert(!this.executor.owner&&!this.executor.active&&!this.executor.starting&&!this.executor.cleaning,'Finish the active session or workflow first.',409);}
 previewRecord(project,id){const p=this.previews.get(id);assert(p&&p.project.id===project.id&&p.project.version===project.version&&p.expires>Date.now(),'Preview expired. Refresh workspace details.',409);this.current(p.project);return p;}
 async inspect(project,snapshot,rowID){
  this.current(project);assert(snapshot.status==='connected'&&!snapshot.stale&&!snapshot.partial&&!snapshot.truncated,'Complete, current Git status is required. Refresh local status.',409);
  const row=snapshot.worktrees.find(w=>w.id===rowID);assert(row&&row.available&&!row.stale&&!row.locked&&!row.prunable&&!row.bare&&!row.detached&&row.branch&&row.operations?.length===0&&!row.changes?.conflicts,'Workspace is unavailable, locked, detached, conflicted, or has a pending Git operation.',409);
  const root=await identity(row.path),common=await identity(snapshot.commonDirectory),admin=await identity((await git(row.path,['rev-parse','--absolute-git-dir'])).trim());
  assert(root.path===row.path&&common.path===(await realpath((await git(row.path,['rev-parse','--path-format=absolute','--git-common-dir'])).trim())),'Workspace repository identity changed.',409);
  assert(admin.path!==common.path&&!row.current&&!['main','master',snapshot.defaultBranch,(snapshot.target?.ref?.startsWith('refs/remotes/')?snapshot.target.ref.split('/').slice(3).join('/'):snapshot.target?.ref?.replace(/^refs\/heads\//,''))].filter(Boolean).includes(row.branch),'Primary, source, main, and comparison-target workspaces cannot be adopted or continued.',409);
  for(const p of this.projects()){if(!p.folderPath)continue;const folder=await realpath(p.folderPath).catch(()=>null);assert(!folder||!inside(folder,root.path),'This workspace is a connected project source checkout. Use an isolated workspace.',409);}
  for(const file of ['index.lock','HEAD.lock'])assert(!await stat(path.join(admin.path,file)).then(()=>true,e=>{if(e.code==='ENOENT')return false;throw e;}),'Git has an active lock. Wait for its operation to finish.',409);
  const candidates=this.notes.list().filter(r=>r.destination===row.path);assert(candidates.length<=1,'Workspace has ambiguous retained registrations. Inspect its history.',409);let registration=null;
  let recoveryTask=this.data.tasks.find(t=>t.projectID===project.id&&t.destination===row.path&&['failed','pending'].includes(t.state)),recoveryOperation=recoveryTask?this.data.operations.find(o=>o.kind==='adopt'&&o.taskID===recoveryTask.id):null;if(candidates.length){registration=candidates[0];if(recoveryTask)assert(recoveryTask.registrationID===registration.id||recoveryTask.registrationID===null&&registration.origin.kind==='adoption'&&registration.origin.id===recoveryTask.id&&registration.ownerKey==='task:'+recoveryTask.id,'Incomplete association has a different registration.',409);assert(registration.projectID===project.id,'Associate or continue this workspace from its original project.',403);assert(registration.classification!=='benchmark','Benchmark workspaces cannot be continued.',409);if(recoveryTask&&recoveryOperation){assert(same(registration.sourceRepositoryIdentity,common),'Source repository identity changed.',409);if(registration.attachment)assert(same(registration.attachment,{root,commonDirectory:common,administrativeDirectory:admin}),'Workspace attachment identity changed.',409);}else registration=await this.notes.verify(registration.id,row.path,registration.ownerKey);}
  const task=registration?this.data.tasks.find(t=>t.registrationID===registration.id&&t.projectID===project.id&&t.state==='attached'):null;
  const original=(task||recoveryTask)?{task:(task||recoveryTask).originalTask,acceptance:(task||recoveryTask).acceptance}:registration?await this.originContext(registration):null;
  const fingerprint={root,common,admin,git:snapshot._identity,content:await dirtyIdentity(row.path),registrationID:registration?.id||null,registrationRevision:registration?.revision||null,registrationData:registration?{purpose:registration.purpose,notes:registration.notes,workRef:registration.workRef,ownerKey:registration.ownerKey,projectID:registration.projectID}:null};
  if(recoveryOperation){const old=copy(recoveryOperation.previewIdentity),current=copy(fingerprint);for(const key of ['registrationID','registrationRevision','registrationData']){delete old[key];delete current[key];}assert(same(old,current),'Incomplete adoption workspace changed. Inspect it manually before reassociation.',409);}
  return {row,registration,task,original,fingerprint,recoveryTask,recoveryOperation};
 }
 async preview(project,input){
  assert(input&&Object.keys(input).every(k=>['snapshotID','projectVersion','worktreeID'].includes(k)),'Invalid workspace preview request.');assert(input.projectVersion===project.version,'Project changed. Refresh local status.',409);this.gitStatus.prune();const saved=this.gitStatus.snapshots.get(input.snapshotID);assert(saved&&saved.project.id===project.id&&saved.project.version===project.version&&saved.project.folderPath===project.folderPath,'Status expired or belongs to another project. Refresh local status.',409);
  const fresh=await this.gitStatus.inspect(project.folderPath,{targetRef:saved.snapshot.target?.ref||'',remoteName:saved.snapshot.selectedRemote||''});assert(fresh._identity===saved.snapshot._identity,'Repository changed. Refresh local status.',409);const inspected=await this.inspect(project,fresh,input.worktreeID);this.current(project);
  const id=randomUUID(),expires=Date.now()+PREVIEW_MS;for(const [key,p] of this.previews)if(p.expires<Date.now())this.previews.delete(key);assert(this.previews.size<100,'Too many open workspace previews. Close older previews and try shortly.',429);
  this.previews.set(id,{id,expires,project:copy(project),snapshot:fresh,...inspected});
  return {id,projectVersion:project.version,path:inspected.row.path,branch:inspected.row.branch,dirty:inspected.row.dirty,worktreeID:input.worktreeID,registrationID:inspected.registration?.id||null,taskID:inspected.task?.id||null,purpose:inspected.registration?.purpose||'',workRef:inspected.registration?.workRef||'',acceptance:inspected.original?.acceptance||'',originalTask:inspected.original?.task||'',recoveryRequestKey:inspected.recoveryOperation?.requestKey||null,recoveryRequest:inspected.recoveryOperation?copy(inspected.recoveryOperation.request):null,expiresAt:new Date(expires).toISOString()};
 }
 async recheck(p,{allowRegistration=null}={}){
  this.current(p.project);assert(p.expires>Date.now(),'Preview expired. Refresh workspace details.',409);const snapshot=await this.gitStatus.inspect(p.project.folderPath,{targetRef:p.snapshot.target?.ref||'',remoteName:p.snapshot.selectedRemote||''});const current=await this.inspect(p.project,snapshot,p.row.id);const expected=copy(p.fingerprint);if(allowRegistration){expected.registrationID=current.fingerprint.registrationID;expected.registrationRevision=current.fingerprint.registrationRevision;if(!p.registration)expected.registrationData=current.fingerprint.registrationData;assert(current.registration?.id===allowRegistration,'Workspace registration changed.',409);}assert(same(expected,current.fingerprint),'Workspace content or identity changed. Refresh and confirm ownership again.',409);this.current(p.project);return current;
 }
 request(project,input,kind){assert(input&&Object.keys(input).every(k=>['previewID','requestKey','confirmOwnership',...(kind==='adopt'?['purpose','workRef','acceptance']:['agent','model','effort','task'])].includes(k)),'Invalid workspace task request.');this.current(project);assert(input?.confirmOwnership===true,'Confirm that no external writer owns this workspace and that current changes belong to this task.');text(input.requestKey,'request key',240);const request=kind==='adopt'?{purpose:text(input.purpose??'','purpose',240,false),workRef:text(input.workRef??'','work reference',500,false),acceptance:text(input.acceptance??'','acceptance',20000,false)}:{agent:text(input.agent,'agent',80),model:text(input.model,'model',240),effort:text(input.effort,'effort',80),task:text(input.task,'next instruction',20000)};const existing=this.data.operations.find(o=>o.projectID===project.id&&o.requestKey===input.requestKey);if(existing)assert(existing.kind===kind&&same(existing.request,request),'Request key was already used for different work.',409);return {request,existing};}
 async adopt(project,input){
  const {request,existing}=this.request(project,input,'adopt');if(existing?.state==='attached')return copy(this.data.tasks.find(t=>t.id===existing.taskID));const p=this.previewRecord(project,input.previewID);if(existing){const before=copy(existing.previewIdentity),after=copy(p.fingerprint);for(const key of ['registrationID','registrationRevision','registrationData']){delete before[key];delete after[key];}assert(same(before,after)&&(!p.registration||p.registration.id===this.data.tasks.find(t=>t.id===existing.taskID)?.registrationID||p.registration.origin.kind==='adoption'&&p.registration.origin.id===existing.taskID&&p.registration.ownerKey==='task:'+existing.taskID),'Adoption recovery requires the unchanged original workspace.',409);}this.available();const owner='adoption:'+randomUUID();this.executor.owner=owner;let operation=existing;
  try{
   const checked=await this.recheck(p);assert(!checked.task,'Workspace already has a task. Refresh to continue it.',409);let task;
   if(!operation){assert(!this.data.tasks.some(t=>t.projectID===project.id&&t.destination===p.row.path),'Workspace has an incomplete association. Retry its original request with a fresh preview.',409);text(checked.original?.task||request.purpose,'original task or purpose',100000);const id=randomUUID();task={id,projectID:project.id,destination:p.row.path,registrationID:checked.registration?.id||null,state:'pending',purpose:checked.registration?.purpose??request.purpose,workRef:checked.registration?.workRef||request.workRef||'local:'+id,originalTask:checked.original?.task||request.purpose,acceptance:checked.original?.acceptance??request.acceptance,createdAt:now(),error:null};operation={id:randomUUID(),projectID:project.id,kind:'adopt',requestKey:input.requestKey,request,previewIdentity:p.fingerprint,taskID:id,state:'pending',createdAt:now()};this.change(d=>{d.tasks.push(task);d.operations.push(operation);});}else task=this.data.tasks.find(t=>t.id===operation.taskID);
   let registration=checked.registration;
   if(!registration){registration=this.notes.prepare({intentID:'adoption:'+task.id,projectID:project.id,sourceContext:await inspectFolder(project.folderPath),destination:p.row.path,branch:p.row.branch,purpose:task.purpose,origin:{kind:'adoption',id:task.id},workRef:task.workRef,ownerKey:'task:'+task.id,classification:'development'});this.change(d=>{d.tasks.find(t=>t.id===task.id).registrationID=registration.id;});}
   if(registration.state!=='attached')registration=await this.notes.attach(registration.intentID,{expectedRevision:registration.revision,validate:()=>this.current(project)});
   await this.recheck(p,{allowRegistration:registration.id});return this.change(d=>{const t=d.tasks.find(t=>t.id===task.id);t.registrationID=registration.id;t.state='attached';t.error=null;d.operations.find(o=>o.id===operation.id).state='attached';return t;});
  }catch(e){if(operation)this.change(d=>{const o=d.operations.find(o=>o.id===operation.id);o.state='failed';o.error=String(e.message).slice(0,1000);const t=d.tasks.find(t=>t.id===o.taskID);t.state='failed';t.error=o.error;});throw e;}finally{if(this.executor.owner===owner)this.executor.owner=null;}
 }
 async continue(project,input){
  const {request,existing}=this.request(project,input,'continue');if(existing){assert(existing.state==='started'&&existing.sessionID,'This continuation is pending, interrupted, or failed. Inspect sessions and use a new explicit request.',409);return {sessionID:existing.sessionID,taskID:existing.taskID};}const p=this.previewRecord(project,input.previewID);assert(p.task?.state==='attached','Adopt this workspace before continuing.',409);const key=project.id+':'+input.requestKey;assert(!this.pending.has(key),'Continuation is already being prepared.',409);this.pending.add(key);let operation;
  try{this.available();await this.recheck(p);assert(!this.data.operations.some(o=>o.projectID===project.id&&o.requestKey===input.requestKey),'Continuation request already exists.',409);operation={id:randomUUID(),projectID:project.id,kind:'continue',requestKey:input.requestKey,request,previewIdentity:p.fingerprint,taskID:p.task.id,state:'pending',createdAt:now()};this.change(d=>d.operations.push(operation));const context=await inspectFolder(p.row.path);const registration=this.notes.get(p.registration.id);const session=await this.terminals.start({agent:request.agent,model:request.model,effort:request.effort,mode:'worktree',task:request.task,initialPrompt:`Original task:\n${p.task.originalTask}\n\nAcceptance criteria (unchanged):\n${p.task.acceptance}\n\nWorkspace purpose:\n${registration.purpose}\n\nNext instruction:\n${request.task}`},project,{workspace:{workingDirectory:p.row.path,worktreePath:p.row.path,branch:p.row.branch,sourceContext:context,workspaceRegistrationID:registration.id,workspaceOwnerKey:registration.ownerKey,taskID:p.task.id},shouldLaunch:async()=>{await this.recheck(p,{allowRegistration:registration.id});return true;}});const sessionID=session.id||session.sessionID;assert(sessionID,'Terminal did not return a session identity.');this.change(d=>{const o=d.operations.find(o=>o.id===operation.id);o.state='started';o.sessionID=sessionID;});return {sessionID,taskID:p.task.id};
  }catch(e){if(operation)this.change(d=>{const o=d.operations.find(o=>o.id===operation.id);o.state='failed';o.error=String(e.message).slice(0,1000);});throw e;}finally{this.pending.delete(key);}
 }
}
